### ISSUE TITLE
Config command broken when using with Drupal 8.0.0-beta15

### ISSUE THREAD

**Issue by luksak** [drush-ops/drush#1690]
When running config commands on Drupal 8.0.0-beta15 and older like config-export I get this error:

```
$ drush cex
exception 'Exception' with message 'The configuration directory type 'CONFIG_SYNC_DIRECTORY' does not exist' in ~/core/includes/bootstrap.inc:177
Stack trace:
#0 ~/.composer/vendor/drush/drush/commands/core/config.drush.inc(335): config_get_config_directory('CONFIG_SYNC_DIR...')
#1 [internal function]: drush_config_export()
#2 ~/.composer/vendor/drush/drush/includes/command.inc(364): call_user_func_array('drush_config_ex...', Array)
#3 ~/.composer/vendor/drush/drush/includes/command.inc(215): _drush_invoke_hooks(Array, Array)
#4 [internal function]: drush_command()
#5 ~/.composer/vendor/drush/drush/includes/command.inc(183): call_user_func_array('drush_command', Array)
#6 ~/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#7 ~/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 ~/.composer/vendor/drush/drush/drush.php(11): drush_main()
#9 {main}
```

**Comment by weitzman** [comment]
Yep - you updated Drush without updating Drupal core. Due to flux in Drupal, thats not goijng to work. Please update Drupal to RC1 or higher.
