### ISSUE TITLE
drush site-install: exception 'Drush\Sql\SqlException' with message 'Unable to find a    [error] matching SQL Class. Drush cannot find your database connection details.'

### ISSUE THREAD

**Issue by jepster** [drush-ops/drush#1772]
Tested in Drush 7.1 and 8-dev on Mac OSX Yosemite. Installed via composer and wget from Github repository. If I run 
```
drush si
```
or
```
drush site-install
```
Either with --db-url param or not, I get the following error message:
```
exception 'Drush\Sql\SqlException' with message 'Unable to find a    [error]
matching SQL Class. Drush cannot find your database connection
details.' in
/Users/jepster/.composer/vendor/drush/drush/commands/sql/sql.drush.inc:597
Stack trace:
#0
/Users/jepster/.composer/vendor/drush/drush/commands/core/site_install.drush.inc(107):
drush_sql_get_class()
#1 [internal function]: drush_core_pre_site_install()
#2
/Users/jepster/.composer/vendor/drush/drush/includes/command.inc(359):
call_user_func_array('drush_core_pre_...', Array)
#3
/Users/jepster/.composer/vendor/drush/drush/includes/command.inc(210):
_drush_invoke_hooks(Array, Array)
#4 [internal function]: drush_command()
#5
/Users/jepster/.composer/vendor/drush/drush/includes/command.inc(178):
call_user_func_array('drush_command', Array)
#6
/Users/jepster/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62):
drush_dispatch(Array)
#7 /Users/jepster/.composer/vendor/drush/drush/drush.php(70):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /Users/jepster/.composer/vendor/drush/drush/drush.php(11):
drush_main()
#9 {main}
user-Pro:d7-1 jepster$ 
```

**Comment by jepster** [comment]
I'm running PHP 5.6.7.

**Comment by weitzman** [comment]
It looks like Drush can't find your root. maybe pass --root. Please post the exact command you are running along with output. Use --debug for more info.

**Comment by jepster** [comment]
Thanks for your reply. I had specified the wrong command. I've forgot the host. The command must be: drush si --db-url=mysql://USERNAME:PASSWORD@HOST/DATABASE. Closing this issue.
