### ISSUE TITLE
urol executed via bash throws exception error if role has a space in it

### ISSUE THREAD

**Issue by btopro** [drush-ops/drush#1829]
Role name "teaching assistant"

command executed is:

`drush @comply-all urol "teaching assistant" sdf --y`

if I copy and paste this it works fine. if the following command is called from a bash script it bricks every time when encapsulating the role name (which is needed otherwise it's evaluated by drush as two different arguments). Anyone experience anything similar?

```
[ulmusdrush@localhost ~]$ exception 'Drush\Role\RoleException' with message 'Could not find the role: "teaching' in          [error]
/home/ulmusdrush/.composer/vendor/drush/drush/lib/Drush/Role/RoleBase.php:46
Stack trace:
#0 [internal function]: Drush\Role\RoleBase->__construct('"teaching')
#1 /home/ulmusdrush/.composer/vendor/drush/drush/includes/drush.inc(113):
ReflectionClass->newInstanceArgs(Array)
#2 /home/ulmusdrush/.composer/vendor/drush/drush/commands/core/role.drush.inc(273):
drush_get_class('Drush\\Role\\Role', Array)
#3 /home/ulmusdrush/.composer/vendor/drush/drush/commands/user/user.drush.inc(281):
drush_role_get_class('"teaching')
#4 [internal function]: drush_user_add_role('"teaching', 'assistant"', 'qwe')
#5 /home/ulmusdrush/.composer/vendor/drush/drush/includes/command.inc(359):
call_user_func_array('drush_user_add_...', Array)
#6 /home/ulmusdrush/.composer/vendor/drush/drush/includes/command.inc(210):
_drush_invoke_hooks(Array, Array)
#7 [internal function]: drush_command('"teaching', 'assistant"', 'qwe')
#8 /home/ulmusdrush/.composer/vendor/drush/drush/includes/command.inc(178):
call_user_func_array('drush_command', Array)
#9 /home/ulmusdrush/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62):
drush_dispatch(Array)
#10 /home/ulmusdrush/.composer/vendor/drush/drush/drush.php(70):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#11 /home/ulmusdrush/.composer/vendor/drush/drush/drush.php(11): drush_main()
#12 {main}
```

**Comment by weitzman** [comment]
In the future, please ask support questions on <a href="http://drupal.stackexchange.com/questions/tagged/drush">Drupal Answers</a> and contribute code or report bugs on Github.
