### ISSUE TITLE
make drush work well with the config_readonly module

### ISSUE THREAD

**Issue by beejeebus** [drush-ops/drush#1934]
when the [Config Read-only](https://www.drupal.org/project/config_readonly) module is enabled, drush config commands that try to run Config->save() blow up messily.

add support for the module and integrate it gracefully.

current behaviour is this, when running for example 'drush config-edit system.site':

```
justin@trusty:/var/www/8-drupal/webroot 
 (8.1.x) $ drush config-edit system.site
exception 'Exception' with message 'Your site configuration active store is currently locked.' in                                [error]
/var/www/8-drupal/webroot/modules/config_readonly/src/Config/ConfigReadonlyStorage.php:118
Stack trace:
#0 /var/www/8-drupal/webroot/modules/config_readonly/src/Config/ConfigReadonlyStorage.php(71):
Drupal\config_readonly\Config\ConfigReadonlyStorage->checkLock()
#1 /var/www/8-drupal/webroot/core/lib/Drupal/Core/Config/Config.php(227):
Drupal\config_readonly\Config\ConfigReadonlyStorage->write('system.site', Array)
#2 /home/justin/vms_nfs_share/home-bin/drush/commands/core/config.drush.inc(754): Drupal\Core\Config\Config->save()
#3 [internal function]: drush_config_edit('system.site')
#4 /home/justin/vms_nfs_share/home-bin/drush/includes/command.inc(366): call_user_func_array('drush_config_ed...', Array)
#5 /home/justin/vms_nfs_share/home-bin/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#6 [internal function]: drush_command('system.site')
#7 /home/justin/vms_nfs_share/home-bin/drush/includes/command.inc(185): call_user_func_array('drush_command', Array)
#8 /home/justin/vms_nfs_share/home-bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#9 /home/justin/vms_nfs_share/home-bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#10 /home/justin/vms_nfs_share/home-bin/drush/drush.php(12): drush_main()
#11 {main}
```

**Comment by beejeebus** [comment]
closing.
