### ISSUE TITLE
exception 'Drush\User\UserListException' with message 'Unable to find a matching user for 1.'

### ISSUE THREAD

**Issue by AlexShapka** [drush-ops/drush#1953]
I have installed Drush per instructions on http://docs.drush.org/en/master/install, namely I performed:

```
wget http://files.drush.org/drush.phar
php drush.phar core-status
chmod +x drush.phar
sudo mv drush.phar /usr/local/bin/drush
drush init
```

It works fine for my Drupal 7 website in most cases:

```
drush status
 Drupal version                  :  7.41                    
 Site URI                        :  http://default          
 Database driver                 :  mysql                   
 Database hostname               :  localhost               
 Database port                   :                          
 Database username               :  irocps                   
 Database name                   :  irocps                   
 Drupal bootstrap                :  Successful              
 Drupal user                     :                          
 Default theme                   :  corolla                 
 Administration theme            :  adaptivetheme_admin     
 PHP configuration               :  /etc/php.ini            
 PHP OS                          :  Linux                   
 Drush script                    :  /usr/local/bin/drush    
 Drush version                   :  8.0.2                   
 Drush temp directory            :  /tmp                    
 Drush configuration             :                          
 Drush alias files               :                          
 Install profile                 :  standard                
 Drupal root                     :  /home/irocps/public_html 
 Site path                       :  sites/default           
 File directory path             :  sites/irocps.org/files   
 Private file directory path     :  /home/irocps/private     
 Temporary file directory path   :  /tmp  
```

 but is giving errors for some commands like, for example:

```
drush uli
exception 'Drush\User\UserListException' with message 'Unable to find a matching user for 1.' in                                                  [error]
phar:///usr/local/bin/drush/lib/Drush/User/UserList.php:114
Stack trace:
#0 phar:///usr/local/bin/drush/lib/Drush/User/UserList.php(15): Drush\User\UserList::getFromParameters(1)
#1 phar:///usr/local/bin/drush/commands/user/user.drush.inc(409): Drush\User\UserList->__construct(1)
#2 [internal function]: drush_user_login()
#3 phar:///usr/local/bin/drush/includes/command.inc(366): call_user_func_array('drush_user_logi...', Array)
#4 phar:///usr/local/bin/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#5 [internal function]: drush_command()
#6 phar:///usr/local/bin/drush/includes/command.inc(185): call_user_func_array('drush_command', Array)
#7 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#8 phar:///usr/local/bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#9 phar:///usr/local/bin/drush/includes/startup.inc(289): drush_main()
#10 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#11 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#12 {main}

```

I don't know why it would be looking for '/usr/local/bin/drush/lib' when there is no such a directory at all. As I said I followed the setup instructions on http://docs.drush.org/en/master/install, according to which the '/usr/local/bin/drush' is just as renamed 'drush.phar' file, it is not a directory.

**Comment by weitzman** [comment]
a .phar file is actually a package containing lots of files inside. So a uri like phar:///usr/local/bin/drush/lib/Drush/User/UserList.php refers to a file thats inside the drush.phar package.

Do you have a userID 1 in your database? Can you login as that user? Maybe try `drush uinf 1`

**Comment by AlexShapka** [comment]
Yes, this website has user #1, but it also giving the same error on any user "drush uli any_uid".

**Comment by weitzman** [comment]
Please answer all questions precisely (i.e. "in the database").
