### ISSUE TITLE
Calling drush vget --format=json inside a process without env vars returns PHP and not JSON!

### ISSUE THREAD

**Issue by davidfischer-ch** [drush-ops/drush#2025]
I am writing a Python 3 script to automated the deployment of a Drupal website.
The procedure calls `drush vget --format=json` to retrieve the website variables and iterate over it.

I tested this script successfully but then when the script is called by cron the scripts failed to decode the output of `drush`. In fact I discovered that in that case the output is not a valid JSON string but a PHP representation of the array (key value)!

I tested the command interactively using a python interactive shell and I discovered that when the environment variables (env) is empty then the drush command effectively behaves differently.

```
>>> import json, subprocess
>>> json.loads(subprocess.check_output(['drush', '-p', '-r', '/home/www/sandbox/drupal', 'vget', '--format=json'], env={}).decode('utf-8'))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```
VS

```
>>> import json, subprocess
>>> json.loads(subprocess.check_output(['drush', '-p', '-r', '/home/www/sandbox/drupal', 'vget', '--format=json']).decode('utf-8'))
{...} <- this is a python dict with the variables
```

**Comment by davidfischer-ch** [comment]
I found that drush needs PATH to be set.
