### ISSUE TITLE
PHP Fatal error:  Class 'Drupal\user\Entity\User' not found in /var/lib/nginx/.composer/vendor/drush/drush/lib/Drush/User/User8.php

### ISSUE THREAD

**Issue by keithyau** [drush-ops/drush#2046]
Hi there, 

having below issue. Any idea is appreciated.

`[nginx@ip-10-0-4-230 sites]$ drush dis module_builder
PHP Fatal error:  Class 'Drupal\user\Entity\User' not found in /var/lib/nginx/.composer/vendor/drush/drush/lib/Drush/User/User8.php on line 26
Drush command terminated abnormally due to an unrecoverable error.                                [error]
Error: Class 'Drupal\user\Entity\User' not found in
/var/lib/nginx/.composer/vendor/drush/drush/lib/Drush/User/User8.php, line 26
Drush was not able to start (bootstrap) Drupal.                                                   [error]
Hint: This error can only occur once the database connection has already been successfully
initiated, therefore this error generally points to a site configuration issue, and not a problem
connecting to the database.
`

Keith

**Comment by weitzman** [comment]
Please paste output of `drush status --verbose`

**Comment by michaellenahan** [comment]
```
vagrant@dkr:/var/www/drupalvm/dkr-web/docroot$ drush status --verbose
Executing: mysql --defaults-extra-file=/tmp/drush_cxOBMB --database=dkr --host=localhost --port=3306 --silent  < /tmp/drush_ypSCRo
Executing: mysql --defaults-extra-file=/tmp/drush_NLPAH1 --database=dkr --host=localhost --port=3306 --silent  < /tmp/drush_jV74JO
Error: Class 'Drupal\user\Entity\User' not found in Drush\User\User8->load_by_uid() (line 26 of                             [error]
/var/www/drupalvm/dkr-web/vendor/drush/drush/lib/Drush/User/User8.php) #0
/var/www/drupalvm/dkr-web/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php(558): Drush\User\User8->load_by_uid(0)
#1 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/bootstrap.inc(354): Drush\Boot\DrupalBoot->bootstrap_drupal_login()
#2 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/bootstrap.inc(509): drush_bootstrap(6, 7)
#3 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/bootstrap.inc(456): drush_bootstrap_max()
#4 /var/www/drupalvm/dkr-web/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(59): drush_bootstrap_to_phase(-2)
#5 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#6 phar:///usr/local/bin/drush/bin/drush.php(150): drush_main()
#7 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#8 {main}.
Error: Class 'Drupal\user\Entity\User' not found in /var/www/drupalvm/dkr-web/vendor/drush/drush/lib/Drush/User/User8.php on line 26 #0 /var/www/drupalvm/dkr-web/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php(558): Drush\User\User8->load_by_uid(0)
#1 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/bootstrap.inc(354): Drush\Boot\DrupalBoot->bootstrap_drupal_login()
#2 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/bootstrap.inc(509): drush_bootstrap(6, 7)
#3 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/bootstrap.inc(456): drush_bootstrap_max()
#4 /var/www/drupalvm/dkr-web/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(59): drush_bootstrap_to_phase(-2)
#5 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#6 phar:///usr/local/bin/drush/bin/drush.php(150): drush_main()
#7 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#8 {main}
Error: Class &#039;Drupal\user\Entity\User&#039; not found in Drush\User\User8->load_by_uid() (line 26 of /var/www/drupalvm/dkr-web/vendor/drush/drush/lib/Drush/User/User8.php).
Drush command terminated abnormally due to an unrecoverable error.                                                          [error]
A non well formed numeric value encountered drush.inc:1671                                                                     [notice]
ob_end_clean(): failed to delete buffer. No buffer to delete preflight.inc:786                                                 [notice]
Drush was not able to start (bootstrap) Drupal.                                                                             [error]
Hint: This error can only occur once the database connection has already been successfully initiated, therefore this error
generally points to a site configuration issue, and not a problem connecting to the database.

Drush was attempting to connect to:
 Drupal version                  :  8.4.5
 Site URI                        :  http://default
 Database driver                 :  mysql
 Database hostname               :  localhost
 Database port                   :  3306
 Database username               :  drupaluser
 Database name                   :  dkr
 Database                        :  Connected
 Administration theme            :  seven
 PHP configuration               :  /etc/php/7.1/cli/php.ini
 PHP OS                          :  Linux
 Drush script                    :  /usr/local/bin/drush
 Drush version                   :  8.1.15
 Drush temp directory            :  /tmp
 Drush configuration             :
 Drush alias files               :
 Install profile                 :  thunder
 Drupal root                     :  /var/www/drupalvm/dkr-web/docroot
 Drupal Settings File            :  sites/default/settings.php
 Site path                       :  sites/default
 File directory path             :  sites/default/files
 Temporary file directory path   :  /tmp
 Sync config path                :  ../config/sync
```

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.

**Comment by clfer** [comment]
For anyone coming from a google search:
http://www.john-brandenburg.com/blog/unable-run-drush-uli-drupal-8

Did your DB import finished properly?

**Comment by harivenuqed** [comment]
Delete the entire database and reimport a related one, the issue was resolved for me. something related to drush cache
