### ISSUE TITLE
Running drush sql-cli or sql-drop using --target fails in Drupal 8

### ISSUE THREAD

**Issue by generalredneck** [drush-ops/drush#2137]
my settings.php has the following:

```
<?php
/**
 * @file
 * Secret configuration settings for the site.
 */

$databases = array(
  'default' => array(
    'default' => array(
      'database' => 'drupal',
      'username' => 'drupal',
      'password' => 'drupal',
      'host' => 'localhost',
      'port' => '',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
  'migrate' => array(
    'default' => array(
      'database' => 'upgrade',
      'username' => 'drupal',
      'password' => 'drupal',
      'host' => 'localhost',
      'port' => '',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);
```

In this case doing `drush sql-drop --target=default -y` works. However doing `drush sql-drop --target=migrate` provides me with an exception 

```
exception 'Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class. Drush cannot    [error]
find your database connection details.' in
/var/www/html/build/vendor/drush/drush/commands/sql/sql.drush.inc:593
Stack trace:
#0 /var/www/html/build/vendor/drush/drush/commands/sql/sql.drush.inc(436): drush_sql_get_class()
#1 [internal function]: drush_sql_drop()
#2 /var/www/html/build/vendor/drush/drush/includes/command.inc(366):
call_user_func_array('drush_sql_drop', Array)
#3 /var/www/html/build/vendor/drush/drush/includes/command.inc(217): _drush_invoke_hooks(Array,
Array)
#4 [internal function]: drush_command()
#5 /var/www/html/build/vendor/drush/drush/includes/command.inc(185):
call_user_func_array('drush_command', Array)
#6 /var/www/html/build/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#7 /var/www/html/build/vendor/drush/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /var/www/html/build/vendor/drush/drush/drush.php(12): drush_main()
#9 {main}
```

the "upgrade" database does exist and the credentials are correct.

**Comment by weitzman** [comment]
Can't reproduce the problem with sql-drop using a non-default --target. Working fine here.

**Comment by generalredneck** [comment]
@weitzman real quick... I know I forgot to add my drush version. I'm using 8.1.0-rc1. are we testing on the same version. If not, let me test on the version you are on.

**Comment by weitzman** [comment]
I'm using master branch. If installing via composer, use 'dev-master' version

**Comment by generalredneck** [comment]
n/m... this was the biggest case of idiot...

![bitmoji](https://render.bitstrips.com/v2/cpanel/9176152-115908046_6-s1-v1.png?palette=1&width=246)

so if you take a look at my connection string and map it to flags... I should be using `--database`, not `--target`.
