### ISSUE TITLE
Exception for missing PHP extensions is not helpful

### ISSUE THREAD

**Issue by webflo** [drush-ops/drush#2158]
Discovered in https://github.com/drupal-composer/drupal-project/issues/144

---

Drush does not list the missing extensions in the log output. Core uses an inline twig template in the exception. Maybe thats the real reason why it does not work.

**Full log:**

```
$ ../vendor/bin/drush si --db-url=mysql://root@127.0.0.1/d8
You are about to CREATE the 'd8' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                                                                                                                                      [ok]
Drupal\Core\Installer\Exception\InstallerException: PHP extensions: Disabled                                                                                                                                                                                                      [error]

Array in /home/vagrant/d8/web/core/includes/install.core.inc:2162
Stack trace:
#0 /home/vagrant/d8/web/core/includes/install.core.inc(1020): install_display_requirements(Array, Array)
#1 /home/vagrant/d8/web/core/includes/install.core.inc(654): install_verify_requirements(Array)
#2 /home/vagrant/d8/web/core/includes/install.core.inc(532): install_run_task(Array, Array)
#3 /home/vagrant/d8/web/core/includes/install.core.inc(116): install_run_tasks(Array)
#4 /home/vagrant/d8/vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#5 /home/vagrant/d8/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#6 /home/vagrant/d8/vendor/drush/drush/commands/core/drupal/site_install.inc(80): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#7 /home/vagrant/d8/vendor/drush/drush/commands/core/site_install.drush.inc(247): drush_core_site_install_version('standard', Array)
#8 /home/vagrant/d8/vendor/drush/drush/includes/command.inc(366): drush_core_site_install()
#9 /home/vagrant/d8/vendor/drush/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#10 /home/vagrant/d8/vendor/drush/drush/includes/command.inc(185): drush_command()
#11 /home/vagrant/d8/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#12 /home/vagrant/d8/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#13 /home/vagrant/d8/vendor/drush/drush/drush.php(12): drush_main()
#14 {main}
```

**Comment by weitzman** [comment]
Yes, I would think it is the twig template. Why would we use such fancy display in an exception. I nthe installer. Ugh.

**Comment by drzraf** [comment]
should a core bug be opened? or can/should drush workaround this?

**Comment by webflo** [comment]
@drzraf Yes please on a core issue. I will help you to fix it.

**Comment by drzraf** [comment]
https://www.drupal.org/node/2833864
