### ISSUE TITLE
drush core-requirements, logicexception: Render context is empty...

### ISSUE THREAD

**Issue by dhendriks** [drush-ops/drush#2296]
The drush 'core-requirements' command results in a LogicException related to 'Render context is empty...'. I'm using the latest drush (8.1.3).

```console
$ drush core-requirements
LogicException: Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or[error]
#lazy_builder/#pre_render instead. in /home/<anonymized>/public_html/core/lib/Drupal/Core/Render/Renderer.php:241
Stack trace:
#0 /home/<anonymized>/public_html/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#1 /home/<anonymized>/public_html/core/includes/common.inc(870): Drupal\Core\Render\Renderer->render(Array, false)
#2 /home/<anonymized>/public_html/core/lib/Drupal/Core/Theme/ThemeManager.php(306): drupal_render(Array)
#3 /home/<anonymized>/public_html/modules/token/token.install(25): Drupal\Core\Theme\ThemeManager->render('item_list', Array)
#4 [internal function]: token_requirements('runtime')
#5 /home/<anonymized>/public_html/core/lib/Drupal/Core/Extension/ModuleHandler.php(402): call_user_func_array('token_requireme...',
Array)
#6 phar:///home/<anonymized>/drush.phar/commands/core/drupal/environment.inc(252):
Drupal\Core\Extension\ModuleHandler->invokeAll('requirements', Array)
#7 phar:///home/<anonymized>/drush.phar/commands/core/core.drush.inc(805): drush_module_invoke_all('requirements', 'runtime')
#8 phar:///home/<anonymized>/drush.phar/includes/command.inc(373): drush_core_requirements()
#9 phar:///home/<anonymized>/drush.phar/includes/command.inc(224): _drush_invoke_hooks(Array, Array)
#10 phar:///home/<anonymized>/drush.phar/includes/command.inc(192): drush_command()
#11 phar:///home/<anonymized>/drush.phar/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#12 phar:///home/<anonymized>/drush.phar/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#13 phar:///home/<anonymized>/drush.phar/includes/startup.inc(325): drush_main()
#14 phar:///home/<anonymized>/drush.phar/drush(114): drush_startup(Array)
#15 /home/<anonymized>/drush.phar(10): require('phar:///home/de...')
#16 {main}
```

**Comment by fiasco** [comment]
I'm seeing this issue too but its unclear whether drush should be providing a render context or if modules implementing hook_requirements shouldn't be calling render() within these functions.

**Comment by paulbrzeski** [comment]
I'm having this issue as well.

Maybe the context needs to handle being in a CLI? The warning seems like an assumption about it only running in the browser.
