### ISSUE TITLE
Container not initialized exception

### ISSUE THREAD

**Issue by jhedstrom** [drush-ops/drush#2297]
I'm running the latest 8.2.x, and latest master branch of drush, and seeing this exception on `drush cr`, and several other commands:

```
Error: Uncaught Drupal\Core\DependencyInjection\ContainerNotInitializedException: \Drupal::$container is not initialized yet. \Drupal::setContainer() must be called with a real container. in /.../drupal/core/lib/Drupal.php:129
Stack trace:
#0 /.../drupal/core/lib/Drupal.php(158): Drupal::getContainer()
#1 /.../drupal/core/includes/bootstrap.inc(480): Drupal::service('messenger')
#2 /.../drush/includes/drush.inc(1412): drupal_get_messages(NULL, true)
#3 /.../drush/includes/command.inc(213): _drush_log_drupal_messages()
#4 /.../drush/includes/command.inc(185): drush_command()
#5 /.../drush/lib/Drush/Boot/BaseBoot.php(73): drush_dispatch(Array)
#6 /.../drupal/core/lib/Drupal.php, line 129
```

**Comment by jhedstrom** [comment]
Actually, after pulling in 8.2.x actual latest changes, this went away.
