### ISSUE TITLE
sql-query --target fails when array of slave databases are defined

### ISSUE THREAD

**Issue by ttk** [drush-ops/drush#2461]
In the settings.php file the documentation says we can configure a array of slave connections as follows:

```
* The general format for the $databases array is as follows:
 * @code
 * $databases['default']['default'] = $info_array;
 * $databases['default']['slave'][] = $info_array;
 * $databases['default']['slave'][] = $info_array;
 * $databases['extra']['default'] = $info_array;
 * @endcode
```

The array of slaves is properly recognized in drupal and the following succeeds:
`db_query('SELECT * from variable where name=\'site_name\'',[],['target'=>'slave']);`

However, the equivalent drush command fails:
`drush sqlq --target=slave "SELECT * from variable where name='site_name'"`

with the following error:
```
Drush\Sql\SqlException: Unable to find a matching SQL Class. Drush cannot find your database connection details. in /usr/lib/php/drush/commands/sql/sql.drush.inc:593                                                                                      [error]
Stack trace:
#0 /usr/lib/php/drush/commands/sql/sql.drush.inc(421): drush_sql_get_class(NULL)
#1 /usr/lib/php/drush/includes/command.inc(366): drush_sql_query('SELECT * from v...')
#2 /usr/lib/php/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#3 /usr/lib/php/drush/includes/command.inc(185): drush_command('SELECT * from v...')
#4 /usr/lib/php/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#5 /usr/lib/php/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#6 /usr/lib/php/drush/drush.php(12): drush_main()
#7 {main}
```

Tested using ` Drush Version   :  8.0.5` using `Drupal version :  7.51`

**Comment by weitzman** [comment]
Would be great if you could provide a PR for this.

**Comment by weitzman** [comment]
Inactivity
