### ISSUE TITLE
Error when running Drush ULI

### ISSUE THREAD

**Issue by robballou** [drush-ops/drush#2568]
When running:

    drush ALIAS uli

I receive the following:

```
PHP Fatal error:  Uncaught Error: Call to a member function id() on null in /Users/example/.composer/vendor/drush/drush/lib/Drush/Commands/core/UserCommands.php:382
Stack trace:
#0 [internal function]: Drush\Commands\core\UserCommands->login('exampleuser', Array)
#1 /Users/example/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(180): call_user_func_array(Array, Array)
#2 /Users/example/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(129): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /Users/example/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(104): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /Users/example/.composer/vendor/drush/drush/includes/annotationcommand_adapter.inc(240): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\C in /Users/example/.composer/vendor/drush/drush/lib/Drush/Commands/core/UserCommands.php on line 382

Fatal error: Uncaught Error: Call to a member function id() on null in /Users/example/.composer/vendor/drush/drush/lib/Drush/Commands/core/UserCommands.php:382
Stack trace:
#0 [internal function]: Drush\Commands\core\UserCommands->login('exampleuser', Array)
#1 /Users/example/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(180): call_user_func_array(Array, Array)
#2 /Users/example/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(129): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /Users/example/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(104): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /Users/example/.composer/vendor/drush/drush/includes/annotationcommand_adapter.inc(240): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\C in /Users/example/.composer/vendor/drush/drush/lib/Drush/Commands/core/UserCommands.php on line 382
 [error]  Drush command terminated abnormally due to an unrecoverable error.
Error: Uncaught Error: Call to a member function id() on null in /Users/example/.composer/vendor/drush/drush/lib/Drush/Commands/core/UserCommands.php:382
Stack trace:
#0 [internal function]: Drush\Commands\core\UserCommands->login('exampleuser', Array)
#1 /Users/example/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(180): call_user_func_array(Array, Array)
#2 /Users/example/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(129): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /Users/example/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(104): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /Users/example/.composer/vendor/drush/drush/includes/annotationcommand_adapter.inc(240): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\C in /Users/example/.composer/vendor/drush/drush/lib/Drush/Commands/core/UserCommands.php, line 382
```

`Drush version : 9.0-dev-gcd88d481`

**Comment by weitzman** [comment]
Thanks for using master branch and reporting bugs.
