### ISSUE TITLE
Drupal Console and Mollom break Drush 

### ISSUE THREAD

**Issue by webmasterpf** [drush-ops/drush#2687]
Hi,

I don't know if it's the right place to post here but I get this issue after installing Drupal Console.When I try to use a drush command I get this:
```
The following module is missing from the file system: mollom bootstrap.inc:236                                                                             [warning]
Exception: Mollom Class could not be found. Please run composer in the module folder or install composer manager. in /home/xxx/www/pfdev_stage/drupal-8multi/modules/mollom/src/API/DrupalClient.php on line 14 #0 /home/xxx/bin/composer/composer.phar/vendor/composer/ClassLoader.php(440): include()
#1 /home/xxx/bin/composer/composer.phar/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/provence-...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Drupal\\mollom\\A...')
#3 /home/xxx/www/pfdev_stage/drupal-8multi/modules/mollom/src/API/DrupalTestClient.php(12): spl_autoload_call('Drupal\\mollom\\A...')
#4 /home/xxx/bin/composer/composer.phar/vendor/composer/ClassLoader.php(440): include('/home/provence-...')
#5 /home/xxx/bin/composer/composer.phar/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/provence-...')
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass('Drupal\\mollom\\A...')
#7 [internal function]: spl_autoload_call('Drupal\\mollom\\A...')
#8 /home/xxx/www/pfdev_stage/drupal-8multi/modules/devel/webprofiler/src/Compiler/ServicePass.php(75): ReflectionClass->__construct('Drupal\\mollom\\A...')
#9 /home/xxx/www/pfdev_stage/drupal-8multi/modules/devel/webprofiler/src/Compiler/ServicePass.php(26): Drupal\webprofiler\Compiler\ServicePass->extractData(Object(Drupal\Core\DependencyInjection\ContainerBuilder), Object(Symfony\Component\DependencyInjection\Compiler\ServiceReferenceGraph))
#10 /home/xxx/www/pfdev_stage/drupal-8multi/vendor/symfony/dependency-injection/Compiler/Compiler.php(104): Drupal\webprofiler\Compiler\ServicePass->process(Object(Drupal\Core\DependencyInjection\ContainerBuilder))
#11 /home/xxx/www/pfdev_stage/drupal-8multi/vendor/symfony/dependency-injection/ContainerBuilder.php(590): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Drupal\Core\DependencyInjection\ContainerBuilder))
#12 /home/xxx/www/pfdev_stage/drupal-8multi/core/lib/Drupal/Core/DrupalKernel.php(1263): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#13 /home/xxx/www/pfdev_stage/drupal-8multi/core/lib/Drupal/Core/DrupalKernel.php(866): Drupal\Core\DrupalKernel->compileContainer()
#14 /home/xxx/www/pfdev_stage/drupal-8multi/core/lib/Drupal/Core/DrupalKernel.php(461): Drupal\Core\DrupalKernel->initializeContainer()
#15 /home/xxx/bin/composer/composer.phar/vendor/drush/drush/lib/Drush/Boot/DrupalBoot8.php(149): Drupal\Core\DrupalKernel->boot()
#16 /home/xxx/bin/composer/composer.phar/vendor/drush/drush/includes/bootstrap.inc(354): Drush\Boot\DrupalBoot8->bootstrap_drupal_full()
#17 /home/xxx/bin/composer/composer.phar/vendor/drush/drush/includes/bootstrap.inc(473): drush_bootstrap(5, 6)
#18 /home/xxx/bin/composer/composer.phar/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(59): drush_bootstrap_to_phase(6)
#19 /home/xxx/bin/composer/composer.phar/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#20 /home/xxx/bin/composer/composer.phar/vendor/drush/drush/drush.php(12): drush_main()
#21 {main}
Drush command terminated abnormally due to an unrecoverable error.                                                                                         [error]
Error: Module 'curl' already loaded in Unknown, line 0
Exception: Mollom Class could not be found. Please run composer in the module folder or install composer manager. in include() (line 14 of /home/xxx/www/pfdev_stage/drupal-8multi/modules/mollom/src/API/DrupalClient.php).
```
How can I fix it ?
Thanks

**Comment by greg-1-anderson** [comment]
Is Mollom working from the Drupal web UI? The error message could mean that there is an incompatibility between these three components, as you suggested -- but it could also be caused if you are not using Composer to manage your Drupal site, which Mollom apparently now requires.
