### ISSUE TITLE
Error: Undefined class constant 'Drush\Log\LogLevel::FAILED' in drush/includes/drush.inc

### ISSUE THREAD

**Issue by awitjes** [drush-ops/drush#3190]
Hello,
I want to run 'drush updb -y' to performe updates. In one of our projects, it is important, that warnings during these updates are handled like errors, the update should fail on warnings. I found the --strict=2 option, which might be the thing we need, but I am not completely sure. So I wanted to try it out.

When I try to run drush updb with the --strict=2 option, it fails with the error: Undefined class constant 'Drush\Log\LogLevel::FAILED' in drush_log_has_errors() (includes/drush.inc)

When I add the constants LogLevel::WARNING, LogLevel::ERROR, LogLevel::FAILED in Log\LogLevel, the error goes away. 

To reproduce: Every drush command I tried with the --strict=2 option, failed with this error.

This problem is easily fixed, but my question is: What did you intend to do with theses constants? To which values should they be set? Are they even needed or is the drush_log_has_errors() wrong?

Thank you!

**Comment by weitzman** [comment]
what is the output of `drush version`?

**Comment by awitjes** [comment]
In one project 8.1.12, in another test project 8.1.15.

**Comment by greg-1-anderson** [comment]
This sort of looks like Drush versions are being mixed. Are you running pm-update on a Drupal site with a site-local Drush? That's not allowed. Site-local Drush should only be used on sites that are managed via Composer.

**Comment by awitjes** [comment]
Thanks for your responses, but I am still not sure, if that is the problem. 
I have a global drush(.phar) in my /usr/local/bin, with version 8.1.12. For this test, I renamed it to `drush.bak`.
If I type `drush version` after I renamed it to `drush.bak` it simply prints: `bash: /usr/local/bin/drush: No such file or directory`

I created a fresh project using the drupal-composer/drupal-project using `composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction`
After it finished, I used `composer require drush/drush @dev`. 
From the web directory of this new project, I had to give the whole path to drush
`../vendor/drush/drush/drush version` outputs `8.1.15`

If I try `../vendor/drush/drush/drush si --db-url=mysql://dev:dev@localhost/my_test_db --strict=2`it installs my drupal site, gives me the admin password as normal, even says everything is ok, but the last lines are showing the error again. I copied the lines from my command line:

```
dev@ubuntu:~/git/test-drush/web$ ../vendor/drush/drush/drush si --db-url=mysql://dev:dev@localhost/my_test_db --strict=2
You are about to CREATE the 'my_test_db' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the  [ok]
--notify global option.
Installation complete.  User name: admin  User password: gymEcbZUvj   [ok]
Congratulations, you installed Drupal!                                [status]
Error: Undefined class constant 'Drush\Log\LogLevel::FAILED' in /home/dev/git/test-drush/vendor/drush/drush/includes/drush.inc on line 1320 #0 /home/dev/git/test-drush/vendor/drush/drush/includes/preflight.inc(84): drush_log_has_errors()
#1 /home/dev/git/test-drush/vendor/drush/drush/drush.php(12): drush_main()
#2 {main}
Error: Undefined class constant &#039;Drush\Log\LogLevel::FAILED&#039; in drush_log_has_errors() (line 1320 of /home/dev/git/test-drush/vendor/drush/drush/includes/drush.inc).
```

If you still think, it might be my setup, I can do a complete new ubuntu installation on my virtualbox, install composer and git and try again.
Thanks for your time.

**Comment by greg-1-anderson** [comment]
If you are using drupal-composer/drupal-project, then you are using Composer to manage your Drupal site. If you are managing your Drupal site with Composer, then you should never run the `pm-update` or `pm-download` commands.

**Comment by awitjes** [comment]
I read my posts again and I think I was imprecise, in what I what the real problem is. Sorry to post here again, but I hope it makes to problem clear:

**What I want to do:** I want to use --strict=2 with drush commands, so warnings will result in a failed command execution.

**What happens, if I use it:**  even `drush --version --strict=2` results in 

```
drush --version --strict=2
 Drush Version   :  8.1.15 

PHP Fatal error:  Uncaught Error: Undefined class constant 'Drush\Log\LogLevel::FAILED' in /home/dev/git/clean-drush/vendor/drush/drush/includes/drush.inc:1320
Stack trace:
#0 /home/dev/git/clean-drush/vendor/drush/drush/includes/preflight.inc(84): drush_log_has_errors()
#1 /home/dev/git/clean-drush/vendor/drush/drush/drush.php(12): drush_main()
#2 {main}
  thrown in /home/dev/git/clean-drush/vendor/drush/drush/includes/drush.inc on line 1320
```

I understand the error message, I know how and where to define said constant. My IDE complains about it too and wants to fix it.
But please, could you check, if the constant really should be defined or if the function `drush_log_has_errors()` is in some way wrong? I don't understand enough of the inner workings of drush, to check it myself.

Thank you.

**Comment by greg-1-anderson** [comment]
I was able to reproduce this. It appears to be a bug in Drush after all.

**Comment by greg-1-anderson** [comment]
n.b. There is no failure in the master branch, but neither do we support `--strict=2` there, at least not at the moment.

**Comment by greg-1-anderson** [comment]
On master:
```
$ drush9 --version --strict=2
Drush Commandline Tool 9.0-dev-g5a3263f3
```
(Does not convert warnings into errors.)

**Comment by greg-1-anderson** [comment]
On Drush 8, I get the same results as reported by @awitjes

**Comment by Kingdutch** [comment]
This error is caused by the following commit: https://github.com/drush-ops/drush/commit/3657fa99a9c47e4684786ccac71270b2db27615e#diff-2a696f27c9b9fca50273053c32e258bf256a3da6dc6956e66d6e7cbdf4c71ba2R1295

That commit shows that the word `failed` was not actually used as an error level anywhere in Drush so the find/replace caused an error here (`FAILED` is not a valid PSR log level).

The correct fix is probably to replace `LogLevel::FAILED` with `LogLevel::CRITICAL` and add `LogLevel::ALERT` and `LogLevel::EMERGENCY`.

**Comment by greg-1-anderson** [comment]
Sounds reasonable. A PR would be appreciated.
