### ISSUE TITLE
Drush site-install without drush.yml

### ISSUE THREAD

**Issue by bircher** [drush-ops/drush#3270]
On my contrib development project I have drush master.

My drush alias (`dr`) is `./vendor/bin/drush --root="/var/www/html/web" ` since I call it from the project root. (and actually that inside a docker container)
When I now run `dr si standard -y` I get:
`[error]  Could not determine target sites directory for site to install. Use --sites-subdir to specify.`

So I run `dr si standard -y --sites-subdir=web` and now I get:
```
 // You are about to create a sites/web/settings.php file and create a sites/sites.php file and DROP all tables in your 
 // 'drupal' database. Do you want to continue?: yes.                                                                   

 [notice] Starting Drupal installation. This takes a while. Consider using the --notify global option.
 [success] Installation complete.  User name: admin  User password: VLoqXLhLLu
[22-Dec-2017 14:51:39 UTC] PHP Fatal error:  Uncaught Exception: notify-send command failed. Please install it as per http://coderstalk.blogspot.com/2010/02/how-to-install-notify-send-in-ubuntu.html. Or you may specify an alternate command to run by setting notify:cmd in a drush.yml file in /var/www/html/vendor/drush/drush/src/Commands/core/NotifyCommands.php:92
Stack trace:
#0 /var/www/html/vendor/drush/drush/src/Commands/core/NotifyCommands.php(55): Drush\Commands\core\NotifyCommands::shutdownSendText('Command 'site:i...', Object(Consolidation\AnnotatedCommand\CommandData))
#1 /var/www/html/vendor/drush/drush/src/Commands/core/NotifyCommands.php(39): Drush\Commands\core\NotifyCommands::shutdownSend('Command 'site:i...', Object(Consolidation\AnnotatedCommand\CommandData))
#2 [internal function]: Drush\Commands\core\NotifyCommands->shutdown(Object(Consolidation\AnnotatedCommand\CommandData))
#3 {main}
  thrown in /var/www/html/vendor/drush/drush/src/Commands/core/NotifyCommands.php on line 92
[22-Dec-2017 14:51:39 UTC] PHP Stack trace:
[22-Dec-2017 14:51:39 UTC] PHP   1. {main}() /var/www/html/vendor/drush/drush/drush:0
[22-Dec-2017 14:51:39 UTC] PHP   2. require() /var/www/html/vendor/drush/drush/drush:4

Fatal error: Uncaught Exception: notify-send command failed. Please install it as per http://coderstalk.blogspot.com/2010/02/how-to-install-notify-send-in-ubuntu.html. Or you may specify an alternate command to run by setting notify:cmd in a drush.yml file in /var/www/html/vendor/drush/drush/src/Commands/core/NotifyCommands.php on line 92

Call Stack:
    0.0002     359152   1. {main}() /var/www/html/vendor/drush/drush/drush:0
    0.0004     360080   2. require('/var/www/html/vendor/drush/drush/drush.php') /var/www/html/vendor/drush/drush/drush:4

Exception: notify-send command failed. Please install it as per http://coderstalk.blogspot.com/2010/02/how-to-install-notify-send-in-ubuntu.html. Or you may specify an alternate command to run by setting notify:cmd in a drush.yml file in /var/www/html/vendor/drush/drush/src/Commands/core/NotifyCommands.php on line 92

Call Stack:
    0.0002     359152   1. {main}() /var/www/html/vendor/drush/drush/drush:0
    0.0004     360080   2. require('/var/www/html/vendor/drush/drush/drush.php') /var/www/html/vendor/drush/drush/drush:4
   39.0614   35255416   3. Drush\Commands\core\NotifyCommands->shutdown() /var/www/html/vendor/drush/drush/src/Commands/core/NotifyCommands.php:0
   39.0616   35255480   4. Drush\Commands\core\NotifyCommands::shutdownSend() /var/www/html/vendor/drush/drush/src/Commands/core/NotifyCommands.php:39
   39.0616   35255480   5. Drush\Commands\core\NotifyCommands::shutdownSendText() /var/www/html/vendor/drush/drush/src/Commands/core/NotifyCommands.php:55

```

I guess both things would go away if I had some defaults in drush.yml for both. But I thought I report this regression as it used to work with the defaults before.

**Comment by weitzman** [comment]
First, its not too likely you need to specify --root anymore. Drush9 can find the project and drupal root when you call into `vendor/bin/drush`

Are you wanting a notification here or not? Its possible that we have changed the default to notify when it used to not do that. Also, can you check for any stray config files? Run `drush st` and look for the item `Drush configs`. Maybe one of them has defined notify.duration? You might have copied that from example.drush.yml.

**Comment by shobhitjuyal** [comment]
Hello @weitzman 

I have the same issue with Drush 9.2.1.. However not with all projects but with only one .. don't know why.

**Comment by christopher-hopper** [comment]
For others like @shobhitjuyal who come here to find answers, this may help.

**First**, as @weitzman says above

* check which Drush config files are being loaded using `drush status`

```
 Drush configs    : /home/vagrant/.drush/drush.yml
                    /var/www/vendor/drush/drush/drush.yml
                    /var/www/drush/drush.yml
```

**Next**, you will likely find that a `drush.yml` config file has a `notify:duration` value of `30`.

*  If you have run `drush init` lately it will add a `~/.drush/drush.yml` file with the following:

```yaml

notify:
  # Notify when command takes more than 30 seconds.
  duration: 30
  # Specify a command to run. Defaults to Notification Center (OSX) or libnotify (Linux)
# cmd: /path/to/program
  # See src/Commands/core/NotifyCommands.php for more configuration settings.
```

**Lastly**, if you don't want to install a `notify:cmd` program, just disable this feature. 

* On a guest Linux VM you may not care for the notify feature so set notify duration to zero.

Add the following lines to your home `~/.drush/drush.yml` or site `/var/www/drush/drush.yml` file:

```yaml

notify:
  # Disable use of notify to avoid 'Uncaught Exception: notify-send command failed.'
  # when running commands on headless guest VMs.
  duration: 0

```


Hope this helps someone else. I ran into this problem on a Vagrant DrupalVM box after executing `drush init` on the guest VM.

**Comment by jeffymahoney** [comment]
This doesn't work for me using Drush 9.3. Setting the notify duration to 0 had no effect.
