### ISSUE TITLE
When an update fails, updatedb is still exiting with 0

### ISSUE THREAD

**Issue by deviantintegral** [drush-ops/drush#3376]
This looks like a regression from #3095.

In attempting to run updates from a Drupal 8.4.4 install to 8.5.x using Drush 9.1.0, a fatal error is thrown, but drush still returned success. Note the last line with the exit code:

```
-------- ------------- --------------- --------------------------------------- 
  Module   Update ID     Type            Description                            
 -------- ------------- --------------- --------------------------------------- 
  system   8501          hook_update_n   Add the 'revision_default' field to    
                                         all relevant entity types.             
  views    8500          hook_update_n   Update field names for multi-value     
                                         base fields.                           
  system   change_acti   post-update     Change plugin IDs of actions.          
           on_plugins                                                           
  system   field_forma   post-update     Clear caches due to schema changes in  
           tter_entity                   core.entity.schema.yml.                
           _schema                                                              
  views    bulk_field_   post-update     Update dependencies for moved bulk     
           moved                         field plugin.                          
  views    entity_link   post-update     Add additional settings to the entity  
           _url                          link field and convert node_path       
                                         usage  to entity_link.                 
  views    filter_plac   post-update     Add placeholder settings to string or  
           eholder_tex                   numeric filters.                       
           t                                                                    
 -------- ------------- --------------- --------------------------------------- 

 // Do you wish to run the specified pending updates?: yes.                     

 [notice] Update started: system_update_8501
TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::reset() must be an instance of Doctrine\Common\Annotations\void, none returned in Doctrine\Common\Annotations\AnnotationRegistry::reset() (line 55 of /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php).
 [error]  TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::reset() must be an instance of Doctrine\Common\Annotations\void, none returned in Doctrine\Common\Annotations\AnnotationRegistry::reset() (line 55 of /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php) #0 /srv/bindings/221f215df214430b82daa4e29943f72b/code/web/core/lib/Drupal/Component/Annotation/Plugin/Discovery/AnnotatedClassDiscovery.php(113): Doctrine\Common\Annotations\AnnotationRegistry::reset()
#1 /srv/bindings/221f215df214430b82daa4e29943f72b/code/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php(106): Drupal\Component\Annotation\Plugin\Discovery\AnnotatedClassDiscovery->getDefinitions()
#2 /srv/bindings/221f215df214430b82daa4e29943f72b/code/web/core/lib/Drupal/Core/Plugin/DefaultPluginManager.php(175): Drupal\Core\Entity\EntityTypeManager->findDefinitions()
#3 /srv/bindings/221f215df214430b82daa4e29943f72b/code/web/core/modules/system/system.install(2079): Drupal\Core\Plugin\DefaultPluginManager->getDefinitions()
#4 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/src/Commands/core/UpdateDBCommands.php(185): system_update_8501(Array)
#5 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/includes/batch.inc(235): Drush\Commands\core\UpdateDBCommands->updateDoOne('system', 8501, Array, Object(DrushBatchContext))
#6 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/includes/batch.inc(183): _drush_batch_worker()
#7 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/includes/batch.inc(95): _drush_batch_command('2')
#8 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/src/Commands/core/UpdateDBCommands.php(142): drush_batch_command('2')
#9 [internal function]: Drush\Commands\core\UpdateDBCommands->process('2', Array)
#10 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)
#11 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#13 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#14 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/symfony/console/Command/Command.php(252): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\LessStrictArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/symfony/console/Application.php(964): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\LessStrictArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\LessStrictArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\LessStrictArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\Component\Console\Application->run(Object(Drush\Symfony\LessStrictArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\Runtime\Runtime->doRun(Array)
#20 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/drush.php(64): Drush\Runtime\Runtime->run(Array)
#21 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/drush(4): require('/srv/bindings/2...')
#22 {main}. 
 [error]  Drush command terminated abnormally due to an unrecoverable error. 
 [success] Finished performing updates.
 [notice] Command: test-85x.ci-9 -- drush updatedb [Exit: 0]
```

**Comment by pfrenssen** [comment]
Thanks for the report! It appears that our code that tries to detect if an update was executed successfully is not being executed because a fatal `TypeError` is being thrown. Up to now it seems we've only been testing this with exceptions. This will be quite easy to replicate in a test.

**Comment by pfrenssen** [comment]
Hmm I started on a test but `TypeErrors` are a PHP7 feature and we don't have any PHP7-specific tests yet. I will try if it can also be replicated with another fatal error.

**Comment by rbayliss** [comment]
I don't think this is limited to `TypeError` - it's anything that's not an `Exception`.  Eg: If I have the following code in an update hook:

```
function mymodule_update_8001() { 
  $foo->bar();
}
```
The error will be output (`Error: Call to a member function foo()...`), but the return code is still 0.  I can "fix" the problem by converting from catching `Exception` to `Throwable` [here](https://github.com/drush-ops/drush/blob/44daf5422d3f1cba04bdc36df22a16890c7ba8bd/src/Commands/core/UpdateDBCommands.php#L189), it behaves as you'd expect (RC 1, prints "Update failed: mass_utility_update_8026").  Of course `Throwable` isn't valid in PHP 5, so I'm not sure that's the way to go here.

**Comment by weitzman** [comment]
I'm interested in a PHP5 compatible fix, if anyone gets a chance to work on this.

**Comment by pfrenssen** [comment]
I think this will fix it for PHP 7 and is still compatible with PHP 5:

```
try {
  // ...
} catch (Throwable $t) {
  // This class doesn't exist in PHP 5 so this won't execute. It will catch the errors on PHP 7 though.
} catch (Exception $e) {
  // This will catch normal exceptions on both PHP 5 and PHP 7.
}
```

Regarding catching errors on PHP 5, as far as I know the only thing we can do is to register an error handler and a shutdown function that will then exit with an error code.

**Comment by weitzman** [comment]
FYI there are WIP tests related to this in #3386

**Comment by dpagini** [comment]
I'm running into this same issue. I'm not sure I understand the fix, however. Could anyone help me understand if I could post a proposed fix to reference as a patch, even if the tests are not available to merge the code in...?

**Comment by weitzman** [comment]
PR at #3673

**Comment by dpagini** [comment]
Thank you @weitzman!
