### ISSUE TITLE
Class 'Drupal\user\Entity\User' not found in Drush\User\User8->load_by_uid()

### ISSUE THREAD

**Issue by michaellenahan** [drush-ops/drush#3416]
Drush 8.1.15

Hi, I get the following issue using drush in Ubuntu VM on Mac (https://github.com/geerlingguy/drupal-vm)

```
vagrant@dkr:/var/www/drupalvm/dkr-web/docroot/sites/default$ drush
Error: Class 'Drupal\user\Entity\User' not found in Drush\User\User8->load_by_uid() (line 26 of                             [error]
/var/www/drupalvm/dkr-web/vendor/drush/drush/lib/Drush/User/User8.php) #0
/var/www/drupalvm/dkr-web/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php(558): Drush\User\User8->load_by_uid(0)
#1 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/bootstrap.inc(354): Drush\Boot\DrupalBoot->bootstrap_drupal_login()
#2 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/bootstrap.inc(509): drush_bootstrap(6, 7)
#3 /var/www/drupalvm/dkr-web/vendor/drush/drush/commands/core/help.drush.inc(103): drush_bootstrap_max()
#4 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/command.inc(422): drush_core_help()
#5 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#6 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/command.inc(199): drush_command()
#7 /var/www/drupalvm/dkr-web/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#8 /var/www/drupalvm/dkr-web/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#9 phar:///usr/local/bin/drush/bin/drush.php(150): drush_main()
#10 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#11 {main}.
```

I see the same problem was reported here with no reply in March 2016
https://github.com/drush-ops/drush/issues/2046

Grateful for any help.

**Comment by weitzman** [comment]
Lets stick with that 1 open issue.
