### ISSUE TITLE
Arch Linux MYSQL_ATTR_SSL_CA undefined

### ISSUE THREAD

**Issue by dmp1ce** [drush-ops/drush#3587]
I get the error below when running `drush` with no commands or options. If I add a `new PHP()` line above the location where MYSQL_ATTR_SSL_CA is referenced then the error does not occur. I'm not really sure what the fix is here but it looks like a bug with a newer version of `PHP` or `pdo_mysql` to me.

I'm running Arch Linux with the version 10.1.33 mariadb tools installed. Other versions for drush and PHP are below.

```
Drush Version   :  8.1.17
```
```
PHP 7.2.6 (cli) (built: May 26 2018 07:45:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.6, Copyright (c) 1999-2018, by Zend Technologies
```
```
simpledavid@delicateweb> ../vendor/bin/drush
Error: Undefined class constant 'MYSQL_ATTR_SSL_CA' in /home/david/Projects/xxxx/vendor/drush/drush/lib/Drush/Sql/Sqlmysql.php on line 57 #0 /home/david/Projects/xxxx/vendor/drush/drush/lib/Drush/Sql/SqlBase.php(165): Drush\Sql\Sqlmysql->creds()
#1 /home/david/Projects/xxxx/vendor/drush/drush/includes/environment.inc(393): Drush\Sql\SqlBase->query('SELECT 1;')
#2 /home/david/Projects/xxxx/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php(462): drush_valid_db_credentials()
#3 /home/david/Projects/xxxx/vendor/drush/drush/lib/Drush/Boot/DrupalBoot8.php(109): Drush\Boot\DrupalBoot->bootstrap_drupal_database_validate()
#4 /home/david/Projects/xxxx/vendor/drush/drush/includes/bootstrap.inc(430): 
Drush\Boot\DrupalBoot8->bootstrap_drupal_database_validate()
#5 /home/david/Projects/xxxx/vendor/drush/drush/includes/bootstrap.inc(507): drush_bootstrap_validate(4)
#6 /home/david/Projects/xxxx/vendor/drush/drush/commands/core/help.drush.inc(103): drush_bootstrap_max()
#7 /home/david/Projects/xxxx/vendor/drush/drush/includes/command.inc(422): drush_core_help()
#8 /home/david/Projects/xxxx/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#9 /home/david/Projects/xxxx/vendor/drush/drush/includes/command.inc(199): drush_command()
#10 /home/david/Projects/xxxx/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#11 /home/david/Projects/xxxx/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#12 /home/david/Projects/xxxx/vendor/drush/drush/drush.php(12): drush_main()
#13 {main}
Error: Undefined class constant &#039;MYSQL_ATTR_SSL_CA&#039; in Drush\Sql\Sqlmysql->creds() (line 57 of /home/david/Projects/xxxx/vendor/drush/drush/lib/Drush/Sql/Sqlmysql.php).
Drush command terminated abnormally due to an unrecoverable error.                                                                                                 [error]
```

**Comment by dmp1ce** [comment]
I'm pretty sure this was caused by a `~/drush/php.ini` I didn't realize I had. Closing.
