### ISSUE TITLE
Error: Class 'Drush\Sql\Sql' not found

### ISSUE THREAD

**Issue by prkos** [drush-ops/drush#3670]
I installed php 7.1 on my Ubuntu 14.04 and some related php extensions in order to install the latest D8. Composer seemed to have created the project correctly. 

Drush status is showing up: 

```sh
$ ../vendor/bin/drush status
 Drupal version : 8.5.6                                             
 Site URI       : default                                           
 PHP binary     : /usr/bin/php7.1                                   
 PHP config     : /etc/php/7.1/cli/php.ini                          
 PHP OS         : Linux                                             
 Drush script   : /var/www/html/testd8/vendor/bin/drush             
 Drush version  : 9.3.0                                             
 Drush temp     : /tmp                                              
 Drush configs  : /var/www/html/testd8/vendor/drush/drush/drush.yml 
                  /var/www/html/testd8/drush/drush.yml              
 Drupal root    : /var/www/html/testd8/web                          
 Site path      : sites/default           
```
But when I try to install the site I'm getting: 

```sh
$ ../vendor/bin/drush site-install standard --db-url=mysql://myname:mypass@localhost/mydb
Error: Class 'Drush\Sql\Sql' not found in /var/www/html/testd8/vendor/drush/drush/src/Sql/SqlBase.php on line 81 #0 /var/www/html/testd8/vendor/drush/drush/src/Sql/SqlBase.php(64): Drush\Sql\SqlBase::getInstance(Array, Array)
#1 /var/www/html/testd8/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(235): Drush\Sql\SqlBase::create(Array)
#2 /var/www/html/testd8/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php(43): Drush\Commands\core\SiteInstallCommands->validate(Object(Consolidation\AnnotatedCommand\CommandData))
#3 /var/www/html/testd8/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->callValidator(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /var/www/html/testd8/vendor/consolidation/annotated-command/src/CommandProcessor.php(167): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->validate(Object(Consolidation\AnnotatedCommand\CommandData))
#5 /var/www/html/testd8/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /var/www/html/testd8/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#7 /var/www/html/testd8/vendor/symfony/console/Command/Command.php(251): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/testd8/vendor/symfony/console/Application.php(964): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/testd8/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/testd8/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/testd8/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/testd8/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\Runtime\Runtime->doRun(Array)
#13 /var/www/html/testd8/vendor/drush/drush/drush.php(66): Drush\Runtime\Runtime->run(Array)
#14 /var/www/html/testd8/vendor/drush/drush/drush(4): require('/var/www/html/t...')
#15 {main}
Error: Class &#039;Drush\Sql\Sql&#039; not found in Drush\Sql\SqlBase::getInstance() (line 81 of /var/www/html/testd8/vendor/drush/drush/src/Sql/SqlBase.php).
 [error]  Drush command terminated abnormally due to an unrecoverable error. 

```
Visiting the site is just showing a blank page. The same with `/core/install.php`. 
My other sites seem to be working correctly (Apache 2). 

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.3.0
| Drupal version? | 8.5.6
| PHP version     | 7.1
| OS?             | Ubuntu 14.04

**Comment by weitzman** [comment]
Please use Drupal Answers for support questions.

**Comment by prkos** [comment]
Just in case someone else stumbles upon this; the issue was in mysql password containing special characters. 

[Error: Class 'Drush\Sql\Sql' not found](https://drupal.stackexchange.com/questions/263148/error-class-drush-sql-sql-not-found)
