### ISSUE TITLE
drush site-install failure: Undefined class constant 'MYSQL_ATTR_SSL_CA'

### ISSUE THREAD

**Issue by laurencefass** [drush-ops/drush#3817]
im trying a new alpine linux php-7 base image and i've hit the following problem trying to use site-install.

```
#3816 drush site-install social -y --notify --account-name=user1 --account-pass=vpsKundalin1 --db-url=mysql://user:pass@ip:3306/alpinesocial
Error: Undefined class constant 'MYSQL_ATTR_SSL_CA' in /root/.composer/vendor/drush/drush/src/Sql/SqlMysql.php on line 62 #0 /root/.composer/vendor/drush/drush/src/Sql/SqlBase.php(263): Drush\Sql\SqlMysql->creds()
#1 /root/.composer/vendor/drush/drush/src/Sql/SqlMysql.php(118): Drush\Sql\SqlBase->alwaysQuery('SELECT 1;', '/tmp/drush_nNfg...', '/dev/null')
#2 /root/.composer/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(316): Drush\Sql\SqlMysql->dbExists()
#3 /root/.composer/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php(43): Drush\Commands\core\SiteInstallCommands->pre(Object(Consolidation\AnnotatedCommand\CommandData))
#4 /root/.composer/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->callValidator(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /root/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(167): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->validate(Object(Consolidation\AnnotatedCommand\CommandData))
#6 /root/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#7 /root/.composer/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#8 /var/www/social/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/social/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/social/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/social/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /root/.composer/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /root/.composer/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\Runtime\Runtime->doRun(Array)
#14 /root/.composer/vendor/drush/drush/drush.php(66): Drush\Runtime\Runtime->run(Array)
#15 /root/.composer/vendor/drush/drush/drush(4): require('/root/.composer...')
#16 {main}
Error: Undefined class constant &#039;MYSQL_ATTR_SSL_CA&#039; in Drush\Sql\SqlMysql->creds() (line 62 of /root/.composer/vendor/drush/drush/src/Sql/SqlMysql.php).
 [error]  Drush command terminated abnormally due to an unrecoverable error.
```

php  7 extension list follows:

```
apk search php7
php7-intl-7.2.10-r0
php7-openssl-7.2.10-r0
php7-dba-7.2.10-r0
php7-sqlite3-7.2.10-r0
php7-pear-7.2.10-r0
php7-tokenizer-7.2.10-r0
php7-phpdbg-7.2.10-r0
cacti-php7-1.1.30-r0
xapian-bindings-php7-1.4.5-r0
php7-litespeed-7.2.10-r0
php7-gmp-7.2.10-r0
php7-pdo_mysql-7.2.10-r0
php7-sodium-7.2.10-r0
php7-pcntl-7.2.10-r0
php7-common-7.2.10-r0
php7-oauth-2.0.2-r3
php7-xsl-7.2.10-r0
php7-7.2.10-r0
php7-fpm-7.2.10-r0
php7-gmagick-2.0.5_rc1-r2
php7-imagick-3.4.3-r8
php7-mysqlnd-7.2.10-r0
php7-enchant-7.2.10-r0
php7-pspell-7.2.10-r0
php7-redis-4.0.2-r0
php7-snmp-7.2.10-r0
php7-doc-7.2.10-r0
php7-fileinfo-7.2.10-r0
php7-mbstring-7.2.10-r0
php7-dev-7.2.10-r0
php7-pear-mail_mime-1.10.0-r0
php7-xmlrpc-7.2.10-r0
php7-embed-7.2.10-r0
php7-xmlreader-7.2.10-r0
php7-pear-mdb2_driver_mysql-1.5.0b4-r0
php7-pdo_sqlite-7.2.10-r0
php7-pear-auth_sasl2-0.2.0-r0
php7-exif-7.2.10-r0
php7-recode-7.2.10-r0
php7-opcache-7.2.10-r0
php7-ldap-7.2.10-r0
php7-posix-7.2.10-r0
php7-pear-net_socket-1.1.0-r0
php7-session-7.2.10-r0
php7-gd-7.2.10-r0
php7-gettext-7.2.10-r0
php7-mailparse-3.0.2-r2
php7-json-7.2.10-r0
php7-xml-7.2.10-r0
php7-mongodb-1.4.4-r0
php7-iconv-7.2.10-r0
php7-sysvshm-7.2.10-r0
php7-curl-7.2.10-r0
php7-shmop-7.2.10-r0
php7-odbc-7.2.10-r0
php7-phar-7.2.10-r0
php7-pdo_pgsql-7.2.10-r0
php7-imap-7.2.10-r0
php7-pear-mdb2_driver_pgsql-1.5.0b4-r0
php7-pdo_dblib-7.2.10-r0
php7-pgsql-7.2.10-r0
php7-pdo_odbc-7.2.10-r0
php7-xdebug-2.6.1-r0
php7-zip-7.2.10-r0
php7-apache2-7.2.10-r0
php7-cgi-7.2.10-r0
php7-ctype-7.2.10-r0
php7-amqp-1.9.3-r1
php7-mcrypt-1.0.1-r0
php7-wddx-7.2.10-r0
php7-pear-net_smtp-1.8.0-r1
php7-bcmath-7.2.10-r0
php7-calendar-7.2.10-r0
php7-tidy-7.2.10-r0
php7-dom-7.2.10-r0
php7-sockets-7.2.10-r0
php7-zmq-1.1.3-r2
php7-event-2.4.1-r0
php7-memcached-3.0.4-r1
unit-php7-1.2-r0
php7-yaml-2.0.2-r1
php7-soap-7.2.10-r0
php7-apcu-5.1.11-r2
php7-sysvmsg-7.2.10-r0
php7-imagick-dev-3.4.3-r8
php7-ssh2-1.1.2-r2
php7-ftp-7.2.10-r0
php7-sysvsem-7.2.10-r0
php7-pear-net_idna2-0.2.0-r1
php7-pdo-7.2.10-r0
php7-pear-auth_sasl-1.1.0-r0
php7-bz2-7.2.10-r0
php7-mysqli-7.2.10-r0
php7-pear-net_smtp-doc-1.8.0-r1
php7-simplexml-7.2.10-r0
php7-xmlwriter-7.2.10-r0
```
any help appreciated. thanks.

**Comment by greg-1-anderson** [comment]
This sort of support request is better handled on Stack Exchange, where it will get more eyes.

**Comment by laurencefass** [comment]
thanks  problem solved...  missing php7-pdo_mysql.
