### ISSUE TITLE
drush.phar fails to run any command when one of them is provided as a phar file.

### ISSUE THREAD

**Issue by drzraf** [drush-ops/drush#3844]
**Describe the bug**
I bundle my command as a phar file suitable to `~/.drush` and named after the expected pattern, like `my-cmd.drush.inc`.
This works flawlessly when using drush 8 **from sources** but not when using drush .phar file.

**How To Reproduce**
Compile a command as a phar file and run it using Drush from https://github.com/drush-ops/drush/releases/download/8.1.18/drush.phar and run.

**Expected behavior**
Command succeeds

**Actual behavior**
**All** drush command fail with:
```
Command <FOO> needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.
The drush command '<FOO>' could not be executed.
Could not find a Drupal settings.php file at sites/foo/settings.php.
```

**Workaround**
Use drush from sources

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.1.18
| Drupal version? | 7.x
| PHP version     | 7.2
| OS?             | Linux

**Additional information**
I initially thought the `chdir` that phar format use would mess with finding `settings.php` but the fact that Drush from sources works seems to point somewhere else.

**Comment by greg-1-anderson** [comment]
Drush 8 is in maintenance only mode; I'm not sure if I will get to this sort of fix, but a PR would be welcome.

If you could get your file working as a CommandFile that works with Drush 9, I'd be up for fixing Drush 8 to use the same CommandFile. The rules for this is that you can only use the APIs of objects injected to your CommandFile class, or APIs available in Drupal.

**Comment by roygoldman** [comment]
I believe this is now a more critical issues with the 7.62 update. This results in drush writing an exception to console during most command (all that i have tried since doing the 7.62 update). The following trace is given.

based on my testing, it doesn't appear that this causes any execution issues with the commands being run, but I don't have time to investigate this further at the moment.

```
PHP Fatal error:  Uncaught TYPO3\PharStreamWrapper\Exception: Unexpected file extension in "phar:///usr/local/bin/drush/commands/core/outputformat" in /misc/typo3/drupal-security/PharExtensionInterceptor.php:39
Stack trace:
#0 /misc/typo3/phar-stream-wrapper/src/Behavior.php(72): Drupal\Core\Security\PharExtensionInterceptor->assert('phar:///usr/loc...', 'url_stat')
#1 /misc/typo3/phar-stream-wrapper/src/Manager.php(83): TYPO3\PharStreamWrapper\Behavior->assert('phar:///usr/loc...', 'url_stat')
#2 /misc/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(412): TYPO3\PharStreamWrapper\Manager->assert('phar:///usr/loc...', 'url_stat')
#3 /misc/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(401): TYPO3\PharStreamWrapper\PharStreamWrapper->assert('phar:///usr/loc...', 'url_stat')
#4 [internal function]: TYPO3\PharStreamWrapper\PharStreamWrapper->url_stat('phar:///usr/loc...', 2)
#5 phar:///usr/local/bin/drush/includes/engines.inc(87): file_exists('phar:///usr/loc...' in /misc/typo3/drupal-security/PharExtensionInterceptor.php on line 39, code: 255)
```

## Reproducing

To reproduce the above trace, you can simply update an existing 7.61 site to 7.62 using `drush up`. I believe the command successfully updates the site's code, and the exception is triggered during the database update portion of the command. I was also able to reproduce it running `drush cc all` and `drush ard` on the 7.52 site following the update. The backups were successfully created and appeared to have , but I haven't been able to attempt a full restore to guarantee that it worked successfully.

**Comment by weitzman** [comment]
This issue is unrelated to the errors you are seeing. Please follow https://www.drupal.org/project/drupal/issues/3026386. Drupal is issueing a hotfix release tonight to fix today's security releases.

**Comment by greg-1-anderson** [comment]
I just re-read the original post. I think I missed the fact that the reason that the commandfile in question is not working with drush.phar is that the commandfile itself is being bundled as a phar.

I am not particularly interested in supporting this. It seems unnecessary to bundle an extension as a phar. If you'd like to make your own stand-alone phar, see https://github.com/g1a/starter

**Comment by arch1v1st** [comment]
This is what finally fixed it for me, running Drush 8 / Drupal 7.64 / PHP 7.2:
```
# wget https://github.com/drush-ops/drush/releases/download/8.1.18/drush.phar
# chmod +x drush.phar
# sudo mv drush.phar /usr/local/bin/drush
# ln -s /usr/local/bin/drush.phar /usr/local/bin/drush
# cd ~
# drush cc drush
```

**Comment by greg-1-anderson** [comment]
^^ is unrelated to this issue, but very helpful. Thank you.

**Comment by drzraf** [comment]
@greg-1-anderson do you know the underlying reason for the strange failure OP?
Why loading a command bundled in a phar file would work using Git sources but not` drush.phar`?

**Comment by greg-1-anderson** [comment]
I suspect that it is a php limitation; however, I am not interested in supporting this, so I did not investigate the cause.

**Comment by dustinsilva** [comment]
> This is what finally fixed the TYPO3 errors for me, running Drush 8 / Drupal 7.64 / PHP 7.2:
> 
> ```
> # wget https://github.com/drush-ops/drush/releases/download/8.1.18/drush.phar
> # chmod +x drush.phar
> # sudo mv drush.phar /usr/local/bin/drush/drush.phar
> # ln -s /usr/local/bin/drush.phar /usr/local/bin/drush
> # cd ~
> # drush cc drush
> ```

I'm either missing something, or there is a typo with the third command "sudo mv drush.phar /usr/local/bin/drush/drush.phar" ----is the dir "drush" supposed to be in the path /usr/local/bin/"drush"/drush.phar ???

**Comment by greg-1-anderson** [comment]
@dustinsilva No, not a typo. The idea, and in fact the main intent of the example is to rename `drush.phar` to `drush`. That avoids triggering the checks that were causing the problems with the Drush .phar in Drupal 7.64.

**Comment by dustinsilva** [comment]
but if I copy and paste each command as you have it, the third command fails as the directory "/usr/local/bin/drush" does not exist and as a result, drush.phar cannot be moved.

**Comment by paul-m** [comment]
For future travelers to this place:
```
curl -L https://github.com/drush-ops/drush/releases/download/8.2.3/drush.phar > drush.phar
chmod +x drush.phar
mkdir /usr/local/bin/drushphar
mv drush.phar /usr/local/bin/drushphar/drush.phar
ln -s /usr/local/bin/drushphar/drush.phar /usr/local/bin/drush
```

**Comment by andrewg211** [comment]
> This is what finally fixed the TYPO3 errors for me, running Drush 8 / Drupal 7.64 / PHP 7.2:
> 
> ```
> # wget https://github.com/drush-ops/drush/releases/download/8.1.18/drush.phar
> # chmod +x drush.phar
> # sudo mv drush.phar /usr/local/bin/drush/drush.phar
> # ln -s /usr/local/bin/drush.phar /usr/local/bin/drush
> # cd ~
> # drush cc drush
> ```

Please double check your paths before posting.

Thanks
