### ISSUE TITLE
Unable to change role using drush

### ISSUE THREAD

**Issue by solomon123** [drush-ops/drush#4077]
When I run the following drush command, found this error. my drush works fine except this user-add-role command.
$ drush urol "Administrator" 4, --mail=mymail@gmail.com
Drush\Role\RoleException: Could not find the role: Administrator in           [error]                                                         /Applications/MAMP/htdocs/drupal/vendor/drush/drush/lib/Drush/Role/RoleBase.php:46
Stack trace:
#0 [internal function]: Drush\Role\RoleBase->__construct('Content Manager')
#1 /Applications/MAMP/htdocs/drupal/vendor/drush/drush/includes/drush.inc(117): ReflectionClass->newInstanceArgs(Array)
#2 /Applications/MAMP/htdocs/drupal/vendor/drush/drush/commands/core/role.drush.inc(274): drush_get_class('Drush\\Role\\Role', Array)
#3 /Applications/MAMP/htdocs/drupal/vendor/drush/drush/commands/user/user.drush.inc(282): drush_role_get_class('Content Manager')
#4 /Applications/MAMP/htdocs/drupal/vendor/drush/drush/includes/command.inc(422): drush_user_add_role('Content Manager')
#5 /Applications/MAMP/htdocs/drupal/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#6 /Applications/MAMP/htdocs/drupal/vendor/drush/drush/includes/command.inc(199): drush_command('Content Manager')
#7 /Applications/MAMP/htdocs/drupal/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#8 /Applications/MAMP/htdocs/drupal/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#9 /Applications/MAMP/htdocs/drupal/vendor/drush/drush/drush.php(12): drush_main()
#10 {main}

$ drush rls 
this works fine, and list all the roles in my site.
I'm using Drush version: 8.1.18

I'm working on Drupal 8.7.1
I tried to use different roles the same error is showing. Other than this my drush works properly.
Thanks :)

**Comment by solomon123** [comment]
Got it:- Syntax error. It should be as: 
$ drush urol administrator mymail@gmail.com

to remove role:
$ drush urrol role_machine_name myemail@gmail.com
