### ISSUE TITLE
Fatal Error due to Robo on fresh install

### ISSUE THREAD

**Issue by webmasterpf** [drush-ops/drush#4218]
**Describe the bug**
Unable to run drush status command to test if installation works.

**To Reproduce**
Install D8.7.7 with composer (not the drupal project), install drush:
```
composer require drupal/core:8.7.7
composer  require drush/drush:9.7
```
**Expected behavior**
What did you expect would happen?

**Actual behavior**
```
[preflight] Commandfile search paths: /home/xxx/www/le_rocher/sited8/vendor/drush/drush/src
Fatal error: Uncaught TypeError: Argument 3 passed to Robo\Robo::configureContainer() must be an instance of Robo\Config\Config, instance of Drush\Config\DrushConfig given, called in /home/xxx/www/le_rocher/sited8/vendor/drush/drush/src/Runtime/DependencyInjection.php on line 55 and defined in /home/xxx/www/le_rocher/sited8/vendor/consolidation/robo/src/Robo.php:177
Stack trace:
#0 /home/xxx/www/le_rocher/sited8/vendor/drush/drush/src/Runtime/DependencyInjection.php(55): Robo\Robo::configureContainer(Object(League\Container\Container), Object(Drush\Application), Object(Drush\Config\DrushConfig), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /home/xxx/www/le_rocher/sited8/vendor/drush/drush/src/Runtime/Runtime.php(92): Drush\Runtime\DependencyInjection->initContainer(Object(Drush\Application), Object(Drush\Config\DrushConfig), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Conso in /home/xxx/www/le_rocher/sited8/vendor/consolidation/robo/src/Robo.php on line 177
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7
| Drupal version? | 8.7.7
| PHP version     | 7.2
| OS?             | /Linux/

**Comment by webmasterpf** [comment]
in addition, I get a weird thing if I check for updates:
`drupal/core                    8.7.7           9.0.x-dev 1207ca6`

on another website it's different:
`drupal/core                    8.7.7 8.7.8`

do a setting in composer.json maybe the problem ?

**Comment by webmasterpf** [comment]
further information about robo files:

```
 find  /home/xxx/www/site1/sited8/vendor/  -name '*robo*'
/home/xxx/www/site1/sited8/vendor/bin/robo
/home/xxx/www/site1/sited8/vendor/consolidation/robo
/home/xxx/www/site1/sited8/vendor/consolidation/robo/examples/robo.script
/home/xxx/www/site1/sited8/vendor/consolidation/robo/robo
/home/xxx/www/site1/sited8/vendor/consolidation/robo/tests/_data/claypit/box/robo.txt
/home/xxx/www/site1/sited8/vendor/consolidation/robo/tests/_data/robo.yml
/home/xxx/www/site1/sited8/vendor/consolidation/robo/tests/_data/robo2.yml
$ find  /home/xxx/www/site2/sited8/vendor/  -name '*robo*'
/home/xxx/www/site2/sited8/vendor/bin/robo
/home/xxx/www/site2/sited8/vendor/consolidation/robo
/home/xxx/www/site2/sited8/vendor/consolidation/robo/robo
/home/xxx/www/site2/sited8/vendor/consolidation/robo/robo.yml
```

Drush work on site2, not on site1...probably because of difference between robo files... how can I reinstall them ?

**Comment by webmasterpf** [comment]
After modifying my composer.json file with:
```
"prefer-stable": true,
"minimum-stability": "dev",
```
and:
```
"drupal/core": "^8.7",
"drush/drush": "^9.7",
```
run composer install and all come back as designed (example):
`Updating consolidation/robo (dev-state ed9cdb8 => 1.4.10):  Checking out e5a6ca64cf`

and drush status work :) The initial install of Drush 10 and dev, was a bad idea in my case.

**Comment by greg-1-anderson** [comment]
What version of Robo was installed in the non-working scenario?

**Comment by webmasterpf** [comment]
I don't know. How can I know that ?

**Comment by greg-1-anderson** [comment]
composer info consolidation/robo

**Comment by webmasterpf** [comment]
Actually it's:
```
$ composer info consolidation/robo
name     : consolidation/robo
descrip. : Modern task runner
keywords :
versions : * 1.4.10
type     : library
```
with drush 9, previously it was perhaps, another version with drush 10 dev.
