### ISSUE TITLE
10.0.0-rc4 installer throws an error

### ISSUE THREAD

**Issue by nerdstein** [drush-ops/drush#4234]
**Describe the bug**

**To Reproduce**
1. Clone Drupal 9.0.x-dev
2. Load Drush 10.0.0-rc4
3. Run the following site install command/parameters:
`drush -r "${DOCROOT}" si standard --account-name=admin --account-pass=admin -y`

**Expected behavior**
I expected the Drush install command to install Drupal.

**Actual behavior**
It exited and did not install. It threw the following error:
```
TypeError: Argument 1 passed to Drush\SiteAlias\ProcessManager::configureProcess() must be an instance of Consolidation\SiteProcess\ProcessBase, instance of Symfony\Component\Process\Process given, called in /root/.composer/vendor/drush/drush/src/SiteAlias/ProcessManager.php on line 143 in /root/.composer/vendor/drush/drush/src/SiteAlias/ProcessManager.php on line 149 #0 /root/.composer/vendor/drush/drush/src/SiteAlias/ProcessManager.php(143): Drush\SiteAlias\ProcessManager::configureProcess(Object(Symfony\Component\Process\Process))
#1 /root/.composer/vendor/drush/drush/src/Drush.php(405): Drush\SiteAlias\ProcessManager->shell('command -v mysq...', NULL, NULL, NULL, 60)
#2 /root/.composer/vendor/drush/drush/src/Exec/ExecTrait.php(93): Drush\Drush::shell('command -v mysq...')
#3 /root/.composer/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(341): Drush\Commands\core\SiteInstallCommands::programExists('mysql')
#4 /root/.composer/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php(43): Drush\Commands\core\SiteInstallCommands->pre(Object(Consolidation\AnnotatedCommand\CommandData))
#5 /root/.composer/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->callValidator(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /root/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(195): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->validate(Object(Consolidation\AnnotatedCommand\CommandData))
#7 /root/.composer/vendor/consolidation/annotated-command/src/CommandProcessor.php(178): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#8 /root/.composer/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#9 /var/www/html.original/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html.original/vendor/symfony/console/Application.php(976): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html.original/vendor/symfony/console/Application.php(276): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html.original/vendor/symfony/console/Application.php(152): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /root/.composer/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /root/.composer/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /root/.composer/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#16 /root/.composer/vendor/drush/drush/drush(4): require('/root/.composer...')
#17 {main}
TypeError: Argument 1 passed to Drush\SiteAlias\ProcessManager::configureProcess() must be an instance of Consolidation\SiteProcess\ProcessBase, instance of Symfony\Component\Process\Process given, called in /root/.composer/vendor/drush/drush/src/SiteAlias/ProcessManager.php on line 143 in Drush\SiteAlias\ProcessManager::configureProcess() (line 149 of /root/.composer/vendor/drush/drush/src/SiteAlias/ProcessManager.php).
```

**Workaround**
None that I have found yet

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.0.0-rc4
| Drupal version? | 9.0.x-dev
| PHP version     | 7.2
| OS?             | Linux

**Additional information**
This is running on Simplytest.me with the new TugboatQA backend.

**Comment by weitzman** [comment]
Thanks for trying the new RC  

Drush must be installed as a dependency of your composer built site. It's unsupported as a global program for quite a while now. A global program to consider is drush launcher, and that hands of to the drush that's in your project. 

See drush install instructions for more info.

**Comment by nerdstein** [comment]
Thanks for the prompt reply
