### ISSUE TITLE
Fatal Error when trying to drush uli into a remote site using an alias

### ISSUE THREAD

**Issue by Boegie** [drush-ops/drush#4317]
**Describe the bug**

Tried to drush uli into a platform.sh hosted site with correct site-alias setup.
Drush 10.2.1 seems to currently be missing the function `drush_has_bash()`

**To Reproduce**
What did you do?
`drush @site-aliases.emergency-planning.dev uli`

**Expected behavior**
What did you expect would happen?

**Actual behavior**
What happened instead?

Fatal Error was thrown:

```
PHP Fatal error:  Uncaught Error: Call to undefined function Drush\Exec\drush_has_bash() in D:\htdocs\emergency-planning\vendor\drush\drush\src\Exec\ExecTrait.php:59
Stack trace:
#0 D:\htdocs\emergency-planning\vendor\drush\drush\src\Commands\core\LoginCommands.php(91): Drush\Commands\core\LoginCommands->startBrowser('https://www---d...', false, NULL, true)
#1 [internal function]: Drush\Commands\core\LoginCommands->login('', Array)
#2 D:\htdocs\emergency-planning\vendor\consolidation\annotated-command\src\CommandProcessor.php(257): call_user_func_array(Array, Array)
#3 D:\htdocs\emergency-planning\vendor\consolidation\annotated-command\src\CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 D:\htdocs\emergency-planning\vendor\consolidation\annotated-command\src\CommandProcessor.php(178): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5  in D:\htdocs\emergency-planning\vendor\drush\drush\src\Exec\ExecTrait.php on line 59

Fatal error: Uncaught Error: Call to undefined function Drush\Exec\drush_has_bash() in D:\htdocs\emergency-planning\vendor\drush\drush\src\Exec\ExecTrait.php on line 59

Error: Call to undefined function Drush\Exec\drush_has_bash() in D:\htdocs\emergency-planning\vendor\drush\drush\src\Exec\ExecTrait.php on line 59

Call Stack:
    0.2050     403072   1. {main}() D:\htdocs\emergency-planning\vendor\drush\drush\drush:0
    0.2057     415752   2. require('D:\htdocs\emergency-planning\vendor\drush\drush\drush.php') D:\htdocs\emergency-planning\vendor\drush\drush\drush:4
    0.2438    2693600   3. Drush\Runtime\Runtime->run() D:\htdocs\emergency-planning\vendor\drush\drush\drush.php:72
    0.2448    2715600   4. Drush\Runtime\Runtime->doRun() D:\htdocs\emergency-planning\vendor\drush\drush\src\Runtime\Runtime.php:49
    0.6990   10069440   5. Drush\Application->run() D:\htdocs\emergency-planning\vendor\drush\drush\src\Runtime\Runtime.php:118
    0.7737   10070328   6. Drush\Application->doRun() D:\htdocs\emergency-planning\vendor\symfony\console\Application.php:148
    0.7746   10070784   7. Drush\Application->doRunCommand() D:\htdocs\emergency-planning\vendor\symfony\console\Application.php:255

 [warning] Drush command terminated abnormally.
```

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.1
| Drupal version? | 8.8.2 
| PHP version     | PHP 7.2.24 (cli) (built: Oct 22 2019 11:18:58) ( ZTS MSVC15 (Visual C++ 2017) x64 )
| OS?             | Windows 10

**Additional information**

**Comment by Boegie** [comment]
Thanks for the quick fix
