### ISSUE TITLE
ConfigCommands' does not have a method 'setExportStorage'

### ISSUE THREAD

**Issue by mikemadison13** [drush-ops/drush#4327]
**Describe the bug**
I attempted to run a `drush en google_analytics` and got a pretty significant failure:

```
 [warning] call_user_func_array() expects parameter 1 to be a valid callback, class 'Drush\Drupal\Commands\config\ConfigCommands' does not have a method 'setExportStorage' Container.php:329
 [warning] call_user_func_array() expects parameter 1 to be a valid callback, class 'Drush\Drupal\Commands\config\ConfigExportCommands' does not have a method 'setExportStorage' Container.php:329
 [error]  TypeError: Argument 4 passed to Drush\Drupal\Commands\config\ConfigImportCommands::__construct() must implement interface Drupal\Core\Extension\ModuleHandlerInterface, instance of Drupal\Core\Cache\ChainedFastBackend given in Drush\Drupal\Commands\config\ConfigImportCommands->__construct() (line 135 of /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php) #0 [internal function]: Drush\Drupal\Commands\config\ConfigImportCommands->__construct(Object(Drupal\Core\Config\ConfigManager), Object(Drupal\Core\Config\CachedStorage), Object(Drupal\config_filter\Config\FilteredStorage), Object(Drupal\Core\Cache\ChainedFastBackend), Object(Drupal\Core\Extension\ModuleHandler), Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher), Object(Drupal\Core\ProxyClass\Lock\DatabaseLockBackend), Object(Drupal\Core\Config\TypedConfigManager), Object(Drupal\Core\ProxyClass\Extension\ModuleInstaller), Object(Drupal\Core\Extension\ThemeHandler), Object(Drupal\Core\StringTranslation\TranslationManager))
#1 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(310): ReflectionClass->newInstanceArgs(Array)
#2 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\Container->createService(Array, 'config.import.c...')
#3 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(487): Drupal\Component\DependencyInjection\Container->get('config.import.c...', 1)
#4 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(326): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#5 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\Container->createService(Array, 'drush.command.s...')
#6 /app/vendor/drush/drush/src/Boot/DrupalBoot8.php(277): Drupal\Component\DependencyInjection\Container->get('drush.command.s...')
#7 /app/vendor/drush/drush/src/Boot/DrupalBoot8.php(243): Drush\Boot\DrupalBoot8->addDrupalModuleDrushCommands(Object(Drush\Boot\BootstrapManager))
#8 /app/vendor/drush/drush/src/Boot/BootstrapManager.php(293): Drush\Boot\DrupalBoot8->bootstrapDrupalFull(Object(Drush\Boot\BootstrapManager), NULL)
#9 /app/vendor/drush/drush/src/Boot/BootstrapManager.php(493): Drush\Boot\BootstrapManager->doBootstrap(5, 6, NULL)
#10 /app/vendor/drush/drush/src/Application.php(225): Drush\Boot\BootstrapManager->bootstrapMax()
#11 /app/vendor/drush/drush/src/Application.php(192): Drush\Application->bootstrapAndFind('pm:enable')
#12 /app/vendor/symfony/console/Application.php(236): Drush\Application->find('pm:enable')
#13 /app/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /app/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /app/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#17 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#18 {main}. 
```

**To Reproduce**
I ran a composer command `composer require drupal/google_analytics` to install the most current version of the module then attempted to enable it.

**Expected behavior**
The module would enable

**Actual behavior**
See above error.

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.2 -- note I am blocked from updating to 10.x due to https://github.com/drush-ops/drush/issues/4323
| Drupal version? | 8.8.2
| PHP version     | 7.3
| OS?             | Linux VM

**Additional Information**
I found no evidence of this issue, and even if it's "fixed" by updating to 10.x I wanted to document it for 9.7.x so there was a record for other folks.

**Comment by mikemadison13** [comment]
just realized this is because I installed a site with drush 10 and then downgraded to 9.x. My apologies!

**Comment by carsonblack** [comment]
Can confirm that I took the same action as @mikemadison13, installing drush 10 then trying to downgrade to drush 9, and ended up with the same error message. So reinstall the site (I'm using Docksal) with drush 9 in place and it works again.
