### ISSUE TITLE
Site install fails with Umami as argument with exit status 1

### ISSUE THREAD

**Issue by rpkoller** [drush-ops/drush#4420]
**Describe the bug**
When I try to perform a drush site install the process fails with `umami` as argument but works flawlessly with `standard` or `minimal` as argument instead

**To Reproduce**
I am using DDEV. The following steps I've applied: 

1. `mkdir ~/Sites/d9umami && cd ~/Sites/d9umami`
2. `git clone https://git.drupalcode.org/project/drupal.git .`
3. `ddev config --mariadb-version=10.3` 
4. `git checkout 9.1.x`
5. `ddev composer install`
6. `ddev composer require --dev drush/drush`
7. `ddev . drush si umami --account-name=myuser --account-pass=mypw --account-mail=mymail@mail.com --site-name=UmamiTest`

**Expected behavior**
I would have expected that the site is installed like it works with the argument `standard` or `minimal`

**Actual behavior**
The actual output after dropping all database tables: 

```
$> ddev . drush si umami --account-name=myuser --account-pass=mypw --account-mail=mymail@mail.com --site-name=UmamiTest'

 You are about to DROP all tables in your 'db' database. Do you want to continue? (yes/no) [yes]:
 >
 [notice] Starting Drupal installation. This takes a while.
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
 [warning] strpos(): Empty needle ExtensionDiscovery.php:283
 [warning] The following profile is missing from the file system: umami bootstrap.inc:181
Error: Call to a member function getPath() on null in /var/www/html/core/includes/install.core.inc on line 847 #0 /var/www/html/core/includes/install.core.inc(712): install_tasks(Array)
#1 /var/www/html/core/includes/install.core.inc(561): install_tasks_to_perform(Array)
#2 /var/www/html/core/includes/install.core.inc(118): install_run_tasks(Array, NULL)
#3 /var/www/html/vendor/drush/drush/includes/drush.inc(212): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#4 /var/www/html/vendor/drush/drush/includes/drush.inc(197): drush_call_user_func_array('install_drupal', Array)
#5 /var/www/html/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(150): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#6 [internal function]: Drush\Commands\core\SiteInstallCommands->install('umami', Array)
#7 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#8 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#9 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#10 /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 /var/www/html/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/symfony/console/Application.php(1019): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#18 /var/www/html/vendor/drush/drush/includes/preflight.inc(18): require('/var/www/html/v...')
#19 phar:///usr/local/bin/drush/bin/drush.php(141): drush_main()
#20 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#21 {main}
Error: Call to a member function getPath() on null in install_tasks() (line 847 of /var/www/html/core/includes/install.core.inc).
 [warning] Drush command terminated abnormally.
Failed to execute command drush si umami --account-name=myuser --account-pass=mypw --account-mail=mymail@mail.com --site-name=UmamiTest: exit status 1
```
### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.2
| Drupal version? | 9.1.x
| PHP version     | 7.3
| OS?             | Mac (10.13.6) + ddev version v1.14.2

**Comment by rpkoller** [comment]
uhhhh i've learned today that the name how to call the install profile isn't `umami` but `demo_umami`... retried the described steps from above and it worked flawlessly:

`ddev . drush si demo_umami --account-name=myuser --account-pass=mypw --account-mail=mymail@mail.com --site-name=UmamiTest`

closing this since things work as expected. sorry for the false alarm.

**Comment by greg-1-anderson** [comment]
` [warning] The following profile is missing from the file system: umami bootstrap.inc:181`

Perhaps this should be a fatal.

**Comment by weitzman** [comment]
Drush doesn't currently validate the profile's existence. The warning is coming from drupal.

**Comment by greg-1-anderson** [comment]
Maybe something to consider in the future, then.
