### ISSUE TITLE
`drush uli` fails with ugly error  if database dropped (both drush 10.3.1 and 8.3.5)

### ISSUE THREAD

**Issue by rfay** [drush-ops/drush#4459]
**Describe the bug**

If you drop the database or it doesn't exist yet, `drush uli` gives you a major stack trace instead of "I can't do that right now, Dave"

This is the same on Drupal 8 and Drupal 9, I'll only give examples on Drupal 9.

This happens with different results on both drush 10.3.1 and 8.3.5 

**To Reproduce**

On drush 10.3.1, Drupal 9:

```
$ vendor/bin/drush --version
Drush Commandline Tool 10.3.1

$ vendor/bin/drush uli
https://d9.ddev.site/user/reset/1/1594315796/6EJX2TFtlYQ74Hu_hQaffp52MITwz8vKwREqB5IvnEQ/login

$ vendor/bin/drush sql-drop -y

 // Do you really want to drop all tables in the database db?: yes.

$ vendor/bin/drush uli
PHP Fatal error:  Trait 'Drupal\system\ModuleDependencyMessageTrait' not found in /var/www/html/core/lib/Drupal/Core/Extension/ThemeInstaller.php on line 23

Fatal error: Trait 'Drupal\system\ModuleDependencyMessageTrait' not found in /var/www/html/core/lib/Drupal/Core/Extension/ThemeInstaller.php on line 23
 [warning] Drush command terminated abnormally.
```

=====================================================
On Drush 8.3.5, Drupal 9 it's a lot more intimidating:

```
$ drush8 --version
 Drush Version   :  8.3.5

$ drush8 uli
https://d9.ddev.site/user/reset/1/1594314691/YGg1cG2n7Z8O4S7dFHfOSwHcDv0mGX84ClL4Spdlg90/login

$ drush8 sql-drop -y
Do you really want to drop all tables in the database db? (y/n): y

$ drush8 uli
Error: Class 'Drupal\user\Entity\User' not found in                          [error]
Drush\User\User8->load_by_uid() (line 26 of
phar:///usr/local/bin/drush8/vendor/composer/../../lib/Drush/User/User8.php)
#0
phar:///usr/local/bin/drush8/vendor/composer/../../lib/Drush/User/UserList.php(103):
Drush\User\User8->load_by_uid('1')
#1
phar:///usr/local/bin/drush8/vendor/composer/../../lib/Drush/User/UserList.php(15):
Drush\User\UserList::getFromParameters(Array)
#2 phar:///usr/local/bin/drush8/commands/user/user.drush.inc(409):
Drush\User\UserList->__construct(1)
#3 phar:///usr/local/bin/drush8/includes/command.inc(422): drush_user_login()
#4 phar:///usr/local/bin/drush8/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#5 phar:///usr/local/bin/drush8/includes/command.inc(199): drush_command()
#6 phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#7 phar:///usr/local/bin/drush8/includes/preflight.inc(67):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 phar:///usr/local/bin/drush8/includes/startup.inc(465): drush_main()
#9 phar:///usr/local/bin/drush8/includes/startup.inc(369):
drush_run_main(false, '/', 'Phar detected. ...')
#10 phar:///usr/local/bin/drush8/drush(114): drush_startup(Array)
#11 /usr/local/bin/drush8(10): require('phar:///usr/loc...')
#12 {main}.
Error: Class 'Drupal\user\Entity\User' not found in phar:///usr/local/bin/drush8/vendor/composer/../../lib/Drush/User/User8.php on line 26 #0 phar:///usr/local/bin/drush8/vendor/composer/../../lib/Drush/User/UserList.php(103): Drush\User\User8->load_by_uid('1')
#1 phar:///usr/local/bin/drush8/vendor/composer/../../lib/Drush/User/UserList.php(15): Drush\User\UserList::getFromParameters(Array)
#2 phar:///usr/local/bin/drush8/commands/user/user.drush.inc(409): Drush\User\UserList->__construct(1)
#3 phar:///usr/local/bin/drush8/includes/command.inc(422): drush_user_login()
#4 phar:///usr/local/bin/drush8/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#5 phar:///usr/local/bin/drush8/includes/command.inc(199): drush_command()
#6 phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#7 phar:///usr/local/bin/drush8/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 phar:///usr/local/bin/drush8/includes/startup.inc(465): drush_main()
#9 phar:///usr/local/bin/drush8/includes/startup.inc(369): drush_run_main(false, '/', 'Phar detected. ...')
#10 phar:///usr/local/bin/drush8/drush(114): drush_startup(Array)
#11 /usr/local/bin/drush8(10): require('phar:///usr/loc...')
#12 {main}
Error: Class &#039;Drupal\user\Entity\User&#039; not found in Drush\User\User8->load_by_uid() (line 26 of phar:///usr/local/bin/drush8/vendor/composer/../../lib/Drush/User/User8.php).
Drush command terminated abnormally due to an unrecoverable error.           [error]
```

**Expected behavior**

Probably "Sorry, I can't do that Dave"

**Actual behavior**

Above.

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.1, 8.3.5
| Drupal version? | 9.0.1
| PHP version     | 7.3
| OS?             | Linux

**Comment by weitzman** [comment]
Well, Drush just throws an Exception. The stack trace is your PHP/Xdebug settings.

**Comment by rfay** [comment]
Side-note and unrelated, but could you school me on what settings would affect the stack trace? I don't have xdebug enabled in either situation, double-checked with `php -i` just now.

**Comment by weitzman** [comment]
I'm not sure to be honest. I think more recent drupal may have an error setting for stack trace as well.
