### ISSUE TITLE
drush cr doesn't handle a module being moved

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#4661]
**Describe the bug**

It used to be possible to move a module's folder, then do `drush cr` and everything would work fine.

This is no longer the case: `drush cr` crashes:

```
$ drush cr --debug
Using the Drush script found at /Users/joachim/Sites/dcb-repos/vendor/drush/drush/drush using proc_open
 [preflight] Config paths: /Users/joachim/Sites/dcb-repos/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /Users/joachim/Sites/dcb-repos/web/drush/sites,/Users/joachim/Sites/dcb-repos/drush/sites
 [preflight] Commandfile search paths: /Users/joachim/Sites/dcb-repos/vendor/drush/drush/src
 [debug] Starting bootstrap to site [0.15 sec, 8.51 MB]
 [debug] Drush bootstrap phase 2 [0.15 sec, 8.52 MB]
 [debug] Try to validate bootstrap phase 2 [0.15 sec, 8.52 MB]
 [debug] Try to validate bootstrap phase 2 [0.15 sec, 8.52 MB]
 [debug] Try to bootstrap at phase 2 [0.15 sec, 8.52 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalRoot() [0.15 sec, 8.52 MB]
 [debug] Change working directory to /Users/joachim/Sites/dcb-repos/web [0.15 sec, 8.52 MB]
 [debug] Initialized Drupal 8.9.5 root directory at /Users/joachim/Sites/dcb-repos/web [0.15 sec, 8.71 MB]
 [debug] Try to validate bootstrap phase 2 [0.15 sec, 8.71 MB]
 [debug] Try to bootstrap at phase 2 [0.16 sec, 9 MB]
 [debug] Drush bootstrap phase: bootstrapDrupalSite() [0.16 sec, 9 MB]
 [debug] Initialized Drupal site default at sites/default [0.16 sec, 9.18 MB]

Fatal error: Uncaught AssertionError: The file specified by the given app root, relative path and file name (/Users/joachim/Sites/dcb-repos/web/modules/custom/module_builder/module_builder.info.yml) do not exist. in /Users/joachim/Sites/dcb-repos/web/core/lib/Drupal/Core/Extension/Extension.php:67
Stack trace:
#0 /Users/joachim/Sites/dcb-repos/web/core/lib/Drupal/Core/Extension/Extension.php(67): assert(false, 'The file specif...')
#1 /Users/joachim/Sites/dcb-repos/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(114): Drupal\Core\Extension\Extension->__construct('/Users/joachim/...', 'module', 'modules/custom/...', 'module_builder....')
#2 /Users/joachim/Sites/dcb-repos/web/core/lib/Drupal/Component/DependencyInjection/Container.php(259): Drupal\Core\Extension\ModuleHandler->__construct('/Users/joachim/...', Array, Object(Drupal\Core\Cache\DatabaseBackend))
#3 /Users/joachim/Sites/dcb-repos/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\Container->createServ in /Users/joachim/Sites/dcb-repos/web/core/lib/Drupal/Core/Extension/Extension.php on line 67
 [warning] Drush command terminated abnormally. [0.2 sec, 12.43 MB]
```

**To Reproduce**

1. Moved a module folder from web/modules/custom to web/modules/contrib
2. did `drush cr`

**Expected behavior**

Everything rebuilds and Drupal is happy.

**Actual behavior**

Crash. See above.

**Workaround**

Truncate the `cache_container` table manually.

I suspect the problem is this in the serialized data in cache_container:

```
    [parameters] => Array
        (
            [kernel.environment] => prod
            [container.modules] => Array
** module paths are in here!! what is this, wordpress???**
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.4
| Drupal version? | 8.9.5
| PHP version     | 7.3
| OS?             | Mac/Linux/Windows

**Additional information**

**Comment by weitzman** [comment]
Cache:rebuild just calls Drupal's `drupal_rebuild();`. I think any bug would be there. Please search Drupal core issues pr debug away.

**Comment by alexpott** [comment]
Maybe https://www.drupal.org/project/drupal/issues/2160091 will fix this.

**Comment by flyke** [comment]
I was updating a project from Drupal 8 to Drupal 9, following whatever the upgrade_status module says, and in that process (removing modules via composer that are uninstalled) I got the same error. I just came here to say thank you for the tip to truncate the cache_container table in order to make 'drush cr' work again !

**Comment by joachim-n** [comment]
This is the relevant core issue: https://www.drupal.org/project/drupal/issues/2651144

**Comment by JPustkuchen** [comment]
The strange thing is, that "Flush caches" in the frontend (I think it's from Devel) solves the issue. Maybe it does more?
