### ISSUE TITLE
Out of box tideways profiling fails

### ISSUE THREAD

**Issue by andypost** [drush-ops/drush#4704]
**Describe the bug**
Using tideways_xhprof extension I'm getting
```
 $ DRUSH_XH_LINK=1 vendor/bin/drush version
PHP Fatal error:  Uncaught TypeError: Drush\Commands\core\XhprofCommands::xhprofFlags(): Argument #1 ($config) must be of type array, null given, called in /var/www/html/web/vendor/drush/drush/src/Commands/core/XhprofCommands.php on line 68 and defined in /var/www/html/web/vendor/drush/drush/src/Commands/core/XhprofCommands.php:91
Stack trace:
#0 /var/www/html/web/vendor/drush/drush/src/Commands/core/XhprofCommands.php(68): Drush\Commands\core\XhprofCommands::xhprofFlags()
#1 /var/www/html/web/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(47): Drush\Commands\core\XhprofCommands->xhprofInitialize()
#2 /var/www/html/web/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(36): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->doInitializeHook()
#3 /var/www/html/web/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(29): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook()
#4 /var/www/html/web/vendor/consolidation/annotated-command/src/CommandProcessor.php(145): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize()
#5 /var/www/html/web/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(296): Consolidation\AnnotatedCommand\CommandProcessor->initializeHook()
#6 /var/www/html/web/vendor/symfony/console/Command/Command.php(221): Consolidation\AnnotatedCommand\AnnotatedCommand->initialize()
#7 /var/www/html/web/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run()
#8 /var/www/html/web/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /var/www/html/web/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#10 /var/www/html/web/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run()
#11 /var/www/html/web/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun()
#12 /var/www/html/web/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run()
#13 /var/www/html/web/vendor/drush/drush/drush(4): require('...')
#14 {main}
  thrown in /var/www/html/web/vendor/drush/drush/src/Commands/core/XhprofCommands.php on line 91
```

**To Reproduce**
Using `alpine:edge` based docker image with https://pkgs.alpinelinux.org/package/edge/testing/x86_64/php8-tideways_xhprof package but getting the same on PHP 7.4 too

**Expected behavior**
Profiling flags initialized with default values and overridable from environment variables.

**Actual behavior**
Value of "xh.link" (and other options) is not possible to override with env vars

**Workaround**
add settings directly to `drush.yml`

```
xh:
  link: apache
  profile-builtins: false
  profile-cpu: true
  profile-memory: true
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4.0
| Drupal version? | 9.x
| PHP version     | 7.x,8.x
| OS?             | Linux (Alpinelinux and Ubuntu)

**Additional information**
Discussed in slack about a way to override config via environment variables

**Comment by greg-1-anderson** [comment]
Did you try `drush --xh-link=1 version`? The config environment variables stuff seems like it might be broken. DRUSH_OPTIONS_URI works, but arbitrary config can't be set. Not sure why.

**Comment by andypost** [comment]
I find the issue fixed, just waiting for next release and feedback

Here's related follow-up https://github.com/drush-ops/drush/pull/4710 to make things less fragile for xhprof too
