### ISSUE TITLE
Drush 11 RC6: drush uli throws error due to undefined function drush_is_windows()

### ISSUE THREAD

**Issue by drubb** [drush-ops/drush#4997]
I'm using Drush 11 RC6 on Linux, with Drupal Core 9.3.2

Currently it throws an error when using drush uli, that was not present in RC5.
Here's the verbose command output:
```
 ...
 [debug] Add a commandfile class: Drupal\search_api\Commands\SearchApiCommands [0.22 sec, 25.15 MB]
 [debug] Add a commandfile class: Drupal\smart_date\Commands\SmartDateDrushCommands [0.22 sec, 25.25 MB]
 [debug] Add a commandfile class: Drupal\token\Commands\TokenCommands [0.22 sec, 25.25 MB]
 [debug] Add a commandfile class: Drupal\pathauto\Commands\PathautoCommands [0.22 sec, 25.25 MB]
 [error]  Error: Call to undefined function Drush\Exec\drush_is_windows() in Drush\Commands\core\LoginCommands->startBrowser() (line 31 of /app/vendor/drush/drush/src/Exec/ExecTrait.php) #0 /app/vendor/drush/drush/src/Commands/core/LoginCommands.php(92): Drush\Commands\core\LoginCommands->startBrowser('http://frs.lndo...', false, NULL, true)
#1 [internal function]: Drush\Commands\core\LoginCommands->login('', Array)
#2 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#3 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /app/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /app/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /app/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#13 /app/vendor/drush/drush/drush(3): require('/app/vendor/dru...')
#14 /app/vendor/bin/drush(102): include('/app/vendor/dru...')
#15 {main}. [0.26 sec, 30.4 MB]
 ...
```

**Comment by drubb** [comment]
Similar bug for drush php:

```
Error: Call to undefined method Drush\Config\DrushConfig::cache() in Drush\Drupal\Commands\core\CliCommands->historyPath()
```
Downgrading to RC5 resolves both errors.

**Comment by weitzman** [comment]
RC7 has been released. Thanks for testing.
