### ISSUE TITLE
Drush generate failures

### ISSUE THREAD

**Issue by ptmkenny** [drush-ops/drush#5256]
**Describe the bug**

**drush generate module** works.

**drush generate entity:content**, **drush generate service:middleware** and so on fail.

**To Reproduce**
Enter the relevant commands.

PHP 8.1 with drush 11.2.1 running locally in lando/platformsh.
`symfony/console` 4.4.45
`chi-teck/drupal-code-generator` 2.6.1

**Actual behavior**

```
web@5accffd0f86b:/app$ drush generate entity:content

 Welcome to content-entity generator!
––––––––––––––––––––––––––––––––––––––

 Module machine name [web]:
 ➤  [error]  Error: Call to undefined function Symfony\Component\Console\Helper\shell_exec() in Symfony\Component\Console\Helper\QuestionHelper->autocomplete() (line 250 of /app/vendor/symfony/console/Helper/QuestionHelper.php) #0 /app/vendor/symfony/console/Helper/QuestionHelper.php(136): Symfony\Component\Console\Helper\QuestionHelper->autocomplete(Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question), Resource id #1, Object(Closure))
#1 /app/vendor/symfony/console/Helper/QuestionHelper.php(66): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question))
#2 /app/vendor/symfony/console/Helper/QuestionHelper.php(467): Symfony\Component\Console\Helper\QuestionHelper->Symfony\Component\Console\Helper\{closure}()
#3 /app/vendor/symfony/console/Helper/QuestionHelper.php(69): Symfony\Component\Console\Helper\QuestionHelper->validateAttempts(Object(Closure), Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question))
#4 /app/vendor/chi-teck/drupal-code-generator/src/Helper/QuestionHelper.php(39): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question))
#5 /app/vendor/chi-teck/drupal-code-generator/src/Compatibility/Php8/AskTrait.php(15): DrupalCodeGenerator\Helper\QuestionHelper->compatAsk(Object(Symfony\Component\Console\Input\ArgvInput), Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question))
#6 /app/vendor/chi-teck/drupal-code-generator/src/Style/GeneratorStyle.php(65): DrupalCodeGenerator\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question))
#7 /app/vendor/chi-teck/drupal-code-generator/src/Compatibility/Php8/AskQuestionTrait.php(13): DrupalCodeGenerator\Style\GeneratorStyle->compatAskQuestion(Object(Symfony\Component\Console\Question\Question))
#8 /app/vendor/chi-teck/drupal-code-generator/src/Command/DrupalGenerator.php(115): DrupalCodeGenerator\Style\GeneratorStyle->askQuestion(Object(Symfony\Component\Console\Question\Question))
#9 /app/vendor/chi-teck/drupal-code-generator/src/Command/DrupalGenerator.php(77): DrupalCodeGenerator\Command\DrupalGenerator->askMachineName(Array)
#10 /app/vendor/chi-teck/drupal-code-generator/src/Command/Entity/ContentEntity.php(22): DrupalCodeGenerator\Command\DrupalGenerator->collectDefault(Array)
#11 /app/vendor/chi-teck/drupal-code-generator/src/Command/Generator.php(140): DrupalCodeGenerator\Command\Entity\ContentEntity->generate(Array)
#12 /app/vendor/symfony/console/Command/Command.php(255): DrupalCodeGenerator\Command\Generator->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /app/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(DrupalCodeGenerator\Command\Entity\ContentEntity), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /app/vendor/drush/drush/src/Commands/generate/GenerateCommands.php(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 [internal function]: Drush\Commands\generate\GenerateCommands->generate('entity:content', Array)
#18 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#19 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#20 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#21 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#22 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /app/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /app/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /app/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#29 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#30 /app/vendor/bin/drush(107): include('/app/vendor/dru...')
#31 {main}.
Error: Call to undefined function Symfony\Component\Console\Helper\shell_exec() in /app/vendor/symfony/console/Helper/QuestionHelper.php on line 250 #0 /app/vendor/symfony/console/Helper/QuestionHelper.php(136): Symfony\Component\Console\Helper\QuestionHelper->autocomplete(Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question), Resource id #1, Object(Closure))
#1 /app/vendor/symfony/console/Helper/QuestionHelper.php(66): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question))
#2 /app/vendor/symfony/console/Helper/QuestionHelper.php(467): Symfony\Component\Console\Helper\QuestionHelper->Symfony\Component\Console\Helper\{closure}()
#3 /app/vendor/symfony/console/Helper/QuestionHelper.php(69): Symfony\Component\Console\Helper\QuestionHelper->validateAttempts(Object(Closure), Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question))
#4 /app/vendor/chi-teck/drupal-code-generator/src/Helper/QuestionHelper.php(39): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question))
#5 /app/vendor/chi-teck/drupal-code-generator/src/Compatibility/Php8/AskTrait.php(15): DrupalCodeGenerator\Helper\QuestionHelper->compatAsk(Object(Symfony\Component\Console\Input\ArgvInput), Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question))
#6 /app/vendor/chi-teck/drupal-code-generator/src/Style/GeneratorStyle.php(65): DrupalCodeGenerator\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(DrupalCodeGenerator\Style\GeneratorStyle), Object(Symfony\Component\Console\Question\Question))
#7 /app/vendor/chi-teck/drupal-code-generator/src/Compatibility/Php8/AskQuestionTrait.php(13): DrupalCodeGenerator\Style\GeneratorStyle->compatAskQuestion(Object(Symfony\Component\Console\Question\Question))
#8 /app/vendor/chi-teck/drupal-code-generator/src/Command/DrupalGenerator.php(115): DrupalCodeGenerator\Style\GeneratorStyle->askQuestion(Object(Symfony\Component\Console\Question\Question))
#9 /app/vendor/chi-teck/drupal-code-generator/src/Command/DrupalGenerator.php(77): DrupalCodeGenerator\Command\DrupalGenerator->askMachineName(Array)
#10 /app/vendor/chi-teck/drupal-code-generator/src/Command/Entity/ContentEntity.php(22): DrupalCodeGenerator\Command\DrupalGenerator->collectDefault(Array)
#11 /app/vendor/chi-teck/drupal-code-generator/src/Command/Generator.php(140): DrupalCodeGenerator\Command\Entity\ContentEntity->generate(Array)
#12 /app/vendor/symfony/console/Command/Command.php(255): DrupalCodeGenerator\Command\Generator->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /app/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(DrupalCodeGenerator\Command\Entity\ContentEntity), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /app/vendor/drush/drush/src/Commands/generate/GenerateCommands.php(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 [internal function]: Drush\Commands\generate\GenerateCommands->generate('entity:content', Array)
#18 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#19 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#20 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#21 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#22 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /app/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /app/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /app/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#29 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#30 /app/vendor/bin/drush(107): include('/app/vendor/dru...')
#31 {main}
Error: Call to undefined function Symfony\Component\Console\Helper\shell_exec() in Symfony\Component\Console\Helper\QuestionHelper->autocomplete() (line 250 of /app/vendor/symfony/console/Helper/QuestionHelper.php).
 [warning] Drush command terminated abnormally.
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.2.1
| Drupal version? | 9.4.7
| PHP version     | 8.1
| OS?             | linux

**Comment by weitzman** [comment]
That looks like a Symfony Console bug. Not much Drush can do.

**Comment by ptmkenny** [comment]
Ok thanks.  Spinning up a new lando environment with php 8.0 does not have the problem, so I'll just do my `generate` commands with 8.0 instead of 8.1 for now.

**Comment by Chi-teck** [comment]
@ptmkenny it's likely because `shell_exec` function is disabled by your PHP settings.
You can check if it works as follows `php -r 'echo shell_exec("whoami");'`.
