### ISSUE TITLE
drush topic docs:* commands failure

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#5305]
**Describe the bug**

```
$ drush topic docs:script
 [error]  Error: Typed property Drush\Commands\DrushCommands::$commandData must not be accessed before initialization in Drush\Commands\core\DocsCommands->script() (line 119 of /var/www/d10/docroot/vendor/drush/drush/src/Commands/core/DocsCommands.php) #0 [internal function]: Drush\Commands\core\DocsCommands->script()
#1 /var/www/d10/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array()
#2 /var/www/d10/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#3 /var/www/d10/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#4 /var/www/d10/docroot/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(374): Consolidation\AnnotatedCommand\CommandProcessor->process()
#5 /var/www/d10/docroot/vendor/symfony/console/Command/Command.php(312): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#6 /var/www/d10/docroot/vendor/symfony/console/Application.php(1043): Symfony\Component\Console\Command\Command->run()
#7 /var/www/d10/docroot/vendor/symfony/console/Application.php(317): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/d10/docroot/vendor/symfony/console/Application.php(173): Symfony\Component\Console\Application->doRun()
#9 /var/www/d10/docroot/vendor/drush/drush/src/Commands/core/TopicCommands.php(38): Symfony\Component\Console\Application->run()
#10 [internal function]: Drush\Commands\core\TopicCommands->topic()
#11 /var/www/d10/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array()
#12 /var/www/d10/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#13 /var/www/d10/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#14 /var/www/d10/docroot/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(374): Consolidation\AnnotatedCommand\CommandProcessor->process()
#15 /var/www/d10/docroot/vendor/symfony/console/Command/Command.php(312): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#16 /var/www/d10/docroot/vendor/symfony/console/Application.php(1043): Symfony\Component\Console\Command\Command->run()
#17 /var/www/d10/docroot/vendor/symfony/console/Application.php(317): Symfony\Component\Console\Application->doRunCommand()
#18 /var/www/d10/docroot/vendor/symfony/console/Application.php(173): Symfony\Component\Console\Application->doRun()
#19 /var/www/d10/docroot/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run()
#20 /var/www/d10/docroot/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun()
#21 /var/www/d10/docroot/vendor/drush/drush/drush.php(77): Drush\Runtime\Runtime->run()
#22 /var/www/d10/docroot/vendor/drush/drush/drush(4): require('...')
#23 /var/www/d10/docroot/vendor/bin/drush(120): include('...')
#24 {main}. 
```

**To Reproduce**
What did you do?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version  | 11.x
| Drupal version | 10.x
| PHP version     | 8.1
| OS             | Linux

**Comment by weitzman** [comment]
I noticed this too. Help appreciated.
