### ISSUE TITLE
In Process.php line 1019:   TTY mode requires /dev/tty to be read/writable

### ISSUE THREAD

**Issue by jonathan1055** [drush-ops/drush#5347]
**Describe the bug**
In drush11 trying to run `drush runserver` gives me
```
In Process.php line 1019:
  TTY mode requires /dev/tty to be read/writable.  
```
This is exactly what was reported in #4015 and the discussion there suggested it was fixed. 

**To Reproduce**
Fails in drush11. But runs fine in drush10

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.4
| Drupal version? | 10.x
| PHP version     | 8.1
| OS?             | Mac

This is a support request, as I expect the bug was fixed before. Thanks

**Comment by weitzman** [comment]
Any chance you are using Drush Launcher instead of calling vendor/bin/drush directly? I cant reproduce this on OSX.

**Comment by weitzman** [comment]
maybe share output of `drush status` and `composer show`

**Comment by jonathan1055** [comment]
Thanks for the reply. I was using the drush launcher, but the same happens when I try `vendor/bin/drush runserver`
Are there other ways I can try to run it? As I said, drush10 on a drupal 9.5 works fine, but drush 11 on a D10 environment fails.

**drush status**
```
Drupal version   : 10.0.1-dev                                                       
Site URI         : http://default                                                   
DB driver        : mysql                                                            
DB hostname      : localhost                                                        
DB port          :                                                                  
DB username      : drupal10                                                         
DB name          : drupal100dev                                                     
Database         : Connected                                                        
Drupal bootstrap : Successful                                                       
Default theme    : olivero                                                          
Admin theme      : seven                                                            
PHP binary       : /usr/local/Cellar/php/8.1.10/bin/php                             
PHP config       : /usr/local/etc/php/8.1/php.ini                                   
PHP OS           : Darwin                                                           
PHP version      : 8.1.10                                                           
Drush script     : /Library/WebServer/web/drupal100dev/vendor/drush/drush/drush     
Drush version    : 11.4.0                                                           
Drush temp       : /tmp                                                             
Drush configs    : /Library/WebServer/web/drupal100dev/vendor/drush/drush/drush.yml 
Install profile  : standard                                                         
Drupal root      : /Library/WebServer/web/drupal100dev                              
Site path        : sites/default                                                    
Files, Public    : sites/default/files                                              
Files, Temp      : /tmp   
```
I also get at the end of the status call the following:
```
PHP Fatal error:  Cannot redeclare composerRequiree96ef5ed469e804f25c286ba9f7e7584()
(previously declared in /Library/WebServer/Web/drupal100dev/vendor/composer/autoload_real.php:54)
in /Library/WebServer/web/drupal100dev/vendor/composer/autoload_real.php on line 54
```
**composer show**
[_composer_show.txt](https://github.com/drush-ops/drush/files/10338024/_composer_show.txt)

**Comment by weitzman** [comment]
Your output looks OK to me. Its not clear to me whats going on.

**Comment by jonathan1055** [comment]
Just tried `vendor/bin/drush runserver --no-interaction --debug` (from the linked issue)

**Comment by jonathan1055** [comment]
It gives more detail, but not sure if it will show anything.

**Comment by jonathan1055** [comment]
[_runserver_debug.txt](https://github.com/drush-ops/drush/files/10338641/_runserver_debug.txt)

**Comment by jonathan1055** [comment]
symphony process.php has
```
    /**
     * Returns whether TTY is supported on the current operating system.
     */
    public static function isTtySupported(): bool
    {
        static $isTtySupported;
        return $isTtySupported ??= ('/' === \DIRECTORY_SEPARATOR && stream_isatty(\STDOUT));
    }
```

**Comment by jonathan1055** [comment]
Fails in
```
   public function setTty(bool $tty): static
    {
        if ('\\' === \DIRECTORY_SEPARATOR && $tty) {
            throw new RuntimeException('TTY mode is not supported on Windows platform.');
        }
        if ($tty && !self::isTtySupported()) {
            throw new RuntimeException('TTY mode requires /dev/tty to be read/writable.');
        }
        $this->tty = $tty;
        return $this;
    }
```

**Comment by jonathan1055** [comment]
I've got around it temporarily by commenting out the exception line :-) but obviosuly that's not a sustainable solution

**Comment by weitzman** [comment]
In https://github.com/drush-ops/drush/blob/11.x/src/Commands/core/RunserverCommands.php#L80, does `isTtySupported()` return `TRUE`? If so, why does consolidation/site-process (thats where `Tty` class lives) think you have support where Symfony Process thinks you dont.

**Comment by jonathan1055** [comment]
OK I will try to check that. 

Dumb question: The exception says "TTY mode requires /dev/tty to be read/writable". Is this referring simply to the /dev/tty folder? `ls -la /dev/tty` gives: `crw-rw-rw-  1 root  wheel    2,   0  4 Jan 10:22 /dev/tty`

**Comment by jonathan1055** [comment]
Yes, in runserverCommands, runserver function line 80 `Tty::isTtySupported()` returns TRUE (1)

Then `setTty()` is called and in https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Process/Process.php#L1012 on line 1018 we have `self::isTtySupported()` but this returns FALSE (blank) and thus the exception is thrown.

In https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Process/Process.php#L1203 `isTtySupported()` line 1027 `stream_isatty(\STDOUT)` returns FALSE which is the reason for the problem, I think.

**Comment by jonathan1055** [comment]
To answer your second question, in https://github.com/consolidation/site-process/blob/main/src/Util/Tty.php#L16 on line 19 the function `posix_isatty` does exist, so the return is set from calling `posix_isatty(STDIN)` which gives TRUE

Is that the difference? This is testing STDIN whereas in symfony process `isTtySupported()`, the check is on `stream_isatty(\STDOUT)`

**Comment by weitzman** [comment]
@greg-1-anderson any ideas?

**Comment by pameeela** [comment]
This same thing is happening to me, only on sites where I have updated to D10. Tried updating drush from 10 to 11 but still the same issue. Relieved that I am not the only one!

It only happens when using drush on my local machine to access remote sites, e.g. `drush @site.env cr`

If I add `tty: false` to my drush config, then I can run most commands, but still can't ssh via drush because I get tty error.

**Comment by jonathan1055** [comment]
Hi, I don't know if this will fix your problem, but I modified `site-process/src/Util/Tty.php` 
changing `return posix_isatty(STDIN)` to `return posix_isatty(STDOUT);`

Patch attached, in case you want to try it.
[_site_process_tty.patch](https://github.com/drush-ops/drush/files/12617409/_site_process_tty.patch)

**Comment by pameeela** [comment]
Thanks for that. Interestingly, it does work to suppress the error, but if I try `drush @site.env ssh` it runs without error but the ssh session does not start. 

However, if I modify Process.php to comment out the exception, then it works just fine.

Also, I recently got a new laptop and set up everything from scratch assuming that I would be rid of this but... it's still happening. So I guess it's something specific in how I'm setting everything up. Still seems really odd we could be the only two people who've hit this with D10 but certainly seems that way!

**Comment by mhariip** [comment]
> Thanks for that. Interestingly, it does work to suppress the error, but if I try `drush @site.env ssh` it runs without error but the ssh session does not start.
> 
> However, if I modify Process.php to comment out the exception, then it works just fine.
> 
> Also, I recently got a new laptop and set up everything from scratch assuming that I would be rid of this but... it's still happening. So I guess it's something specific in how I'm setting everything up. Still seems really odd we could be the only two people who've hit this with D10 but certainly seems that way!

You are not alone. I have this very same issue with D10 Site aliases. Hope this issue will be resolved soon.

**Comment by idiazroncero** [comment]
Same problem here with D10 site aliases and Drush 11.6, both with Drush Launcher and `vendor/bin/drush`

**Comment by joegl** [comment]
I'm having the same problem with Drush 9, 10 and 11 on any remote D10 site. My local aliases still work fine.

Interestingly, this only started happening to me once I added (and then removed) the `drupal-check` [package](https://github.com/mglaman/drupal-check)

**Comment by greg-1-anderson** [comment]
Just noticed this issue; didn't see the mention earlier. If folks who are having this problem run:
```
php -r 'var_export(stream_isatty(\STDOUT));'
```
Do you get `true` or `false`? I get `true` on my system; I would expect from the comments above that the problem is caused when stream_isatty returns false for STDOUT. I am not sure what would cause that.

**Comment by joegl** [comment]
I get `true` on my system when I run:

```
php -r 'var_export(stream_isatty(\STDOUT));'
```

But I also may have a unique set up causing my issue.

**Comment by greg-1-anderson** [comment]
> It only happens when using drush on my local machine to access remote sites, e.g. drush @site.env cr

I missed this critical bit if information! Take a look at your ssh config, and see if it is configured to allow a tty to be allocated. In some configurations, ssh does not do this, because a tty is an exhaustible resource, and not every remote command needs a tty.

Check and see if behavior is any different if you run Drush in non-interactive mode (`-n`).

**Comment by joegl** [comment]
Drush works when I use the non-interactive mode (`-n`) so you're definitely on to something. What are you referring to when you say "look at your ssh config"? Something in `/etc/ssh/ssh_config` or a drush SSH configuration? Thanks!

**Comment by greg-1-anderson** [comment]
I don't know ssh config off the top of my head; I just know that if I ssh from my Mac to an Ubuntu box, I get a tty, but if I ssh to a Pantheon container, I don't, because Pantheon has configured sshd to not allocate tty's.

When you run Drush in non-interactive mode, it skips the tty check and behaves as if you were running without a tty, so this avoids any inconsistency with the tests to determine whether or not a tty is available. Ideally, Drush would figure it out and do the right thing, but at least there is this workaround.

**Comment by pameeela** [comment]
@greg-1-anderson ok interesting, so using `-n` works but only for non-ssh commands, e.g. :
`drush -n @site.dev cr` works (where it doesn't without `-n`) 
but `drush -n @site.dev ssh` still results in `TTY mode requires /dev/tty to be read/writable.` 
So the same result as adding `tty: false` to the drush ssh config (noted a few months back that adding that to the drush config allows me to run other commands but `ssh` still fails).

I've just worked around this by either using ssh directly (adding the config and running `ssh dev.site`) or using `lando drush` to run the ssh command. I am still keen to resolve it just out of stubbornness.

**Comment by pameeela** [comment]
Was just thinking it might be down to the ssh options in my drush config, but I don't think that's it because even if I break the config, the command fails with `TTY mode requires /dev/tty to be read/writable.` before it hits the broken config.

**Comment by greg-1-anderson** [comment]
Sounds like the ssh command requires a tty, although I don't specifically remember, and in theory this should not be necessary. Does `drush -n @site.dev ssh pwd` behave the same way, or does it work?

**Comment by pameeela** [comment]
Yes, that works. I've only just noticed though that when I run any drush command that way, it actually runs twice. That doesn't happen if I run the same command via Lando. Same version of drush (11.6.0), same config.

> pamelabarone@site % drush @site.dev ssh pwd   
> /app/site/web
> /app/site/web

So there's obviously something else strange going on with this setup. I found a few old issues where people had the same issue of commands running twice but they are all very old and look to have been resolved. Now leaning toward giving up on this considering I have workarounds! Wonder whether any others are finding the same.

**Comment by greg-1-anderson** [comment]
My guess is that the command isn't running twice, it's just that it's output is being printed twice.

**Comment by pameeela** [comment]
It definitely executes twice, if I use `-v` I can see the execution running in full twice and with `drush uli` I get two unique login links.

**Comment by greg-1-anderson** [comment]
Very odd; I have no good theory on how that could be happening. Would be interested to know, if you track down the cause.

**Comment by yookoala** [comment]
Run into similar issue in Drush 12.4.3. Has there been any solution other than to comment out the `throw` line in Process.php?

**Comment by yookoala** [comment]
Dig a little bit deeper. the cause of the TTY failure.

The stacktrace of the exception is:
```
#0 /home/foobar/drupal/vendor/drush/drush/src/Commands/sql/SqlCommands.php(142): Symfony\Component\Process\Process->setTty()
#1 [internal function]: Drush\Commands\sql\SqlCommands->cli()
#2 /home/foobar/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
#3 /home/foobar/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#4 /home/foobar/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#5 /home/foobar/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process()
#6 /home/foobar/drupal/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#7 /home/foobar/drupal/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#8 /home/foobar/drupal/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#9 /home/foobar/drupal/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#10 /home/foobar/drupal/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#11 /home/foobar/drupal/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#12 /home/foobar/drupal/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#13 /home/foobar/drupal/vendor/drush/drush/drush(4): require('...')
#14 {main} [warning] Drush command terminated abnormally.
```

The cause of the exception is because the `stream_isatty(\STDOUT))` returns `bool(false)` when running in drush. This is even if the system supports TTY. On the same system when running `php -r 'var_dump(stream_isatty(\STDOUT));'` would return `bool(true)`. So something was done in drush to cause that to happen.

This would then cause `Symfony\Component\Process\Process::isTtySupported` to evaluated to `bool(false)` and, eventually, cause Process to throw `RuntimeException('TTY mode requires /dev/tty to be read/writable')`.

**Comment by yookoala** [comment]
I think I nailed down the problem to the use of global drush launcher.

If I run drush directly with the relatively path "./vendor/bin/drush", then `stream_isatty(\STDOUT))` would return `boolean(true)` and the entire thing works. On the other hand, if I run drush through [drush-launcher](https://github.com/drush-ops/drush-launcher), then `stream_isatty(\STDOUT))` returns `boolean(false)` and thus the whole issue.

Does anybody have problem here also uses a global drush launcher? Are you problem fixed if you opt not to use it?

**Comment by yookoala** [comment]
I wrote a small bash function to mimic the drush launcher behaviour in bash environment.

You'll need to remove drush launcher from your PATH, then source this file in your .bashrc for it to work:
https://gist.github.com/yookoala/89f02aefc0b49789a7f4d42ebe533e57
