### ISSUE TITLE
drush has some trouble after I import a database dump

### ISSUE THREAD

**Issue by AppLEaDaY** [drush-ops/drush#5364]
I'm struggling to migrate from Drupal 8 to Drupal 9.
In a Drupal 9 instance after I import the database dump from a Drupal 8 instance something goes definitely wrong with drush. I don't have the same problem with another Drupal 9 instance that does not contain the up to date data from the Drupal 8 instance (I started a second migration from scratch and changed database data).
I'm reporting below something about commands issued and responses, with the replacement I introduced to maintain privacy.
I just' cannot understand what's going on there and what can I do to fix the problem, supposed I really have a way out.

**The link to other issues are not intentionally inserted. The text containing hashes followed by numbers, I tried to report it as code, but that way the formatting was not preserved, and readability suffered from that. I apologize for the inconvenience.**

Thanks in advance!

Andrea

-------------------------------------------------------

[USERNAME@HOSTNAME web]$ ../vendor/bin/drush cr
 [warning] Erroneous data format for unserializing 'Symfony\Component\Routing\Route' RouteProvider.php:380
 [warning] Drush command terminated abnormally.
[USERNAME@HOSTNAME web]$ ../vendor/bin/drush 
 [error]  ParseError: syntax error, unexpected 'Token' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in Composer\Autoload\includeFile() (line 35 of /HOME PATH/WEBSITE HOST NAME/web/modules/contrib/devel/src/Commands/DevelCommands.php) #0 /HOME PATH/WEBSITE HOST NAME/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/HOME PATH/...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Drupal\\devel\\Co...')
#2 /HOME PATH/WEBSITE HOST NAME/web/core/lib/Drupal/Component/DependencyInjection/Container.php(259): spl_autoload_call('Drupal\\devel\\Co...')
#3 /HOME PATH/WEBSITE HOST NAME/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\Container->createService(Array, 'devel.commands')
#4 /HOME PATH/WEBSITE HOST NAME/web/core/lib/Drupal/Component/DependencyInjection/Container.php(434): Drupal\Component\DependencyInjection\Container->get('devel.commands', 1)
#5 /HOME PATH/WEBSITE HOST NAME/web/core/lib/Drupal/Component/DependencyInjection/Container.php(273): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#6 /HOME PATH/WEBSITE HOST NAME/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\Container->createService(Array, 'drush.command.s...')
#7 /HOME PATH/WEBSITE HOST NAME/vendor/drush/drush/src/Boot/DrupalBoot8.php(280): Drupal\Component\DependencyInjection\Container->get('drush.command.s...')
#8 /HOME PATH/WEBSITE HOST NAME/vendor/drush/drush/src/Boot/DrupalBoot8.php(246): Drush\Boot\DrupalBoot8->addDrupalModuleDrushCommands(Object(Drush\Boot\BootstrapManager))
#9 /HOME PATH/WEBSITE HOST NAME/vendor/drush/drush/src/Boot/BootstrapManager.php(293): Drush\Boot\DrupalBoot8->bootstrapDrupalFull(Object(Drush\Boot\BootstrapManager), NULL)
#10 /HOME PATH/WEBSITE HOST NAME/vendor/drush/drush/src/Boot/BootstrapManager.php(493): Drush\Boot\BootstrapManager->doBootstrap(5, 6, NULL)
#11 /HOME PATH/WEBSITE HOST NAME/vendor/drush/drush/src/Boot/BootstrapManager.php(427): Drush\Boot\BootstrapManager->bootstrapMax(6)
#12 /HOME PATH/WEBSITE HOST NAME/vendor/drush/drush/src/Boot/BootstrapManager.php(396): Drush\Boot\BootstrapManager->bootstrapToPhaseIndex(-2, Object(Consolidation\AnnotatedCommand\AnnotationData))
#13 /HOME PATH/WEBSITE HOST NAME/vendor/drush/drush/src/Boot/BootstrapHook.php(28): Drush\Boot\BootstrapManager->bootstrapToPhase('max', Object(Consolidation\AnnotatedCommand\AnnotationData))
#14 /HOME PATH/WEBSITE HOST NAME/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(44): Drush\Boot\BootstrapHook->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#15 /HOME PATH/WEBSITE HOST NAME/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(36): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->doInitializeHook(Object(Drush\Boot\BootstrapHook), Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#16 /HOME PATH/WEBSITE HOST NAME/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(29): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Object(Drush\Boot\BootstrapHook), Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#17 /HOME PATH/WEBSITE HOST NAME/vendor/consolidation/annotated-command/src/CommandProcessor.php(145): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#18 /HOME PATH/WEBSITE HOST NAME/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(375): Consolidation\AnnotatedCommand\CommandProcessor->initializeHook(Object(Drush\Symfony\DrushArgvInput), Array, Object(Consolidation\AnnotatedCommand\AnnotationData))
#19 /HOME PATH/WEBSITE HOST NAME/vendor/symfony/console/Command/Command.php(221): Consolidation\AnnotatedCommand\AnnotatedCommand->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /HOME PATH/WEBSITE HOST NAME/vendor/symfony/console/Application.php(1039): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /HOME PATH/WEBSITE HOST NAME/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /HOME PATH/WEBSITE HOST NAME/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /HOME PATH/WEBSITE HOST NAME/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /HOME PATH/WEBSITE HOST NAME/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /HOME PATH/WEBSITE HOST NAME/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#26 /HOME PATH/WEBSITE HOST NAME/vendor/drush/drush/drush(3): require('/HOME PATH/...')
#27 /HOME PATH/WEBSITE HOST NAME/vendor/bin/drush(112): include('/HOME PATH/...')
#28 {main}. 
ParseError: syntax error, unexpected &#039;Token&#039; (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in Composer\Autoload\includeFile() (line 35 of /HOME PATH/WEBSITE HOST NAME/web/modules/contrib/devel/src/Commands/DevelCommands.php).
 [warning] Drush command terminated abnormally.
[USERNAME@HOSTNAME web]$

**Comment by AppLEaDaY** [comment]
UPDATE
It turned out I was using PHP 7.3.33 cli. By specifying the complete path to the php 8.0 cli drush does work as expected. I cannot tell yet why on another instance of drupal PHP 7.3.33 cli was enough to run some drush command with no problem.
