### ISSUE TITLE
state:get returns an error when retrieving an object

### ISSUE THREAD

**Issue by Matt-B50** [drush-ops/drush#5374]
**Describe the bug**
`drush state:get` returns an error when retrieving an object

See [State::get](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21State%21State.php/function/State%3A%3Aset/9) - mixed values can be stored in the drupal state system, this includes objects

**To Reproduce**
My custom module stores and retrieves an object as a key-value pair.

Here's a code snippet from my module:
```
	$token = json_decode($response->getBody());
	\Drupal::state()->set("mymodule.token", $token);

```

I can set and retrieve the key / value pair with no issues within Drupal.

Running `drush state:get mymodule.token` produces an error.

**Expected behavior**
I would expect drush to output the object value in a readable format (`stdClass Object` etc)

**Actual behavior**
The following error was reported:
```
 [error]  TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, stdClass given in str_replace() (line 36 of /app/vendor/consolidation/output-formatters/src/Formatters/TsvFormatter.php) #0 /app/vendor/consolidation/output-formatters/src/Formatters/TsvFormatter.php(36): str_replace(Array, Array, Object(stdClass))
#1 [internal function]: Consolidation\OutputFormatters\Formatters\TsvFormatter->Consolidation\OutputFormatters\Formatters\{closure}(Object(stdClass))
#2 /app/vendor/consolidation/output-formatters/src/Formatters/TsvFormatter.php(35): array_map(Object(Closure), Array)
#3 /app/vendor/consolidation/output-formatters/src/Formatters/TsvFormatter.php(29): Consolidation\OutputFormatters\Formatters\TsvFormatter->tsvEscape(Array)
#4 /app/vendor/consolidation/output-formatters/src/Formatters/CsvFormatter.php(89): Consolidation\OutputFormatters\Formatters\TsvFormatter->writeOneLine(Object(Symfony\Component\Console\Output\BufferedOutput), Array, Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#5 /app/vendor/consolidation/output-formatters/src/Transformations/TableTransformation.php(57): Consolidation\OutputFormatters\Formatters\CsvFormatter->write(Object(Symfony\Component\Console\Output\BufferedOutput), Array, Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#6 /app/vendor/consolidation/output-formatters/src/Formatters/StringFormatter.php(75): Consolidation\OutputFormatters\Transformations\TableTransformation->simplifyToString(Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#7 /app/vendor/consolidation/output-formatters/src/Formatters/StringFormatter.php(47): Consolidation\OutputFormatters\Formatters\StringFormatter->reduceToSigleFieldAndWrite(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Consolidation\OutputFormatters\Transformations\PropertyListTableTransformation), Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#8 /app/vendor/consolidation/output-formatters/src/FormatterManager.php(242): Consolidation\OutputFormatters\Formatters\StringFormatter->write(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Consolidation\OutputFormatters\Transformations\PropertyListTableTransformation), Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#9 /app/vendor/consolidation/annotated-command/src/ResultWriter.php(157): Consolidation\OutputFormatters\FormatterManager->write(Object(Symfony\Component\Console\Output\ConsoleOutput), 'string', Object(Consolidation\OutputFormatters\StructuredData\PropertyList), Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#10 /app/vendor/consolidation/annotated-command/src/ResultWriter.php(88): Consolidation\AnnotatedCommand\ResultWriter->writeUsingFormatter(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Consolidation\OutputFormatters\StructuredData\PropertyList), Object(Consolidation\AnnotatedCommand\CommandData), 0)
#11 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(246): Consolidation\AnnotatedCommand\ResultWriter->handle(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Consolidation\OutputFormatters\StructuredData\PropertyList), Object(Consolidation\AnnotatedCommand\CommandData), Object(Consolidation\AnnotatedCommand\Hooks\Dispatchers\StatusDeterminerHookDispatcher), Object(Consolidation\AnnotatedCommand\Hooks\Dispatchers\ExtracterHookDispatcher))
#12 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(180): Consolidation\AnnotatedCommand\CommandProcessor->handleResults(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Object(Consolidation\OutputFormatters\StructuredData\PropertyList), Object(Consolidation\AnnotatedCommand\CommandData))
#13 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(390): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#14 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /app/vendor/symfony/console/Application.php(1039): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /app/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /app/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /app/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#21 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#22 /app/vendor/bin/drush(120): include('/app/vendor/dru...')
#23 {main}. 
TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, stdClass given in /app/vendor/consolidation/output-formatters/src/Formatters/TsvFormatter.php on line 36 #0 /app/vendor/consolidation/output-formatters/src/Formatters/TsvFormatter.php(36): str_replace(Array, Array, Object(stdClass))
#1 [internal function]: Consolidation\OutputFormatters\Formatters\TsvFormatter->Consolidation\OutputFormatters\Formatters\{closure}(Object(stdClass))
#2 /app/vendor/consolidation/output-formatters/src/Formatters/TsvFormatter.php(35): array_map(Object(Closure), Array)
#3 /app/vendor/consolidation/output-formatters/src/Formatters/TsvFormatter.php(29): Consolidation\OutputFormatters\Formatters\TsvFormatter->tsvEscape(Array)
#4 /app/vendor/consolidation/output-formatters/src/Formatters/CsvFormatter.php(89): Consolidation\OutputFormatters\Formatters\TsvFormatter->writeOneLine(Object(Symfony\Component\Console\Output\BufferedOutput), Array, Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#5 /app/vendor/consolidation/output-formatters/src/Transformations/TableTransformation.php(57): Consolidation\OutputFormatters\Formatters\CsvFormatter->write(Object(Symfony\Component\Console\Output\BufferedOutput), Array, Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#6 /app/vendor/consolidation/output-formatters/src/Formatters/StringFormatter.php(75): Consolidation\OutputFormatters\Transformations\TableTransformation->simplifyToString(Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#7 /app/vendor/consolidation/output-formatters/src/Formatters/StringFormatter.php(47): Consolidation\OutputFormatters\Formatters\StringFormatter->reduceToSigleFieldAndWrite(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Consolidation\OutputFormatters\Transformations\PropertyListTableTransformation), Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#8 /app/vendor/consolidation/output-formatters/src/FormatterManager.php(242): Consolidation\OutputFormatters\Formatters\StringFormatter->write(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Consolidation\OutputFormatters\Transformations\PropertyListTableTransformation), Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#9 /app/vendor/consolidation/annotated-command/src/ResultWriter.php(157): Consolidation\OutputFormatters\FormatterManager->write(Object(Symfony\Component\Console\Output\ConsoleOutput), 'string', Object(Consolidation\OutputFormatters\StructuredData\PropertyList), Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#10 /app/vendor/consolidation/annotated-command/src/ResultWriter.php(88): Consolidation\AnnotatedCommand\ResultWriter->writeUsingFormatter(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Consolidation\OutputFormatters\StructuredData\PropertyList), Object(Consolidation\AnnotatedCommand\CommandData), 0)
#11 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(246): Consolidation\AnnotatedCommand\ResultWriter->handle(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Consolidation\OutputFormatters\StructuredData\PropertyList), Object(Consolidation\AnnotatedCommand\CommandData), Object(Consolidation\AnnotatedCommand\Hooks\Dispatchers\StatusDeterminerHookDispatcher), Object(Consolidation\AnnotatedCommand\Hooks\Dispatchers\ExtracterHookDispatcher))
#12 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(180): Consolidation\AnnotatedCommand\CommandProcessor->handleResults(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Object(Consolidation\OutputFormatters\StructuredData\PropertyList), Object(Consolidation\AnnotatedCommand\CommandData))
#13 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(390): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#14 /app/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /app/vendor/symfony/console/Application.php(1039): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /app/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /app/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /app/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#21 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#22 /app/vendor/bin/drush(120): include('/app/vendor/dru...')
#23 {main}
TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, stdClass given in str_replace() (line 36 of /app/vendor/consolidation/output-formatters/src/Formatters/TsvFormatter.php).
 [warning] Drush command terminated abnormally.
```

**Workaround**
None that I'm aware of

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.6.2
| Drupal version? | 9.5.2
| PHP version     | 8.1.10
| OS?             | Linux

**Additional information**
`drush state:del` works as expected with an object.

**Comment by Matt-B50** [comment]
[RTFM!!!!](https://www.drush.org/latest/commands/state_get/)

My bad, I probably should have read https://www.drush.org/latest/commands/state_get/ closer.

Running `drush state:get mymodule.token --format=var_dump` works fine!

Possibly an enhancement request here to improve the error handling / use var_dump if the value is not an array or  string.
