### ISSUE TITLE
drush cron --help fails

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#5541]
**To Reproduce**
```
$ drush cron --help
 [warning] DOMDocument::createElement(): unterminated entity reference & drush core:cron XmlDescriptor.php:69
 [warning] DOMDocument::createElement(): unterminated entity reference & drush core:cron HelpDocumentBuilder.php:36
Run all cron hooks in all active modules for specified site.

Examples:
 [error]  TypeError: Cannot access offset of type string on string in Drush\Commands\help\HelpCLIFormatter->write() (line 39 of /var/www/d10/web/vendor/drush/drush/src/Commands/help/HelpCLIFormatter.php) #0 /var/www/d10/web/vendor/consolidation/output-formatters/src/FormatterManager.php(242): Drush\Commands\help\HelpCLIFormatter->write()
#1 /var/www/d10/web/vendor/consolidation/annotated-command/src/ResultWriter.php(156): Consolidation\OutputFormatters\FormatterManager->write()
#2 /var/www/d10/web/vendor/consolidation/annotated-command/src/ResultWriter.php(88): Consolidation\AnnotatedCommand\ResultWriter->writeUsingFormatter()
#3 /var/www/d10/web/vendor/consolidation/annotated-command/src/CommandProcessor.php(246): Consolidation\AnnotatedCommand\ResultWriter->handle()
#4 /var/www/d10/web/vendor/consolidation/annotated-command/src/CommandProcessor.php(180): Consolidation\AnnotatedCommand\CommandProcessor->handleResults()
#5 /var/www/d10/web/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(386): Consolidation\AnnotatedCommand\CommandProcessor->process()
#6 /var/www/d10/web/vendor/symfony/console/Command/Command.php(312): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#7 /var/www/d10/web/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#8 /var/www/d10/web/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#9 /var/www/d10/web/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#10 /var/www/d10/web/vendor/drush/drush/src/Runtime/Runtime.php(126): Symfony\Component\Console\Application->run()
#11 /var/www/d10/web/vendor/drush/drush/src/Runtime/Runtime.php(53): Drush\Runtime\Runtime->doRun()
#12 /var/www/d10/web/vendor/drush/drush/drush.php(77): Drush\Runtime\Runtime->run()
#13 /var/www/d10/web/vendor/drush/drush/drush(4): require('...')
#14 /var/www/d10/web/vendor/bin/drush(120): include('...')
#15 {main}. 
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x
| Drupal version? | 10.x
| PHP version     | 8.x
| OS?             | Linux

**Additional information**
Same happens with `drush maint:status --help` command. Seems like double `&` has some special meaning when formatting examples.

**Comment by weitzman** [comment]
PR at https://github.com/consolidation/annotated-command/pull/300. Lets discuss there.
