### ISSUE TITLE
drush runserver fails on 12.0.0-rc2

### ISSUE THREAD

**Issue by mondrake** [drush-ops/drush#5589]
**Describe the bug**

```
TypeError: substr(): Argument #3 ($length) must be of type ?int, bool given in substr() (line 138 of /home/runner/work/d8-unit/d8-unit/vendor/drush/drush/src/Commands/core/RunserverCommands.php) #0 /home/runner/work/d8-unit/d8-unit/vendor/drush/drush/src/Commands/core/RunserverCommands.php(138): substr()
#1 /home/runner/work/d8-unit/d8-unit/vendor/drush/drush/src/Commands/core/RunserverCommands.php(96): Drush\Commands\core\RunserverCommands->parseUri()
#2 /home/runner/work/d8-unit/d8-unit/vendor/drush/drush/src/Commands/core/RunserverCommands.php(49): Drush\Commands\core\RunserverCommands->uri()
TypeError: substr(): Argument #3 ($length) must be of type ?int, bool given in substr() (line 138 of /home/runner/work/d8-unit/d8-unit/vendor/drush/drush/src/Commands/core/RunserverCommands.php).
#3 [internal function]: Drush\Commands\core\RunserverCommands->runserver()
#4 /home/runner/work/d8-unit/d8-unit/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
#5 /home/runner/work/d8-unit/d8-unit/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#6 /home/runner/work/d8-unit/d8-unit/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#7 /home/runner/work/d8-unit/d8-unit/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process()
#8 /home/runner/work/d8-unit/d8-unit/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#9 /home/runner/work/d8-unit/d8-unit/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run()
#10 /home/runner/work/d8-unit/d8-unit/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#11 /home/runner/work/d8-unit/d8-unit/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#12 /home/runner/work/d8-unit/d8-unit/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#13 /home/runner/work/d8-unit/d8-unit/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#14 /home/runner/work/d8-unit/d8-unit/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#15 /home/runner/work/d8-unit/d8-unit/vendor/drush/drush/drush(4): require('...')
#16 /home/runner/work/d8-unit/d8-unit/vendor/bin/drush(119): include('...')
#17 {main}. 
```

**To Reproduce**
`vendor/bin/drush runserver localhost:8080 --default-server=localhost:8080 &`

**Expected behavior**
A running test server.

**Actual behavior**
Bug aobove.

**Workaround**
No

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x
| Drupal version? | 11.x
| PHP version     | 8.2
| OS?             | Linux

**Additional information**
Nope

**Comment by mondrake** [comment]
🙏
