### ISSUE TITLE
When running "drush image:flush --all" it fails with Fatal error: Uncaught Error: Class "Drupal\image\Entity\ImageStyle" not found

### ISSUE THREAD

**Issue by rodrigoaguilera** [drush-ops/drush#5701]
**Describe the bug**
There is a fatal error when running `drush image:flush --all`

**To Reproduce**
Use drush 12.

**Expected behavior**
Image styles get flushed.

**Actual behavior**
There is an error

**Workaround**
Clean each image style individually

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.1.1.0
| Drupal version? | 10.1.1
| PHP version     | 8.2
| OS?             | Linux

**Additional information**
image module is enabled. It looks like Drupal is not initialized in the init hook

Stack trace:
```
#0 /var/www/html/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(47): Drush\Commands\core\ImageCommand
s->initFlush(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#1 /var/www/html/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(36): Consolidation\AnnotatedCommand\H
ooks\Dispatchers\InitializeHookDispatcher->doInitializeHook(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\Annot
atedCommand\AnnotationData))                                                                                                                    
#2 /var/www/html/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(29): Consolidation\AnnotatedCommand\H
ooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\Ann
otatedCommand\AnnotationData))                                                                                                                  
#3 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(145): Consolidation\AnnotatedCommand\Hooks\Dispatchers\Initiali
zeHookDispatcher->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))     
#4 /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(376): Consolidation\AnnotatedCommand\CommandProcessor->initiali
zeHook(Object(Symfony\Component\Console\Input\ArgvInput), Array, Object(Consolidation\AnnotatedCommand\AnnotationData))
#5 /var/www/html/vendor/symfony/console/Command/Command.php(292): Consolidation\AnnotatedCommand\AnnotatedCommand->initialize(Object(Symfony\Com
ponent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\I
nput\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#7 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\Annotated
Command\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Inpu
t\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\In
put\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\Co
nsoleOutput))
```

**Comment by rodrigoaguilera** [comment]
Thanks 😃
