### ISSUE TITLE
Drush 11 uses mixed type (PHP 8.0.0)

### ISSUE THREAD

**Issue by BramDriesen** [drush-ops/drush#5836]
**Describe the bug**
We noticed that the latest version of Drush 11 (11.6.0) is using the `mixed` type which is only available since PHP 8.0.0. Drush 11 however is claiming to support PHP 7.4+. 

**To Reproduce**
`drush cim --partial --source"some/directory/"`

```
[error]  TypeError: Argument 1 passed to Drush\Drupal\Commands\config\ConfigCommands::getDirectory() must be an instance of Drush\Drupal\Commands\config\mixed or null, string given, called in C:\home\site\wwwroot\data_web\website\vendor\drush\drush\src\Drupal\Commands\config\ConfigImportCommands.php on line 220 in Drush\Drupal\Commands\config\ConfigCommands::getDirectory() (line 393 of C:\home\site\wwwroot\data_web\website\vendor\drush\drush\src\Drupal\Commands\config\ConfigCommands.php) #0 C:\home\site\wwwroot\data_web\website\vendor\drush\drush\src\Drupal\Commands\config\ConfigImportCommands.php(220): Drush\Drupal\Commands\config\ConfigCommands::getDirectory()
#1 [internal function]: Drush\Drupal\Commands\config\ConfigImportCommands->import()
#2 C:\home\site\wwwroot\data_web\website\vendor\consolidation\annotated-command\src\CommandProcessor.php(276): call_user_func_array()
#3 C:\home\site\wwwroot\data_web\website\vendor\consolidation\annotated-command\src\CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#4 C:\home\site\wwwroot\data_web\website\vendor\consolidation\annotated-command\src\CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#5 C:\home\site\wwwroot\data_web\website\vendor\consolidation\annotated-command\src\AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process()
#6 C:\home\site\wwwroot\data_web\website\vendor\symfony\console\Command\Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#7 C:\home\site\wwwroot\data_web\website\vendor\symfony\console\Application.php(1039): Symfony\Component\Console\Command\Command->run()
#8 C:\home\site\wwwroot\data_web\website\vendor\symfony\console\Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#9 C:\home\site\wwwroot\data_web\website\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun()
#10 C:\home\site\wwwroot\data_web\website\vendor\drush\drush\src\Runtime\Runtime.php(124): Symfony\Component\Console\Application->run()
#11 C:\home\site\wwwroot\data_web\website\vendor\drush\drush\src\Runtime\Runtime.php(51): Drush\Runtime\Runtime->doRun()
#12 C:\home\site\wwwroot\data_web\website\vendor\drush\drush\drush.php(79): Drush\Runtime\Runtime->run()
#13 C:\home\site\wwwroot\data_web\website\vendor\drush\drush\drush(3): require('C:\\home\\site\\ww...')
#14 C:\home\site\wwwroot\data_web\website\vendor\bin\drush(115): include('C:\\home\\site\\ww...')
#15 {main}. 
```

**Expected behavior**
That the drush cim works.

**Actual behavior**
Fatal exception.

**Workaround**
Downgrade to drush 11.5

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.6.0
| Drupal version? | 9.5.9
| PHP version     | 7.4.30
| OS             | Windows

**Comment by BramDriesen** [comment]
https://github.com/drush-ops/drush/blob/11.x/src/Drupal/Commands/config/ConfigCommands.php#L393

**Comment by BramDriesen** [comment]
https://github.com/drush-ops/drush/pull/5837

**Comment by BramDriesen** [comment]
Commit where this issue got added: https://github.com/drush-ops/drush/pull/5448/files

**Comment by BramDriesen** [comment]
Issue got committed to 11.x
