### ISSUE TITLE
Use callable resolver in batch API to allow callbacks in service notation

### ISSUE THREAD

**Issue by escobar-ui** [drush-ops/drush#5880]
**Problem/Motivation**
The motivation is the same as this issue for the Drupal Core batch API: https://www.drupal.org/project/drupal/issues/3401873.
The batch API takes callbacks, but these have to be functions or static methods on classes.

If we use the callable resolver, we can also allow callbacks in service notation, that is, in the form `my_service:methodName`.

**Proposed resolution**
Changes similar to those made to `core/includes/batch.inc` in this [merge request](https://git.drupalcode.org/project/drupal/-/merge_requests/6130/diffs) could be implemented in `function _drush_batch_worker()` on [batch.inc](https://github.com/drush-ops/drush/blob/13.x/includes/batch.inc#L220)

**Comment by ptmkenny** [comment]
I think this is more relevant now because after upgrading to Drupal 11.4.0-rc1 (change record: [All batch related functions in locale.batch.inc, locale.bulk.inc and locale.compare.inc have been deprecated
](https://www.drupal.org/node/3589759), I'm getting this error:

```

Importing translations.

Command: drush locale:import ja /app/translations/app/ja.po --type=customized --override=customized
>  [error]  TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "Drupal\locale\LocaleImportBatch:batchImport" not found or invalid function name in _drush_batch_worker() (line 257 of /var/www/html/vendor/drush/drush/includes/batch.inc) #0 /var/www/html/vendor/drush/drush/includes/batch.inc(204): _drush_batch_worker()
> #1 /var/www/html/vendor/drush/drush/includes/batch.inc(75): _drush_batch_command()
> #2 /var/www/html/vendor/drush/drush/src/Commands/core/BatchCommands.php(25): drush_batch_command()
> #3 [internal function]: Drush\Commands\core\BatchCommands->process()
> #4 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
> #5 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
> #6 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
> #7 /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(389): Consolidation\AnnotatedCommand\CommandProcessor->process()
> #8 /var/www/html/vendor/symfony/console/Command/Command.php(341): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
> #9 /var/www/html/vendor/symfony/console/Application.php(1117): Symfony\Component\Console\Command\Command->run()
> #10 /var/www/html/vendor/drush/drush/src/Application.php(201): Symfony\Component\Console\Application->doRunCommand()
> #11 /var/www/html/vendor/symfony/console/Application.php(356): Drush\Application->doRunCommand()
> #12 /var/www/html/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRun()
> #13 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(113): Symfony\Component\Console\Application->run()
> #14 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
> #15 /var/www/html/vendor/drush/drush/drush.php(140): Drush\Runtime\Runtime->run()
> #16 /var/www/html/vendor/bin/drush.php(119): include('...')
> #17 {main}.
> TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "Drupal\locale\LocaleImportBatch:batchImport" not found or invalid function name in /var/www/html/vendor/drush/drush/includes/batch.inc on line 257 #0 /var/www/html/vendor/drush/drush/includes/batch.inc(204): _drush_batch_worker()
> #1 /var/www/html/vendor/drush/drush/includes/batch.inc(75): _drush_batch_command()
> #2 /var/www/html/vendor/drush/drush/src/Commands/core/BatchCommands.php(25): drush_batch_command()
> #3 [internal function]: Drush\Commands\core\BatchCommands->process()
> #4 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
> #5 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
> #6 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
> #7 /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(389): Consolidation\AnnotatedCommand\CommandProcessor->process()
> #8 /var/www/html/vendor/symfony/console/Command/Command.php(341): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
> #9 /var/www/html/vendor/symfony/console/Application.php(1117): Symfony\Component\Console\Command\Command->run()
> #10 /var/www/html/vendor/drush/drush/src/Application.php(201): Symfony\Component\Console\Application->doRunCommand()
> #11 /var/www/html/vendor/symfony/console/Application.php(356): Drush\Application->doRunCommand()
> #12 /var/www/html/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRun()
> #13 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(113): Symfony\Component\Console\Application->run()
> #14 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
> #15 /var/www/html/vendor/drush/drush/drush.php(140): Drush\Runtime\Runtime->run()
> #16 /var/www/html/vendor/bin/drush.php(119): include('...')
> #17 {main}
>  [warning] Drush command terminated abnormally.

In ProcessBase.php line 171:

  Unable to decode output into JSON: Syntax error

  TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "Drupal\locale\LocaleIm
  portBatch:batchImport" not found or invalid function name in _drush_batch_worker() (line 257 of /var/www/html/vendor/
  drush/drush/includes/batch.inc).


Failed command drush locale:import ja /app/translations/app/ja.po --type=customized --override=customized
```

**Comment by weitzman** [comment]
This got in.
