### ISSUE TITLE
Fix database lock issues with D11

### ISSUE THREAD

**Issue by mondrake** [drush-ops/drush#5892]
**Describe the bug**
Follow up of #5882 

There are database lock failures in tests of D11 with Drush 13.

**To Reproduce**
See tests

**Expected behavior**
No failures

**Actual behavior**
See tests

**Workaround**
None

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 13.x
| Drupal version? | 11.x
| PHP version     | 8.x
| OS?             | Mac/Linux/Windows

**Additional information**
None presently

**Comment by mondrake** [comment]
The error backtrace

```
   [error]  Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[HY000]: G  
  eneral error: 1205 Lock wait timeout exceeded; try restarting transaction:   
  INSERT INTO "cache_bootstrap" ("cid", "expire", "created", "tags", "checksu  
  m", "data", "serialized") VALUES (:db_insert_placeholder_0, :db_insert_plac  
  eholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_p  
  laceholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6) ON DUPLIC  
  ATE KEY UPDATE "cid" = VALUES("cid"), "expire" = VALUES("expire"), "created  
  " = VALUES("created"), "tags" = VALUES("tags"), "checksum" = VALUES("checks  
  um"), "data" = VALUES("data"), "serialized" = VALUES("serialized"); Array    
  (                                                                            
      [:db_insert_placeholder_0] => last_write_timestamp_cache_bootstrap       
      [:db_insert_placeholder_1] => -1                                         
      [:db_insert_placeholder_2] => 1710336042.501                             
      [:db_insert_placeholder_3] =>                                            
      [:db_insert_placeholder_4] => 0                                          
      [:db_insert_placeholder_5] => d:1710336042.502;                          
      [:db_insert_placeholder_6] => 1                                          
  )                                                                            
   in Drupal\Core\Cache\DatabaseBackend->doSetMultiple() (line 312 of /home/w  
  odby/drush/sut/core/lib/Drupal/Core/Cache/DatabaseBackend.php) #0 /home/wod  
  by/drush/sut/core/lib/Drupal/Core/Database/Query/Upsert.php(115): Drupal\my  
  sql\Driver\Database\mysql\ExceptionHandler->handleExecutionException()       
  #1 /home/wodby/drush/sut/core/lib/Drupal/Core/Cache/DatabaseBackend.php(312  
  ): Drupal\Core\Database\Query\Upsert->execute()                              
  #2 /home/wodby/drush/sut/core/lib/Drupal/Core/Cache/DatabaseBackend.php(227  
  ): Drupal\Core\Cache\DatabaseBackend->doSetMultiple()                        
  #3 /home/wodby/drush/sut/core/lib/Drupal/Core/Cache/DatabaseBackend.php(211  
  ): Drupal\Core\Cache\DatabaseBackend->setMultiple()                          
  #4 /home/wodby/drush/sut/core/lib/Drupal/Core/Cache/ChainedFastBackend.php(  
  301): Drupal\Core\Cache\DatabaseBackend->set()                               
  #5 /home/wodby/drush/sut/core/lib/Drupal/Core/Cache/ChainedFastBackend.php(  
  181): Drupal\Core\Cache\ChainedFastBackend->markAsOutdated()                 
  #6 /home/wodby/drush/sut/core/lib/Drupal/Core/Extension/ModuleHandler.php(3  
  29): Drupal\Core\Cache\ChainedFastBackend->set()                             
  #7 /home/wodby/drush/sut/core/lib/Drupal/Core/EventSubscriber/RequestCloseS  
  ubscriber.php(42): Drupal\Core\Extension\ModuleHandler->writeCache()         
  #8 [internal function]: Drupal\Core\EventSubscriber\RequestCloseSubscriber-  
  >onTerminate()                                                               
  #9 /home/wodby/drush/sut/core/lib/Drupal/Component/EventDispatcher/Containe  
  rAwareEventDispatcher.php(111): call_user_func()                             
  #10 /home/wodby/drush/vendor/symfony/http-kernel/HttpKernel.php(115): Drupa  
  l\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()        
  #11 /home/wodby/drush/sut/core/lib/Drupal/Core/StackMiddleware/StackedHttpK  
  ernel.php(63): Symfony\Component\HttpKernel\HttpKernel->terminate()          
  #12 /home/wodby/drush/sut/core/lib/Drupal/Core/DrupalKernel.php(689): Drupa  
  l\Core\StackMiddleware\StackedHttpKernel->terminate()                        
  #13 /home/wodby/drush/src/Boot/DrupalBoot8.php(326): Drupal\Core\DrupalKern  
  el->terminate()                                                              
  #14 [internal function]: Drush\Boot\DrupalBoot8->terminate()                 
  #15 {main}.                                        
```

smells to me like we are in a predicament similar to https://www.drupal.org/project/drupal/issues/3405976

The fact that this error is being thrown during termination i.e. very late in the execution may be a Drupal transaction object that did not destruct correctly (or is locked somewhere preventing the autocommit), and the db operation related to writing the cache entry gets rejected by the database lock.

**Comment by mondrake** [comment]
@weitzman apparently #5869 fixed this, right? Another case of xdebug blocking commit on destruction. Will add a note to https://www.drupal.org/project/drupal/issues/3405976

Hopefully one day we will get rid of implicit commit in Drupal.

**Comment by weitzman** [comment]
Yes, #5869 disabled Xdebug in our CircleCI. Closing.
