### ISSUE TITLE
Fatal error on cron command help

### ISSUE THREAD

**Issue by manueladan-nttdata** [drush-ops/drush#5970]
**Describe the bug**
Drush crashed requesting help for the cron command as follows:

```
> drush cron --help
 [warning] DOMDocument::createElement(): unterminated entity reference & drush core:cron XmlDescriptor.php:69
 [warning] DOMDocument::createElement(): unterminated entity reference & drush core:cron HelpDocumentBuilder.php:36
Run all cron hooks in all active modules for specified site.

Examples:
 [error]  TypeError: Cannot access offset of type string on string in Drush\Commands\help\HelpCLIFormatter->write() (line 41 of /var/www/vendor/drush/drush/src/Commands/help/HelpCLIFormatter.php) #0 /var/www/vendor/consolidation/output-formatters/src/FormatterManager.php(242): Drush\Commands\help\HelpCLIFormatter->write(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#1 /var/www/vendor/consolidation/annotated-command/src/ResultWriter.php(157): Consolidation\OutputFormatters\FormatterManager->write(Object(Symfony\Component\Console\Output\ConsoleOutput), 'helpcli', Object(Drush\Commands\help\DrushHelpDocument), Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#2 /var/www/vendor/consolidation/annotated-command/src/ResultWriter.php(88): Consolidation\AnnotatedCommand\ResultWriter->writeUsingFormatter(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Drush\Commands\help\DrushHelpDocument), Object(Consolidation\AnnotatedCommand\CommandData), 0)
#3 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(265): Consolidation\AnnotatedCommand\ResultWriter->handle(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Drush\Commands\help\DrushHelpDocument), Object(Consolidation\AnnotatedCommand\CommandData), Object(Consolidation\AnnotatedCommand\Hooks\Dispatchers\StatusDeterminerHookDispatcher), Object(Consolidation\AnnotatedCommand\Hooks\Dispatchers\ExtracterHookDispatcher))
#4 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(180): Consolidation\AnnotatedCommand\CommandProcessor->handleResults(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Object(Drush\Commands\help\DrushHelpDocument), Object(Consolidation\AnnotatedCommand\CommandData))
#5 /var/www/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /var/www/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run(Array)
#13 /var/www/vendor/drush/drush/drush(4): require('/var/www/vendor...')
#14 {main}.
TypeError: Cannot access offset of type string on string in /var/www/vendor/drush/drush/src/Commands/help/HelpCLIFormatter.php on line 41 #0 /var/www/vendor/consolidation/output-formatters/src/FormatterManager.php(242): Drush\Commands\help\HelpCLIFormatter->write(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#1 /var/www/vendor/consolidation/annotated-command/src/ResultWriter.php(157): Consolidation\OutputFormatters\FormatterManager->write(Object(Symfony\Component\Console\Output\ConsoleOutput), 'helpcli', Object(Drush\Commands\help\DrushHelpDocument), Object(Consolidation\OutputFormatters\Options\FormatterOptions))
#2 /var/www/vendor/consolidation/annotated-command/src/ResultWriter.php(88): Consolidation\AnnotatedCommand\ResultWriter->writeUsingFormatter(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Drush\Commands\help\DrushHelpDocument), Object(Consolidation\AnnotatedCommand\CommandData), 0)
#3 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(265): Consolidation\AnnotatedCommand\ResultWriter->handle(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Drush\Commands\help\DrushHelpDocument), Object(Consolidation\AnnotatedCommand\CommandData), Object(Consolidation\AnnotatedCommand\Hooks\Dispatchers\StatusDeterminerHookDispatcher), Object(Consolidation\AnnotatedCommand\Hooks\Dispatchers\ExtracterHookDispatcher))
#4 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(180): Consolidation\AnnotatedCommand\CommandProcessor->handleResults(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Object(Drush\Commands\help\DrushHelpDocument), Object(Consolidation\AnnotatedCommand\CommandData))
#5 /var/www/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /var/www/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run(Array)
#13 /var/www/vendor/drush/drush/drush(4): require('/var/www/vendor...')
#14 {main}
TypeError: Cannot access offset of type string on string in Drush\Commands\help\HelpCLIFormatter->write() (line 41 of /var/www/vendor/drush/drush/src/Commands/help/HelpCLIFormatter.php).
 [warning] Drush command terminated abnormally.
```

**To Reproduce**
Just request help on cron command.

**Expected behavior**
Same output as `drush cron:run --help`

**Actual behavior**
Crash reported.

**Workaround**
Use instead `drush cron:run --help`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.5.1.0
| Drupal version? | 10.2.5
| PHP version     | 8.1.20
| OS?             | Linux

**Additional information**
None.

**Comment by patrickcate** [comment]
I'm getting the same error when I run: `drush help maint:status`

**Comment by weitzman** [comment]
Already fixed in 12.x, awaiting release.
