### ISSUE TITLE
The site:install command with option `--yes` is throwing error

### ISSUE THREAD

**Issue by vishalkhode1** [drush-ops/drush#6002]
**Describe the bug**
The site:install command with option `--yes` is throwing error. This used to work with Drupal 9/10 by assuming following default credentials/driver i.e
```
  'database' => 'drupal',
  'username' => 'drupal',
  'password' => 'drupal',
  'prefix' => '',
  'host' => '127.0.0.1',
  'port' => '3306',
  'isolation_level' => 'READ COMMITTED',
  'driver' => 'mysql',
```

But with Drupal 11, this is throwing error.
```
$ drush site:install --yes
[warning] Undefined array key "" SiteInstallCommands.php:300
  [error]  Error: Call to a member function getInstallTasks() on null in Drush\Commands\core\SiteInstallCommands->validate() (line 300 of /Users/user1/11.x/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php) #0 /Users/user1/11.x/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php(53): Drush\Commands\core\SiteInstallCommands->validate()
#1 /Users/user1/11.x/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php(42): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->doValidator()
#2 /Users/user1/11.x/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/ValidateHookDispatcher.php(29): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->callValidator()
#3 /Users/user1/11.x/vendor/consolidation/annotated-command/src/CommandProcessor.php(195): Consolidation\AnnotatedCommand\Hooks\Dispatchers\ValidateHookDispatcher->validate()
#4 /Users/user1/11.x/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#5 /Users/user1/11.x/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(387): Consolidation\AnnotatedCommand\CommandProcessor->process()
#6 /Users/user1/11.x/vendor/symfony/console/Command/Command.php(279): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#7 /Users/user1/11.x/vendor/symfony/console/Application.php(1049): Symfony\Component\Console\Command\Command->run()
#8 /Users/user1/11.x/vendor/symfony/console/Application.php(318): Symfony\Component\Console\Application->doRunCommand()
#9 /Users/user1/11.x/vendor/symfony/console/Application.php(169): Symfony\Component\Console\Application->doRun()
#10 /Users/user1/11.x/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#11 /Users/user1/11.x/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#12 /Users/user1/11.x/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#13 /Users/user1/11.x/vendor/drush/drush/drush(4): require('...')
#14 /Users/user1/11.x/vendor/bin/drush(119): include('...')
#15 {main}. 
```

**To Reproduce**
```
$ composer create-project drupal/recommended-project:11.0.0-alpha1 11.x && cd 11.x
$ composer config minimum-stability dev
$ composer require drush/drush 
$ ./vendor/bin/drush site:install --yes
```

**Expected behavior**
The site:install command with option `--yes` should installed the site without any errors by assuming above default credentials/driver.

**Actual behavior**
The site:install command with option `--yes` is throwing error.

**Workaround**
Install the site without `--yes` option.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version  | 13.0.0-beta1
| Drupal version | 11.0.0-alpha1
| PHP version     | 8.3
| OS             | Mac

**Additional information**
Site install with Drupal 11: 
<img width="1507" alt="Drupal 11" src="https://github.com/drush-ops/drush/assets/81069167/33744ca6-53af-4189-b5bf-e60b9502c600">

Site install with Drupal 10
<img width="716" alt="Drupal 10" src="https://github.com/drush-ops/drush/assets/81069167/d4097b19-4c1a-4a2b-91df-7cafb4151f42">

**Comment by weitzman** [comment]
Please try with tip of 13.d branch. This might be fixed already.
