### ISSUE TITLE
Drush 12 throws an error with Drupal 10 (Docker based setup) 

### ISSUE THREAD

**Issue by SHIVAMKASERA** [drush-ops/drush#6088]
**Describe the bug**
while running drush cr /drush status 
PHP Fatal error:  Uncaught Error: Call to undefined method Composer\InstalledVersions::getInstallPath() in /var/www/html/vendor/drush/drush/src/DrupalFinder/DrushDrupalFinder.php:26
Stack trace:
#0 /var/www/html/vendor/drush/drush/src/Preflight/Preflight.php(354): Drush\DrupalFinder\DrushDrupalFinder->getDrupalRoot()
#1 /var/www/html/vendor/drush/drush/src/Preflight/Preflight.php(274): Drush\Preflight\Preflight->preferredSite()
#2 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(58): Drush\Preflight\Preflight->preflight()
#3 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#4 /var/www/html/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#5 /var/www/html/vendor/drush/drush/drush(4): require('...')
#6 {main}
  thrown in /var/www/html/vendor/drush/drush/src/DrupalFinder/DrushDrupalFinder.php on line 26
 
Fatal error: Uncaught Error: Call to undefined method Composer\InstalledVersions::getInstallPath() in /var/www/html/vendor/drush/drush/src/DrupalFinder/DrushDrupalFinder.php:26
Stack trace:
#0 /var/www/html/vendor/drush/drush/src/Preflight/Preflight.php(354): Drush\DrupalFinder\DrushDrupalFinder->getDrupalRoot()
#1 /var/www/html/vendor/drush/drush/src/Preflight/Preflight.php(274): Drush\Preflight\Preflight->preferredSite()
#2 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(58): Drush\Preflight\Preflight->preflight()
#3 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#4 /var/www/html/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#5 /var/www/html/vendor/drush/drush/drush(4): require('...')
#6 {main}
  thrown in /var/www/html/vendor/drush/drush/src/DrupalFinder/DrushDrupalFinder.php on line 26

**To Reproduce**
Run dursh cr command in drupal container

**Expected behavior**
Shoudl clear the cache

**Actual behavior**
Fatal error

**Workaround**
Is there another way to do the desired action?

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x
| Drupal version? | 10.x
| PHP version     | 8.x
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
Please paste in output of `composer show`

**Comment by SHIVAMKASERA** [comment]
Below is the outpot for "composer show"

asm89/stack-cors                               v2.2.0            Cross-origin resource sharing library and stack middleware
behat/mink                                     v1.11.0           Browser controller/emulator abstraction for PHP
behat/mink-browserkit-driver                   v2.2.0            Symfony2 BrowserKit driver for Mink framework
behat/mink-goutte-driver                       v2.0.0            Goutte driver for Mink framework
chi-teck/drupal-code-generator                 3.6.1             Drupal code generator
commerceguys/addressing                        v2.2.2            Addressing library powered by CLDR and Google's address data.
commerceguys/intl                              v2.0.6            Internationalization library powered by CLDR data.
composer/installers                            v2.3.0            A multi-framework Composer library installer
composer/semver                                3.4.2             Semver library that offers utilities, version constraint parsing and validat...
consolidation/annotated-command                4.10.0            Initialize Symfony Console commands from annotated command class methods.
consolidation/config                           2.1.2             Provide configuration services for a commandline tool.
consolidation/filter-via-dot-access-data       2.0.2             This project uses dflydev/dot-access-data to provide simple output filtering...
consolidation/log                              3.1.0             Improved Psr-3 / Psr\Log logger based on Symfony Console components.
consolidation/output-formatters                4.5.0             Format text by applying transformations provided by plug-in formatters.
consolidation/robo                             4.0.6             Modern task runner
consolidation/self-update                      2.2.0             Provides a self:update command for Symfony Console applications.
consolidation/site-alias                       4.1.0             Manage alias records for local and remote sites.
consolidation/site-process                     5.4.0             A thin wrapper around the Symfony Process Component that allows applications...
cweagans/composer-patches                      1.7.3             Provides a way to patch Composer packages.
dealerdirect/phpcodesniffer-composer-installer v0.7.2            PHP_CodeSniffer Standards Composer Installer Plugin
dekor/php-array-table                          2.0               PHP Library for printing associative arrays as text table (similar to mysql ...
dflydev/dot-access-data                        v3.0.3            Given a deep data structure, access data by dot notation.
doctrine/annotations                           1.14.3            Docblock Annotations Parser
doctrine/collections                           2.2.2             PHP Doctrine Collections library that adds additional functionality on top o...
doctrine/common                                3.4.4             PHP Doctrine Common project is a library that provides additional functional...
doctrine/deprecations                          1.1.3             A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging wi...
doctrine/event-manager                         2.0.1             The Doctrine Event Manager is a simple PHP event system that was built to be...
doctrine/instantiator                          2.0.0             A small, lightweight utility to instantiate objects in PHP without invoking ...
doctrine/lexer                                 2.1.1             PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive De...
doctrine/persistence                           3.3.3             The Doctrine Persistence project is a set of shared interfaces and functiona...
dompdf/dompdf                                  v2.0.8            DOMPDF is a CSS 2.1 compliant HTML to PDF converter
drupal/address                                 2.0.2             Provides functionality for storing, validating and displaying international ...
drupal/bat                                     10.2.0            Booking and Availability Management Framework
drupal/bat_api                                 3.1.0             API access to BAT Booking and Availability Data for Drupal
drupal/bat_booking                             10.2.0            BAT Booking
drupal/bat_event                               10.2.0            Create and administer events for BAT.
drupal/bat_event_series                        10.2.0            Create and administer series of BAT events.
drupal/bat_event_ui                            10.2.0            Interface support to the BAT Event module.
drupal/bat_fullcalendar                        10.2.0            Provides a generalized API for manipulating FullCalendar widgets for BAT
drupal/bat_unit                                10.2.0            Create and manage units (e.g. rooms).
drupal/bee                                     3.1.0             Bookable Entities Everywhere
drupal/better_exposed_filters                  6.0.6             Replaces the Views default single- or multi-select boxes with more advanced ...
drupal/block_field                             1.0.0-rc5         Provides a field that allows a content entity to create and configure custom...
drupal/classy                                  1.0.2             The Classy base theme from Drupal 8/9 moved to contrib
drupal/coder                                   8.3.24            Coder is a library to review Drupal code.
drupal/commerce                                2.39.0            Drupal Commerce is a flexible eCommerce solution.
drupal/commerce_number_pattern                 2.39.0            Provides configurable patterns for generating sequential numbers.
drupal/commerce_order                          2.39.0            Defines the Order entity and associated features.
drupal/commerce_price                          2.39.0            Defines the Currency entity.
drupal/commerce_product                        2.39.0            Defines the Product entity and associated features.
drupal/commerce_store                          2.39.0            Defines the Store entity and associated features.
drupal/config_filter                           2.6.0             Config Filter allows other modules to interact with a ConfigStorage through ...
drupal/config_ignore                           3.3.0             Ignore certain configuration during import and export.
drupal/cookies                                 1.2.12            Cookie consent tool.
drupal/core                                    10.3.2            Drupal is an open source content management platform powering millions of we...
drupal/core-composer-scaffold                  10.3.2            A flexible Composer project scaffold builder.
drupal/core-project-message                    10.3.2            Adds a message after Composer installation.
drupal/core-recommended                        10.3.2            Core and its dependencies with known-compatible minor versions. Require this...
drupal/crop                                    2.4.0             Provides storage and API for image crops.
drupal/csv_serialization                       4.0.1             Provides CSV as a serialization format.
drupal/devel                                   5.3.1             Various blocks, pages, and functions for developers.
drupal/drupal_test_assertions                  dev-1.0.x fde83a1 Drupal assertions.
drupal/easy_breadcrumb                         2.0.8             Adds configuration to the system breadcrumbs.
drupal/elasticsearch_connector                 7.0.0-alpha5      Elasticsearch Connector module for Drupal.
drupal/email_attachment                        1.5.0             Module to attach files programmatically to emails.
drupal/emptyparagraphkiller                    1.0.0-beta1       Filters out pesky empty paragraphs.
drupal/entity                                  1.5.0             Provides expanded entity APIs, which will be moved to Drupal core one day.
drupal/entity_browser                          2.11.0            Entity browsing and selecting component.
drupal/entity_browser_entity_form              2.11.0            Entity browser inline entity form integration.
drupal/entity_reference_quantity               3.0.0             Entity reference field with quantity.
drupal/entity_reference_revisions              1.12.0            Entity Reference Revisions
drupal/environment_indicator                   4.0.19            Environment Indicator adds some visual cuest to indicate which copy of the s...
drupal/facets                                  2.0.8             The Facet module allows site builders to easily create and manage faceted se...
drupal/field_group                             3.6.0             Provides the field_group module.
drupal/field_time                              1.0.0-beta2       Provides Time and TimeRange field for Drupal 8 & 9
drupal/focal_point                             2.1.1             Focal Point allows content creators to mark the most important part of an im...
drupal/fullcalendar_library                    2.3.0             Fullcalendar library
drupal/hal                                     2.0.3             Hypermedia Application Language (HAL)
drupal/inline_entity_form                      3.0.0-rc20        Provides a widget for inline management (creation, modification, removal) of...
drupal/intl_date                               1.1.2             Fine-grained localized date formatting.
drupal/jquery_once                             1.0.0             Include dependency to jQuery and the former jQuery.once() library.
drupal/jquery_ui                               1.7.0             Provides jQuery UI library.
drupal/jquery_ui_datepicker                    2.1.0             Provides jQuery UI Datepicker library.
drupal/jquery_ui_slider                        2.1.0             Provides jQuery UI Slider library.
drupal/jquery_ui_touch_punch                   1.1.1             Provides jQuery UI Touch Punch library.
drupal/lang_dropdown                           2.1.0             Provides a dropdown select to switch between available languages.
drupal/media_entity_browser                    2.0.0             This module provides an Entity Browser for Media.
drupal/office_hours                            1.17.0            Defines a 'weekly office hours' field type, allowing you to specify when an ...
drupal/pantheon_advanced_page_cache            2.2.0             Advanced page cache capabilities for Pantheon.
drupal/paragraphs                              1.18.0            Enables the creation of Paragraphs entities.
drupal/pathauto                                1.13.0            Provides a mechanism for modules to automatically generate aliases for the c...
drupal/pdf_generator                           2.0.6             Provides a service to generate pdfs and a views display mode.
drupal/permissions_filter                      1.6.0             Create a filter for permission page.
drupal/pluggable_entity_view_builder           1.1.17            Define entity view builders as plugins, defined per bundle.
drupal/profile                                 1.11.0            Provides configurable user profiles.
drupal/rat                                     1.0.0            
drupal/rdf                                     2.1.1             Enriches your content with metadata to let other applications (e.g. search e...
drupal/redirect                                1.10.0            Allows users to redirect from old URLs to new URLs.
drupal/redis                                   1.7.0             Integration of Drupal with the Redis key-value store.
drupal/search_api                              1.35.0            Provides a generic framework for modules offering search capabilities.
drupal/select2                                 1.15.0            Integration with the select2 JavaScript library.
drupal/services                                5.0.0-beta10      A standardized solution of integrating external applications with Drupal.
drupal/seven                                   1.0.0             The Seven theme from Drupal 8/9 moved to contrib
drupal/simple_sitemap                          4.1.9             Creates a standard conform hreflang XML sitemap of the site content and prov...
drupal/stable                                  2.1.0             A base theme using Drupal core markup and CSS.
drupal/stage_file_proxy                        1.4.0             Provides stage_file_proxy module.
drupal/state_machine                           1.12.0            Provides code-driven workflow functionality.
drupal/symfony_mailer                          1.4.1             Symfony Mailer
drupal/token                                   1.15.0            Provides a user interface for the Token API, some missing core tokens.
drupal/upgrade_status                          4.3.1             Review Drupal major upgrade readiness of the environment and components of t...
drupal/viewsreference                          2.0.0-beta9       Views reference
drush/drush                                    12.5.3            Drush is a command line shell and scripting interface for Drupal, a veritabl...
easyrdf/easyrdf                                1.1.1             EasyRdf is a PHP library designed to make it easy to consume and produce RDF.
egulias/email-validator                        4.0.2             A library for validating emails against several RFCs
elasticsearch/elasticsearch                    v7.17.2           PHP Client for Elasticsearch
ezimuel/guzzlestreams                          3.1.0             Fork of guzzle/streams (abandoned) to be used with elasticsearch-php
ezimuel/ringphp                                1.2.2             Fork of guzzle/RingPHP (abandoned) to be used with elasticsearch-php
ezyang/htmlpurifier                            v4.17.0           Standards compliant HTML filter written in PHP
fabpot/goutte                                  v4.0.3            A simple PHP Web Scraper
fullcalendar/fullcalendar                      6.1.1            
graham-campbell/result-type                    v1.1.3            An Implementation Of The Result Type
grasmash/expander                              3.0.0             Expands internal property references in PHP arrays file.
grasmash/yaml-cli                              3.2.1             A command line tool for reading and manipulating yaml files.
guzzlehttp/guzzle                              7.8.2             Guzzle is a PHP HTTP client library
guzzlehttp/promises                            2.0.3             Guzzle promises library
guzzlehttp/psr7                                2.6.3             PSR-7 message implementation that also provides common utility methods
html2text/html2text                            4.3.1             Converts HTML to formatted plain text
jfeltkamp/cookiesjsr                           1.0.13            Cookie consent tool.
league/container                               4.2.2             A fast and intuitive dependency injection container.
league/csv                                     9.16.0            CSV data manipulation made easy in PHP
maennchen/zipstream-php                        3.1.0             ZipStream is a library for dynamically streaming dynamic zip files from PHP ...
makinacorpus/php-lucene                        1.2.1             Minimalistic, feature-rich, PHP Lucene syntax query builder
markbaker/complex                              3.0.2             PHP Class for working with complex numbers
markbaker/matrix                               3.0.1             PHP Class for working with matrices
masterminds/html5                              2.9.0             An HTML5 parser and serializer.
mck89/peast                                    v1.16.3           Peast is PHP library that generates AST for JavaScript code
mglaman/phpstan-drupal                         1.1.10            Drupal extension and rules for PHPStan
mpyw/phpunit-patch-serializable-comparison     v0.0.2            Fixes assertSame/assertEquals serialization errors running in separate proce...
myclabs/deep-copy                              1.12.0            Create deep copies (clones) of your objects
natxet/cssmin                                  v3.0.6            Minifying CSS
nikic/php-parser                               v5.1.0            A PHP parser written in PHP
nodespark/des-connector                        7.x-dev 54ef32a   An abstraction library for Elasticsearch Connector module for Drupal.
npm-asset/select2                              4.0.13           
npm-asset/slick-carousel                       1.8.1            
nyholm/dsn                                     2.0.1             Parse your DSN strings in a powerful and flexible way
oomphinc/composer-installers-extender          2.0.1             Extend the composer/installers plugin to accept any arbitrary package type.
palantirnet/drupal-rector                      0.12.2            Instant fixes for your Drupal code by using Rector.
patchwork/jsqueeze                             v2.0.5            Efficient JavaScript minification in PHP
pear/archive_tar                               1.5.0             Tar file management class with compression support (gzip, bzip2, lzma2)
pear/console_getopt                            v1.4.3            More info available on: http://pear.php.net/package/Console_Getopt
pear/pear-core-minimal                         v1.10.15          Minimal set of PEAR core files to be used as composer dependency
pear/pear_exception                            v1.0.2            The PEAR Exception base class.
phar-io/manifest                               2.0.4             Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                                3.2.1             Library for handling version information and constraints
phenx/php-font-lib                             0.5.6             A library to read, parse, export and make subsets of different types of font...
phenx/php-svg-lib                              0.5.4             A library to read, parse and export to PDF SVG files.
phootwork/collection                           v3.2.2            The phootwork library fills gaps in the php language and provides better sol...
phootwork/lang                                 v3.2.2            Missing PHP language constructs
phpdocumentor/reflection-common                2.2.0             Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock              5.4.1             With this component, a library can provide support for annotations via DocBl...
phpdocumentor/type-resolver                    1.8.2             A PSR-5 based resolver of Class names, Types and Structural Element Names
phpoffice/phpspreadsheet                       1.29.0            PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Sprea...
phpoption/phpoption                            1.9.3             Option Type for PHP
phpowermove/docblock                           v4.0              PHP Docblock parser and generator. An API to read and write Docblocks.
phpspec/prophecy                               v1.19.0           Highly opinionated mocking framework for PHP 5.3+
phpspec/prophecy-phpunit                       v2.2.0            Integrating the Prophecy mocking library in PHPUnit test cases
phpstan/phpdoc-parser                          1.29.1            PHPDoc parser with support for nullable, intersection and generic types
phpstan/phpstan                                1.4.6             PHPStan - PHP Static Analysis Tool
phpstan/phpstan-deprecation-rules              1.0.0             PHPStan rules for detecting usage of deprecated classes, methods, properties...
phpunit/php-code-coverage                      9.2.31            Library that provides collection, processing, and rendering functionality fo...
phpunit/php-file-iterator                      3.0.6             FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                            3.1.1             Invoke callables with a timeout
phpunit/php-text-template                      2.0.4             Simple template engine.
phpunit/php-timer                              5.0.3             Utility class for timing
phpunit/phpunit                                9.6.20            The PHP Unit Testing framework.
politsin/jquery-ui-touch-punch                 1.0               Extension to jQuery UI for mobile touch event support.
psr/cache                                      3.0.0             Common interface for caching libraries
psr/container                                  2.0.2             Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                           1.0.0             Standard interfaces for event handling.
psr/http-client                                1.0.3             Common interface for HTTP clients
psr/http-factory                               1.1.0             PSR-17: Common interfaces for PSR-7 HTTP message factories
psr/http-message                               2.0               Common interface for HTTP messages
psr/log                                        3.0.0             Common interface for logging libraries
psr/simple-cache                               3.0.0             Common interfaces for simple caching
psy/psysh                                      v0.12.4           An interactive shell for modern PHP.
ralouphie/getallheaders                        3.0.3             A polyfill for getallheaders.
react/promise                                  v2.11.0           A lightweight implementation of CommonJS Promises/A for PHP
rector/rector                                  0.12.17           Instant Upgrade and Automated Refactoring of any PHP code
rlanvin/php-rrule                              v2.5.1            Lightweight and fast recurrence rules for PHP (RFC 5545)
roomify/bat                                    1.4.0             A booking and availability management library
ruflin/elastica                                7.3.2             Elasticsearch Client
sabberworm/php-css-parser                      v8.6.0            Parser for CSS Files written in PHP
scssphp/scssphp                                v1.12.1           scssphp is a compiler for SCSS written in PHP.
sebastian/cli-parser                           1.0.2             Library for parsing CLI options
sebastian/code-unit                            1.0.8             Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup             2.0.3             Looks up which function or method a line of code belongs to
sebastian/comparator                           4.0.8             Provides the functionality to compare PHP values for equality
sebastian/complexity                           2.0.3             Library for calculating the complexity of PHP code units
sebastian/diff                                 4.0.6             Diff implementation
sebastian/environment                          5.1.5             Provides functionality to handle HHVM/PHP environments
sebastian/exporter                             4.0.6             Provides the functionality to export PHP variables for visualization
sebastian/global-state                         5.0.7             Snapshotting of global state
sebastian/lines-of-code                        1.0.4             Library for counting the lines of code in PHP source code
sebastian/object-enumerator                    4.0.4             Traverses array structures and object graphs to enumerate all referenced obj...
sebastian/object-reflector                     2.0.4             Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context                    4.0.5             Provides functionality to recursively process PHP variables
sebastian/resource-operations                  3.0.4             Provides a list of PHP built-in functions that operate on resources
sebastian/type                                 3.2.1             Collection of value objects that represent the types of the PHP type system
sebastian/version                              3.0.2             Library that helps with managing the version number of Git-hosted PHP projects
sirbrillig/phpcs-variable-analysis             v2.11.19          A PHPCS sniff to detect problems with variables.
slevomat/coding-standard                       8.15.0            Slevomat Coding Standard for PHP_CodeSniffer complements Consistence Coding ...
squizlabs/php_codesniffer                      3.10.2            PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violatio...
symfony/browser-kit                            v6.4.8            Simulates the behavior of a web browser, allowing you to make requests, clic...
symfony/console                                v6.4.10           Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                           v6.4.8            Converts CSS selectors to XPath expressions
symfony/dependency-injection                   v6.4.10           Allows you to standardize and centralize the way objects are constructed in ...
symfony/deprecation-contracts                  v3.5.0            A generic function and convention to trigger deprecation notices
symfony/dom-crawler                            v6.4.8            Eases DOM navigation for HTML and XML documents
symfony/error-handler                          v6.4.10           Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher                       v6.4.8            Provides tools that allow your application components to communicate with ea...
symfony/event-dispatcher-contracts             v3.5.0            Generic abstractions related to dispatching event
symfony/filesystem                             v6.4.9            Provides basic utilities for the filesystem
symfony/finder                                 v6.4.10           Finds files and directories via an intuitive fluent interface
symfony/http-client                            v6.4.10           Provides powerful methods to fetch HTTP resources synchronously or asynchron...
symfony/http-client-contracts                  v3.5.0            Generic abstractions related to HTTP clients
symfony/http-foundation                        v6.4.10           Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                            v6.4.10           Provides a structured process for converting a Request into a Response
symfony/mailer                                 v6.4.9            Helps sending emails
symfony/mime                                   v6.4.9            Allows manipulating MIME messages
symfony/phpunit-bridge                         v5.4.42           Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-ctype                         v1.29.0           Symfony polyfill for ctype functions
symfony/polyfill-iconv                         v1.29.0           Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme                 v1.29.0           Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn                      v1.29.0           Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer               v1.29.0           Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                      v1.29.0           Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                         v1.30.0           Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                         v1.30.0           Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                         v1.30.0           Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81                         v1.30.0           Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/polyfill-php83                         v1.29.0           Symfony polyfill backporting some PHP 8.3+ features to lower PHP versions
symfony/process                                v6.4.8            Executes commands in sub-processes
symfony/psr-http-message-bridge                v6.4.10           PSR HTTP message bridge
symfony/routing                                v6.4.10           Maps an HTTP request to a set of configuration variables
symfony/serializer                             v6.4.10           Handles serializing and deserializing data structures, including object grap...
symfony/service-contracts                      v3.5.0            Generic abstractions related to writing services
symfony/string                                 v6.4.10           Provides an object-oriented API to strings and deals with bytes, UTF-8 code ...
symfony/translation-contracts                  v3.5.0            Generic abstractions related to translation
symfony/validator                              v6.4.10           Provides tools to validate values
symfony/var-dumper                             v6.4.10           Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                           v6.4.9            Allows exporting any serializable PHP data structure to plain PHP code
symfony/yaml                                   v6.4.8            Loads and dumps YAML files
tecnickcom/tcpdf                               6.7.5             TCPDF is a PHP class for generating PDF documents and barcodes.
theseer/tokenizer                              1.2.3             A small library for converting tokenized PHP source code into XML and potent...
tijsverkoyen/css-to-inline-styles              v2.2.7            CssToInlineStyles is a class that enables you to convert HTML-pages/files in...
totten/lurkerlite                              1.3.0             Resource Watcher - Lightweight edition of henrikbjorn/lurker with no depende...
twig/twig                                      v3.10.3           Twig, the flexible, fast, and secure template language for PHP
vlucas/phpdotenv                               v5.6.1            Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER...
webflo/drupal-finder                           1.3.1             Helper class to locate a Drupal installation.
webmozart/assert                               1.11.0            Assertions to validate method input/output with nice error messages.
weitzman/drupal-test-traits                    1.x-dev 98864ea   Traits for testing Drupal sites that have user content (versus unpopulated s...--

**Comment by weitzman** [comment]
Can you paste output of `composer --version`. It must be >=2 for drush to work. If it is, you must figure out why you aren't getting the runtime utilities from composer. See https://getcomposer.org/doc/07-runtime.md#runtime-composer-utilities

**Comment by SHIVAMKASERA** [comment]
Composer version 2.6.4.

**Comment by kriboogh** [comment]
scratch my comment (other issue not related)

**Comment by weitzman** [comment]
is it fixed if you run `composer require composer-runtime-api ^2.0`
