### ISSUE TITLE
Remove --db-url from site alias definition docs

### ISSUE THREAD

**Issue by bartfeenstra** [drush-ops/drush#831]
Using a freshly fetched Drupal 8 and PHP 5.5.16, the site-install command fails with the following:

```
PHP Fatal error:  Call to a member function db_spec() on a non-object in /Users/bart/.composer/vendor/drush/drush/commands/core/site_install.drush.inc on line 90
PHP Stack trace:
PHP   1. {main}() /Users/bart/.composer/vendor/drush/drush/drush.php:0
PHP   2. drush_main() /Users/bart/.composer/vendor/drush/drush/drush.php:16
PHP   3. Drush\Boot\DrupalBoot->bootstrap_and_dispatch() /Users/bart/.composer/vendor/drush/drush/drush.php:76
PHP   4. drush_dispatch() /Users/bart/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php:46
PHP   5. call_user_func_array:{/Users/bart/.composer/vendor/drush/drush/includes/command.inc:178}() /Users/bart/.composer/vendor/drush/drush/includes/command.inc:178
PHP   6. drush_command() /Users/bart/.composer/vendor/drush/drush/includes/command.inc:178
PHP   7. _drush_invoke_hooks() /Users/bart/.composer/vendor/drush/drush/includes/command.inc:210
PHP   8. call_user_func_array:{/Users/bart/.composer/vendor/drush/drush/includes/command.inc:359}() /Users/bart/.composer/vendor/drush/drush/includes/command.inc:359
PHP   9. drush_core_pre_site_install() /Users/bart/.composer/vendor/drush/drush/includes/command.inc:359

Fatal error: Call to a member function db_spec() on a non-object in /Users/bart/.composer/vendor/drush/drush/commands/core/site_install.drush.inc on line 90

Call Stack:
    0.0002     237552   1. {main}() /Users/bart/.composer/vendor/drush/drush/drush.php:0
    0.0136    2369240   2. drush_main() /Users/bart/.composer/vendor/drush/drush/drush.php:16
    0.1892    7339824   3. Drush\Boot\DrupalBoot->bootstrap_and_dispatch() /Users/bart/.composer/vendor/drush/drush/drush.php:76
    0.2015    5942312   4. drush_dispatch() /Users/bart/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php:46
    0.3068    8161184   5. call_user_func_array:{/Users/bart/.composer/vendor/drush/drush/includes/command.inc:178}() /Users/bart/.composer/vendor/drush/drush/includes/command.inc:178
    0.3068    8161504   6. drush_command() /Users/bart/.composer/vendor/drush/drush/includes/command.inc:178
    0.3070    8162680   7. _drush_invoke_hooks() /Users/bart/.composer/vendor/drush/drush/includes/command.inc:210
    0.3078    8194592   8. call_user_func_array:{/Users/bart/.composer/vendor/drush/drush/includes/command.inc:359}() /Users/bart/.composer/vendor/drush/drush/includes/command.inc:359
    0.3078    8195296   9. drush_core_pre_site_install() /Users/bart/.composer/vendor/drush/drush/includes/command.inc:359

Drush command terminated abnormally due to an unrecoverable error.                                                                                                            [error]
Error: Call to a member function db_spec() on a non-object in /Users/bart/.composer/vendor/drush/drush/commands/core/site_install.drush.inc, line 90
```

**Comment by davidlukac** [comment]
I get the same error when running Drush commands (e.g. `drush @davidlukac.prod uli`)on my hosting. I'm using a Drush alias which looks like this:
```
<?php

$aliases['prod'] = array(
  'uri' => 'davidlukac.com',
  'root' => '/home/davidlukac.com/web',
  'databases' => array(
    'default' => array(
      'default' => array(
        'database' => 'dbname',
        'username' => 'username',
        'password' => 'somepassword',
        'host' => 'mariadb55.websupport.sk',
        'port' => '3310',
        'driver' => 'mysqli',
        'prefix' => '',
      ),
    ),
  ),
 );
```

The DB credentials are correct - I can connect to the DB e.g. using SequelPro.

When I change the driver to `mysql` I get different error:

```
uid111384@shellserver:~/davidlukac.com/web/sites$ drush @davidlukac.prod uli
exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in         [error]
/home/davidlukac.com/web/includes/database/database.inc:307
Stack trace:
#0 /home/davidlukac.com/web/includes/database/database.inc(307): PDO->__construct('mysql:host=loca...', 'dbdbdb', 'pwdpwdpwd', Array)
#1 /home/davidlukac.com/web/includes/database/mysql/database.inc(55): DatabaseConnection->__construct('mysql:host=loca...', 'dbdbdb', 'pwdpwdpwd', Array)
#2 /home/davidlukac.com/web/includes/database/database.inc(1689): DatabaseConnection_mysql->__construct(Array)
#3 /home/davidlukac.com/web/includes/database/database.inc(1479): Database::openConnection('default', 'default')
#4 /home/davidlukac.com/web/includes/database/database.inc(2350): Database::getConnection('default')
#5 /home/davidlukac.com/web/includes/lock.inc(167): db_query('SELECT expire, ...', Array)
#6 /home/davidlukac.com/web/includes/lock.inc(146): lock_may_be_available('variable_init')
#7 /home/davidlukac.com/web/includes/bootstrap.inc(927): lock_acquire('variable_init', 1)
#8 /home/davidlukac.com/web/includes/bootstrap.inc(2480): variable_initialize(Array)
#9 /home/davidlukac.com/web/includes/bootstrap.inc(2244): _drupal_bootstrap_variables()
#10 /home/davidlukac.com/web/includes/bootstrap.inc(2378): drupal_bootstrap(3, false)
#11 /home/davidlukac.com/web/includes/bootstrap.inc(2236): _drupal_bootstrap_page_cache()
#12 /home/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot7.php(74): drupal_bootstrap(7)
#13 /home/.composer/vendor/drush/drush/includes/bootstrap.inc(336): Drush\Boot\DrupalBoot7->bootstrap_drupal_full()
#14 /home/.composer/vendor/drush/drush/commands/user/user.drush.inc(388): drush_bootstrap(5)
#15 [internal function]: drush_user_login()
#16 /home/.composer/vendor/drush/drush/includes/command.inc(364): call_user_func_array('drush_user_logi...', Array)
#17 /home/.composer/vendor/drush/drush/includes/command.inc(215): _drush_invoke_hooks(Array, Array)
#18 [internal function]: drush_command()
#19 /home/.composer/vendor/drush/drush/includes/command.inc(183): call_user_func_array('drush_command', Array)
#20 /home/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#21 /home/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#22 /home/.composer/vendor/drush/drush/drush.php(11): drush_main()
#23 {main}
```

**Comment by weitzman** [comment]
You can't specify databases reliably in a site alias. Drush uses the site's settings.php during bootstrap. This is a dupe of various other issues.

**Comment by weitzman** [comment]
@greg-1-anderson  - maybe we should remove databases from example.aliases.drushrc.php?

**Comment by greg-1-anderson** [comment]
Yes, I agree. Now that sql-sync is always making remote calls for its various operations, I don't think that `databases` has any purpose in site aliases any longer. I'll put together a PR to remove it from the documentation, and various places in the `site-alias` command that offer to build a `databases` record for you.

Should we also take this out in Drush 7?  It serves no purpose there either.

**Comment by weitzman** [comment]
Yes, we should at least remove from docs in D7. maybe the full PR can be merged there as well.

**Comment by davidlukac** [comment]
Hm, so what would be a workaround for situation where the environment where drush is being run and site itself is being run are different and therefore database connection string differs as well (one is ext. connection and another one is `localhost)? Would a `dummy` settings.php referenced in the Drush alias using `%script` variable work? E.g. `'%site' => 'sites/davidlukac.com.drush/',`? Would it include the DB string from there then?

**Comment by greg-1-anderson** [comment]
It depends on what you mean by "external connection".

What Drupal cares about is that there should be a web configuration that points incoming requests for a given URL to a certain document root, and that said document root should be configured to execute .php files.  If a named host is used (e.g. http://example.com), then that URI is used to find the right folder that contains the right settings.php file.  If none is found, then sites/default/settings.php is used.

Drush is very similar, except instead of a web configuration file, Drush expects the --root option to be provided, either as a commandline option, in a site alias, or implicitly via the current working directory. Drush uses this information to find the document root.  Similarly, Drush examines the --uri option to determine which named host to use.  Drush then searches for the settings.php file in the same way that Drupal would when called via a web browser; if none is found, then sites/default/settings.php is used.

The database options are always read by Drupal's bootstrap, and they are always taken from a settings.php file.  Drush never tries to inject database settings for Drupal; it merely sets up the conditions of the call to emulate what happens in a web request.

**Comment by greg-1-anderson** [comment]
So, it turns out that the sql-sync command still relies on the code in sitealiases.inc to add database information into an alias record, but it only uses it to report the database names in prompts.

We can easily fix up the documentation, but removing the superfluous code would require reworking sql-sync a bit.

**Comment by davidlukac** [comment]
So it looks that the workaround I described above seems to _"kinda"_ work. What I've done:
- I've create a copy of my `settings.php` located in the _usual_ folder in `sites` (in my case `sites/davidlukac.com`,
- and placed this copy into a dummy `sites` folder - `sites/davidlukac.com-drush`,
- I have changed the DB connection string in the _dummy_ one, so it fits the given environment (since the original problem was, that DB connection string should be different on server from where the `drush` is being run as oppose to the web server, and `drush` is ignoring DB connection string specified directly in Drush alias),
- I have change my `drush` alias to _look_ at the _dummy_ sites folder like this:
```
<?php
$site = 'sites/davidlukac.com-drush/';
$aliases['prod'] = array(
  'uri' => 'davidlukac.com',
  'root' => '/home/davidlukac.com/web',
  'path-aliases' => array(
    '%drush' => '/home/.composer/vendor/drush/drush',
    '%site' => $site,
  ),
  '%site' => $site,
  '%dump-dir' => '~/drush.dbdumps',
  '%files' => '/home/davidlukac.com/web/sites/davidlukac.com/files',
);
```

Now the `drush` is able to bootstrap the site and connect to DB:
```
~/davidlukac.com/web$ drush @davidlukac.prod status
 Drupal version                  :  7.37
 Site URI                        :  davidlukac.com
 Database driver                 :  mysql
 Database hostname               :  *****
 Database port                   :  ****
 Database username               :  ****
 Database name                   :  ****
 Drupal bootstrap                :  Successful
 Drupal user                     :
 Default theme                   :  bartik
 Administration theme            :  bartik
 PHP executable                  :  /usr/bin/php
 PHP configuration               :  /etc/php5/cli/php.ini
 PHP OS                          :  Linux
 Drush script                    :  /home/.composer/vendor/drush/drush/drush.php
 Drush version                   :  8.0-dev
 Drush temp directory            :  /tmp
 Drush configuration             :
 Drush alias files               :  /home/davidlukac.com/web/drush/davidlukac.aliases.drushrc.php
 Install profile                 :  davids_blog
 Drupal root                     :  /home/davidlukac.com/web
 Site path                       :  sites/davidlukac.com
 File directory path             :  sites/davidlukac.com/files
 Temporary file directory path   :  /apachetmp/upload
```

BUT, running `drush @davidlukac.prod uli` does generate the login link, but the site says `Access Denied` :-(. Changing the password via `drush` and logging in afterwards works though. Any ideas what that `uli` issue may relate to?
